// Code generated by splitting main.go. Part of package main.
package novodb

import (
	"fmt"
	badger "github.com/dgraph-io/badger/v4"
	"go.uber.org/zap"
	"os"
	"path/filepath"
	"runtime"
	"sync"
	"time"
)

type dbPool struct {
	mu     sync.Mutex
	dbs    map[string]*badger.DB
	cache  *L1Cache
	l2     *L2IndexCache
	dirMgr *DirectoryManager
	closed bool
}

func newDBPool(cache *L1Cache, l2 *L2IndexCache, dirMgr *DirectoryManager) *dbPool {
	return &dbPool{
		dbs:    make(map[string]*badger.DB),
		cache:  cache,
		l2:     l2,
		dirMgr: dirMgr,
	}
}

func (p *dbPool) openDataPath(path string) (*badger.DB, error) {
	p.mu.Lock()
	defer p.mu.Unlock()

	if p.closed {
		return nil, fmt.Errorf("db pool is closed")
	}

	if db, ok := p.dbs[path]; ok {
		return db, nil
	}

	if err := os.MkdirAll(path, 0750); err != nil {
		return nil, err
	}

	opts := badger.DefaultOptions(path).
		WithLogger(nil).
		WithCompression(2).
		WithValueLogFileSize(badgerValueLogSize).
		WithMemTableSize(int64(badgerMemTableSize)).
		WithNumMemtables(badgerNumMemTables).
		WithNumLevelZeroTables(badgerNumLevelZeroTables).
		WithBlockCacheSize(badgerBlockCacheSize).
		WithNumVersionsToKeep(1).
		WithSyncWrites(false).
		WithDetectConflicts(true).
		WithValueThreshold(badgerValueThreshold)

	db, err := badger.Open(opts)
	if err != nil {
		return nil, fmt.Errorf("opening badger at %s: %w", path, err)
	}

	p.dbs[path] = db
	log().Info("BadgerDB opened",
		zap.String("path", path))
	return db, nil
}

func (p *dbPool) openBlock(dbName, blockName string) (*badger.DB, error) {
	path := p.dirMgr.BlockDataPath(dbName, blockName)
	return p.openDataPath(path)
}

func (p *dbPool) openUserDB() (*badger.DB, error) {
	path := filepath.Join(p.dirMgr.dataRoot, usersDBName)
	return p.openDataPath(path)
}

func (p *dbPool) openSystemDB() (*badger.DB, error) {
	path := filepath.Join(p.dirMgr.dataRoot, systemDB)
	return p.openDataPath(path)
}

func (p *dbPool) closeAll() {
	p.mu.Lock()
	defer p.mu.Unlock()
	p.closed = true
	for path, db := range p.dbs {
		if err := db.Close(); err != nil {
			log().Error("Failed to close BadgerDB", zap.String("path", path), zap.Error(err))
		}
	}
	p.dbs = make(map[string]*badger.DB)
}

func (p *dbPool) closeAndRemove(path string) error {
	p.mu.Lock()
	defer p.mu.Unlock()

	if db, ok := p.dbs[path]; ok {
		if err := db.Close(); err != nil {
			return err
		}
		delete(p.dbs, path)
	}
	return nil
}

func (p *dbPool) closeAndRemoveForce(path string) error {
	p.mu.Lock()
	defer p.mu.Unlock()

	if db, ok := p.dbs[path]; ok {
		done := make(chan struct{})
		go func() {
			defer close(done)
			if err := db.Close(); err != nil {
				log().Error("Failed to close DB in force mode",
					zap.String("path", path),
					zap.Error(err))
			}
		}()

		select {
		case <-done:
		case <-time.After(5 * time.Second):
			log().Warn("DB close timeout, forcing removal",
				zap.String("path", path))
		}

		delete(p.dbs, path)
	}

	lockFile := filepath.Join(path, "LOCK")
	if _, err := os.Stat(lockFile); err == nil {
		if err := os.Remove(lockFile); err != nil {
			log().Warn("Failed to remove LOCK file",
				zap.String("file", lockFile),
				zap.Error(err))
		}
	}

	files, _ := filepath.Glob(filepath.Join(path, "*.mem"))
	for _, f := range files {
		os.Remove(f)
	}

	return nil
}

func (p *dbPool) forceClose(path string) error {
	if db, ok := p.dbs[path]; ok {
		db.Close()
		if runtime.GOOS == "windows" {
			time.Sleep(500 * time.Millisecond)
			runtime.GC()
		}
	}
	return nil
}

func (p *dbPool) close(path string) error {
	p.mu.Lock()
	defer p.mu.Unlock()
	if db, ok := p.dbs[path]; ok {
		if err := db.Close(); err != nil {
			return err
		}
		delete(p.dbs, path)
	}
	return nil
}

func (p *dbPool) get(path string) (*badger.DB, bool) {
	p.mu.Lock()
	db, ok := p.dbs[path]
	p.mu.Unlock()
	return db, ok
}
