// Code generated by splitting main.go. Part of package main.
package novodb

import (
	"sync"
)

type BufferPool struct {
	pool     sync.Pool
	maxSize  int
	allocCnt int64
	freeCnt  int64
}

func NewBufferPool(maxSize int) *BufferPool {
	return &BufferPool{
		maxSize: maxSize,
		pool: sync.Pool{
			New: func() interface{} {
				return make([]byte, 0, maxSize)
			},
		},
	}
}

func (bp *BufferPool) Get() []byte {
	bp.freeCnt++
	return bp.pool.Get().([]byte)[:0]
}

func (bp *BufferPool) Put(b []byte) {
	if cap(b) <= bp.maxSize {
		bp.pool.Put(b[:0])
		bp.allocCnt++
	}
}

func (bp *BufferPool) Stats() map[string]any {
	return map[string]any{
		"allocated": bp.allocCnt,
		"freed":     bp.freeCnt,
		"max_size":  bp.maxSize,
	}
}
