// Code generated by splitting main.go. Part of package main.
package novodb

import (
	"fmt"
	"sync"
	"sync/atomic"
	"time"
)

type CacheItem struct {
	key       string
	value     []byte
	expiresAt time.Time
	prev      *CacheItem
	next      *CacheItem
	hitCount  int64
	lastHit   time.Time
}

type L1Cache struct {
	mu         sync.RWMutex
	items      map[string]*CacheItem
	head       *CacheItem
	tail       *CacheItem
	maxBytes   int64
	curBytes   int64
	hits       atomic.Int64
	misses     atomic.Int64
	evictions  atomic.Int64
	compressed bool
	preloaded  atomic.Bool
	ttl        time.Duration
	stopChan   chan struct{}
}

func newL1Cache(maxMB int64, compressed bool, ttl time.Duration) *L1Cache {
	c := &L1Cache{
		items:      make(map[string]*CacheItem, 16384),
		maxBytes:   maxMB * 1024 * 1024,
		head:       &CacheItem{},
		tail:       &CacheItem{},
		compressed: compressed,
		ttl:        ttl,
		stopChan:   make(chan struct{}),
	}
	c.head.next = c.tail
	c.tail.prev = c.head

	go c.cleanupLoop()
	return c
}

func (c *L1Cache) cleanupLoop() {
	ticker := time.NewTicker(1 * time.Minute)
	defer ticker.Stop()

	for {
		select {
		case <-ticker.C:
			c.cleanupExpired()
		case <-c.stopChan:
			return
		}
	}
}

func (c *L1Cache) cleanupExpired() {
	c.mu.Lock()
	defer c.mu.Unlock()

	now := time.Now()
	var toRemove []string

	for key, item := range c.items {
		if !item.expiresAt.IsZero() && now.After(item.expiresAt) {
			toRemove = append(toRemove, key)
		}
	}

	for _, key := range toRemove {
		if item, ok := c.items[key]; ok {
			c.unlink(item)
			c.curBytes -= int64(len(item.value) + len(item.key))
			delete(c.items, key)
		}
	}
}

func (c *L1Cache) get(key string) ([]byte, bool) {
	c.mu.RLock()
	item, ok := c.items[key]
	c.mu.RUnlock()
	if !ok {
		c.misses.Add(1)
		metricCacheMisses.Inc()
		return nil, false
	}

	if !item.expiresAt.IsZero() && time.Now().After(item.expiresAt) {
		c.mu.Lock()
		c.unlink(item)
		c.curBytes -= int64(len(item.value) + len(item.key))
		delete(c.items, key)
		c.mu.Unlock()
		c.misses.Add(1)
		metricCacheMisses.Inc()
		return nil, false
	}

	c.mu.Lock()
	c.unlink(item)
	c.pushFront(item)
	item.hitCount++
	item.lastHit = time.Now()
	c.mu.Unlock()

	c.hits.Add(1)
	metricCacheHits.Inc()
	return item.value, true
}

func (c *L1Cache) set(key string, value []byte) {
	if c.compressed && len(value) > 1024 {
		if compressed, ok, err := compressData(value, CompressionZstd); err == nil && ok {
			value = compressed
		}
	}

	size := int64(len(key) + len(value) + 64)
	c.mu.Lock()
	defer c.mu.Unlock()

	if item, ok := c.items[key]; ok {
		c.curBytes -= int64(len(item.value))
		item.value = value
		item.expiresAt = time.Now().Add(c.ttl)
		c.curBytes += int64(len(value))
		c.unlink(item)
		c.pushFront(item)
		return
	}

	for c.curBytes+size > c.maxBytes && c.tail.prev != c.head {
		evict := c.tail.prev
		c.unlink(evict)
		c.curBytes -= int64(len(evict.value) + len(evict.key))
		delete(c.items, evict.key)
		c.evictions.Add(1)
	}

	item := &CacheItem{
		key:       key,
		value:     value,
		expiresAt: time.Now().Add(c.ttl),
		lastHit:   time.Now(),
	}
	c.items[key] = item
	c.pushFront(item)
	c.curBytes += size
}

func (c *L1Cache) del(key string) {
	c.mu.Lock()
	if item, ok := c.items[key]; ok {
		c.unlink(item)
		c.curBytes -= int64(len(item.value) + len(item.key))
		delete(c.items, key)
	}
	c.mu.Unlock()
}

func (c *L1Cache) unlink(item *CacheItem) {
	item.prev.next = item.next
	item.next.prev = item.prev
}

func (c *L1Cache) pushFront(item *CacheItem) {
	item.next = c.head.next
	item.prev = c.head
	c.head.next.prev = item
	c.head.next = item
}

func (c *L1Cache) stats() map[string]any {
	c.mu.RLock()
	n := len(c.items)
	cur := c.curBytes
	c.mu.RUnlock()
	h, m := c.hits.Load(), c.misses.Load()
	e := c.evictions.Load()
	ratio := 0.0
	if tot := h + m; tot > 0 {
		ratio = float64(h) / float64(tot) * 100
	}
	return map[string]any{
		"entries":    n,
		"used":       fmtBytes(cur),
		"max":        fmtBytes(c.maxBytes),
		"hits":       h,
		"misses":     m,
		"hit_ratio":  fmt.Sprintf("%.2f%%", ratio),
		"evictions":  e,
		"compressed": c.compressed,
		"preloaded":  c.preloaded.Load(),
		"ttl":        c.ttl.String(),
	}
}

func (c *L1Cache) Close() {
	close(c.stopChan)
}

type IndexResult struct {
	DocIDs    []string
	Page      int
	Total     int64
	HasMore   bool
	NextToken string
	ExpiresAt time.Time
	LastUsed  time.Time
	Frequency int
	Size      int
	Loaded    bool
}

type L2IndexCache struct {
	mu          sync.RWMutex
	cache       map[string]*IndexResult
	max         int
	items       int
	evicted     int64
	hit         int64
	miss        int64
	lazyLoading bool
	ttl         time.Duration
	stopChan    chan struct{}
}

func newL2IndexCache(maxEntries int, lazyLoading bool, ttl time.Duration) *L2IndexCache {
	c := &L2IndexCache{
		cache:       make(map[string]*IndexResult, maxEntries),
		max:         maxEntries,
		lazyLoading: lazyLoading,
		ttl:         ttl,
		stopChan:    make(chan struct{}),
	}
	go c.cleanupLoop()
	return c
}

func (c *L2IndexCache) cleanupLoop() {
	ticker := time.NewTicker(5 * time.Minute)
	defer ticker.Stop()

	for {
		select {
		case <-ticker.C:
			c.cleanupExpired()
		case <-c.stopChan:
			return
		}
	}
}

func (c *L2IndexCache) cleanupExpired() {
	c.mu.Lock()
	defer c.mu.Unlock()

	now := time.Now()
	for key, result := range c.cache {
		if !result.ExpiresAt.IsZero() && now.After(result.ExpiresAt) {
			delete(c.cache, key)
			c.items--
		}
	}
}

func (c *L2IndexCache) get(block, field, value string) (*IndexResult, bool) {
	key := fmt.Sprintf("%s/%s/%s", block, field, value)
	c.mu.RLock()
	res, ok := c.cache[key]
	c.mu.RUnlock()
	if !ok {
		c.miss++
		return nil, false
	}
	if c.lazyLoading && !res.Loaded {
		c.miss++
		return nil, false
	}
	if !res.ExpiresAt.IsZero() && time.Now().After(res.ExpiresAt) {
		c.mu.Lock()
		delete(c.cache, key)
		c.items--
		c.mu.Unlock()
		c.miss++
		return nil, false
	}
	res.LastUsed = time.Now()
	res.Frequency++
	c.hit++
	return res, true
}

func (c *L2IndexCache) set(block, field, value string, docIDs []string, total int64, hasMore bool, nextToken string) {
	key := fmt.Sprintf("%s/%s/%s", block, field, value)
	c.mu.Lock()
	defer c.mu.Unlock()

	if len(c.cache) >= c.max {
		c.evict()
	}

	size := len(docIDs)
	c.cache[key] = &IndexResult{
		DocIDs:    docIDs,
		Total:     total,
		HasMore:   hasMore,
		NextToken: nextToken,
		LastUsed:  time.Now(),
		Frequency: 1,
		Size:      size,
		Loaded:    true,
		ExpiresAt: time.Now().Add(c.ttl),
	}
	c.items++
}

func (c *L2IndexCache) evict() {
	var bestKey string
	var bestScore int = -1

	for k, v := range c.cache {
		if c.lazyLoading && !v.Loaded {
			continue
		}
		score := v.Frequency * 100 / (v.Size + 1)
		if v.Size > 1000 {
			score -= 50
		}
		if bestKey == "" || score < bestScore ||
			(score == bestScore && v.LastUsed.Before(c.cache[bestKey].LastUsed)) {
			bestKey = k
			bestScore = score
		}
	}
	if bestKey != "" {
		delete(c.cache, bestKey)
		c.items--
		c.evicted++
	}
}

func (c *L2IndexCache) stats() map[string]any {
	c.mu.RLock()
	defer c.mu.RUnlock()
	loaded := 0
	for _, v := range c.cache {
		if v.Loaded {
			loaded++
		}
	}
	return map[string]any{
		"entries":      c.items,
		"max":          c.max,
		"hit":          c.hit,
		"miss":         c.miss,
		"evicted":      c.evicted,
		"hit_rate":     fmt.Sprintf("%.2f%%", float64(c.hit)/float64(c.hit+c.miss+1)*100),
		"loaded":       loaded,
		"lazy_loading": c.lazyLoading,
	}
}

func (c *L2IndexCache) Close() {
	close(c.stopChan)
}
