// Code generated by splitting main.go. Part of package main.
package novodb

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	badger "github.com/dgraph-io/badger/v4"
	"github.com/hashicorp/raft"
	raftboltdb "github.com/hashicorp/raft-boltdb"
	"go.uber.org/zap"
	"io"
	"net"
	"net/http"
	"os"
	"path/filepath"
	"runtime/debug"
	"strconv"
	"strings"
	"sync"
	"time"
)

type ClusterManager struct {
	raft         *raft.Raft
	fsm          *RaftFSM
	engine       *Engine
	nodeID       string
	raftDir      string
	bindAddr     string
	advertise    string
	mu           sync.RWMutex
	peers        map[string]string
	started      bool
	stopChan     chan struct{}
	stopOnce     sync.Once
	gossipTicker *time.Ticker
	discoverer   *NodeDiscoverer
	autoJoin     bool
	config       *Config
	ctx          context.Context
	cancel       context.CancelFunc
}

type NodeDiscoverer struct {
	mu            sync.RWMutex
	knownNodes    map[string]string
	discoverPort  int
	discoveryChan chan NodeDiscovery
	mux           *http.ServeMux
	server        *http.Server
	stopChan      chan struct{}
}

type NodeDiscovery struct {
	NodeID  string `json:"node_id"`
	Address string `json:"address"`
	Action  string `json:"action"`
}

func NewNodeDiscoverer(port int) *NodeDiscoverer {
	nd := &NodeDiscoverer{
		knownNodes:    make(map[string]string),
		discoverPort:  port,
		discoveryChan: make(chan NodeDiscovery, 10000),
		mux:           http.NewServeMux(),
		stopChan:      make(chan struct{}),
	}
	nd.mux.HandleFunc("/discover", nd.handleDiscovery)
	nd.mux.HandleFunc("/discover/health", nd.handleHealth)
	return nd
}

func (nd *NodeDiscoverer) StartDiscovery() {
	addr := fmt.Sprintf(":%d", nd.discoverPort)
	nd.server = &http.Server{
		Addr:         addr,
		Handler:      nd.mux,
		ReadTimeout:  10 * time.Second,
		WriteTimeout: 10 * time.Second,
	}

	go func() {
		log().Info("Discovery service started", zap.Int("port", nd.discoverPort))
		if err := nd.server.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			log().Error("Discovery server failed", zap.Error(err))
		}
	}()
	go nd.broadcastHeartbeat()
}

func (nd *NodeDiscoverer) Stop() {
	close(nd.stopChan)
	if nd.server != nil {
		ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
		defer cancel()
		nd.server.Shutdown(ctx)
	}
}

func (nd *NodeDiscoverer) handleDiscovery(w http.ResponseWriter, r *http.Request) {
	var discovery NodeDiscovery
	if err := json.NewDecoder(r.Body).Decode(&discovery); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	nd.mu.Lock()
	nd.knownNodes[discovery.NodeID] = discovery.Address
	nd.mu.Unlock()

	nd.discoveryChan <- discovery
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(map[string]string{"status": "ok"})
}

func (nd *NodeDiscoverer) handleHealth(w http.ResponseWriter, r *http.Request) {
	nd.mu.RLock()
	nodes := len(nd.knownNodes)
	nd.mu.RUnlock()
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(map[string]any{
		"status": "ok",
		"nodes":  nodes,
	})
}

func (nd *NodeDiscoverer) broadcastHeartbeat() {
	ticker := time.NewTicker(5 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ticker.C:
			nd.mu.RLock()
			nodes := make(map[string]string)
			for id, addr := range nd.knownNodes {
				nodes[id] = addr
			}
			nd.mu.RUnlock()

			for nodeID, addr := range nodes {
				go func(id, address string) {
					client := &http.Client{Timeout: 2 * time.Second}
					data, _ := json.Marshal(NodeDiscovery{
						NodeID:  id,
						Address: address,
						Action:  "heartbeat",
					})
					client.Post(fmt.Sprintf("http://%s/discover", address), "application/json", bytes.NewReader(data))
				}(nodeID, addr)
			}
		case <-nd.stopChan:
			return
		}
	}
}

func getLocalIP() (string, error) {
	addrs, err := net.InterfaceAddrs()
	if err != nil {
		return "", err
	}

	var preferredPrivate []string
	var otherPrivate []string
	var publicIPs []string
	var globalIPv6 []string

	for _, addr := range addrs {
		ipnet, ok := addr.(*net.IPNet)
		if !ok {
			continue
		}

		if ipnet.IP.IsLoopback() {
			continue
		}
		if ipnet.IP.IsLinkLocalUnicast() {
			continue
		}
		if ipnet.IP.IsMulticast() {
			continue
		}

		if ipv4 := ipnet.IP.To4(); ipv4 != nil {
			ipStr := ipv4.String()
			if ipv4.IsPrivate() {
				if strings.HasPrefix(ipStr, "192.168.") {
					preferredPrivate = append(preferredPrivate, ipStr)
				} else {
					otherPrivate = append(otherPrivate, ipStr)
				}
			} else {
				publicIPs = append(publicIPs, ipStr)
			}
		} else {
			if ipnet.IP.To16() != nil {
				if ipnet.IP.IsGlobalUnicast() && !ipnet.IP.IsPrivate() {
					globalIPv6 = append(globalIPv6, ipnet.IP.String())
				}
			}
		}
	}

	if len(preferredPrivate) > 0 {
		for _, ip := range preferredPrivate {
			if !isBridgeOrDocker(ip) {
				return ip, nil
			}
		}
		ip := preferredPrivate[0]
		return ip, nil
	}

	if len(otherPrivate) > 0 {
		for _, ip := range otherPrivate {
			if !isBridgeOrDocker(ip) {
				return ip, nil
			}
		}
		ip := otherPrivate[0]
		return ip, nil
	}

	if len(publicIPs) > 0 {
		ip := publicIPs[0]
		return ip, nil
	}

	if len(globalIPv6) > 0 {
		ip := globalIPv6[0]
		return ip, nil
	}

	return "127.0.0.1", nil
}

func isBridgeOrDocker(ip string) bool {
	if strings.HasPrefix(ip, "172.17.") ||
		strings.HasPrefix(ip, "172.18.") ||
		strings.HasPrefix(ip, "172.19.") ||
		strings.HasPrefix(ip, "172.20.") ||
		strings.HasPrefix(ip, "172.21.") ||
		strings.HasPrefix(ip, "172.22.") ||
		strings.HasPrefix(ip, "172.23.") ||
		strings.HasPrefix(ip, "172.24.") ||
		strings.HasPrefix(ip, "172.25.") ||
		strings.HasPrefix(ip, "172.26.") ||
		strings.HasPrefix(ip, "172.27.") ||
		strings.HasPrefix(ip, "172.28.") ||
		strings.HasPrefix(ip, "172.29.") ||
		strings.HasPrefix(ip, "172.30.") ||
		strings.HasPrefix(ip, "172.31.") {
		parts := strings.Split(ip, ".")
		if len(parts) == 4 {
			lastOctet, err := strconv.Atoi(parts[3])
			if err == nil && (lastOctet == 0 || lastOctet == 1) {
				return true
			}
		}
	}

	if strings.HasPrefix(ip, "10.88.") {
		parts := strings.Split(ip, ".")
		if len(parts) == 4 {
			lastOctet, err := strconv.Atoi(parts[3])
			if err == nil && (lastOctet == 0 || lastOctet == 1) {
				return true
			}
		}
	}

	return false
}

func (cm *ClusterManager) initRaftWithCustomLogStore() error {
	raftConfig := raft.DefaultConfig()
	raftConfig.LocalID = raft.ServerID(cm.nodeID)
	raftConfig.HeartbeatTimeout = heartbeatInterval
	raftConfig.ElectionTimeout = electionTimeout
	raftConfig.LeaderLeaseTimeout = leaderLeaseTimeout
	raftConfig.SnapshotInterval = 30 * time.Second
	raftConfig.SnapshotThreshold = 2000
	raftConfig.MaxAppendEntries = 256
	raftConfig.TrailingLogs = 100000
	raftConfig.LogOutput = io.Discard

	advertiseAddr, err := net.ResolveTCPAddr("tcp", cm.advertise)
	if err != nil {
		return fmt.Errorf("resolve advertise address: %w", err)
	}

	log().Info("Initializing Raft with custom log store",
		zap.String("bind", cm.bindAddr),
		zap.String("advertise", cm.advertise),
	)

	transport, err := raft.NewTCPTransport(
		cm.bindAddr,
		advertiseAddr,
		raftMaxPool,
		raftTimeout,
		io.Discard,
	)
	if err != nil {
		return fmt.Errorf("create transport: %w", err)
	}

	logStore, err := NewBadgerLogStore(filepath.Join(cm.raftDir, "raft-log-badger"))
	if err != nil {
		return fmt.Errorf("create badger log store: %w", err)
	}

	stableStore, err := raftboltdb.NewBoltStore(filepath.Join(cm.raftDir, "raft-stable.db"))
	if err != nil {
		return fmt.Errorf("create stable store: %w", err)
	}

	snapshotStore, err := raft.NewFileSnapshotStore(cm.raftDir, raftSnapshotRetain, io.Discard)
	if err != nil {
		return fmt.Errorf("create snapshot store: %w", err)
	}

	cm.fsm = NewRaftFSM(cm.engine)

	raftInstance, err := raft.NewRaft(
		raftConfig,
		cm.fsm,
		logStore,
		stableStore,
		snapshotStore,
		transport,
	)
	if err != nil {
		return fmt.Errorf("create raft: %w", err)
	}

	cm.raft = raftInstance

	hasExisting, err := raft.HasExistingState(logStore, stableStore, snapshotStore)
	if err != nil {
		log().Warn("Failed to check existing raft state, assuming no state",
			zap.Error(err))
		hasExisting = false
	}

	if !hasExisting {
		log().Info("No existing cluster state found, bootstrapping...",
			zap.String("node_id", cm.nodeID))

		configuration := raft.Configuration{
			Servers: []raft.Server{
				{
					ID:      raft.ServerID(cm.nodeID),
					Address: raft.ServerAddress(cm.advertise),
				},
			},
		}

		future := cm.raft.BootstrapCluster(configuration)
		if err := future.Error(); err != nil {
			if err == raft.ErrCantBootstrap {
				log().Info("Cluster already bootstrapped (race condition)",
					zap.String("node_id", cm.nodeID))
				return nil
			}
			return fmt.Errorf("bootstrap cluster: %w", err)
		}

		log().Info("Cluster bootstrapped successfully",
			zap.String("node_id", cm.nodeID),
			zap.String("advertise", cm.advertise))
	} else {
		log().Info("Existing cluster state detected",
			zap.String("node_id", cm.nodeID))
	}

	return nil
}

func NewClusterManager(engine *Engine, config *Config) (*ClusterManager, error) {
	if engine == nil {
		return nil, fmt.Errorf("engine is nil")
	}

	nodeID := engine.nodeID

	raftPort := config.RaftPort
	raftBind := config.RaftBind

	bindAddr := fmt.Sprintf("%s:%d", raftBind, raftPort)
	advertise := bindAddr

	if raftBind == "0.0.0.0" || raftBind == "" {
		localIP, err := getLocalIP()
		if err != nil {
			return nil, fmt.Errorf("failed to get local IP: %w", err)
		}
		advertise = fmt.Sprintf("%s:%d", localIP, raftPort)
		bindAddr = fmt.Sprintf("0.0.0.0:%d", raftPort)
		log().Info("Auto-detected IP for advertise",
			zap.String("ip", localIP),
			zap.Int("port", raftPort))
	}

	raftDir := filepath.Join(engine.dataRoot, raftDBName)
	if err := os.MkdirAll(raftDir, 0750); err != nil {
		return nil, fmt.Errorf("create raft directory: %w", err)
	}

	ctx, cancel := context.WithCancel(context.Background())

	cm := &ClusterManager{
		engine:    engine,
		nodeID:    nodeID,
		raftDir:   raftDir,
		bindAddr:  bindAddr,
		advertise: advertise,
		peers:     make(map[string]string),
		stopChan:  make(chan struct{}),
		autoJoin:  true,
		config:    config,
		ctx:       ctx,
		cancel:    cancel,
	}

	cm.discoverer = NewNodeDiscoverer(raftPort + 1000)

	if err := cm.initRaftWithCustomLogStore(); err != nil {
		return nil, fmt.Errorf("initialize raft: %w", err)
	}

	cm.discoverer.StartDiscovery()
	go cm.autoDiscoveryLoop()
	go cm.autoJoinLoop()
	go cm.healthCheckLoop()

	log().Info("Cluster manager initialized (auto-mode)",
		zap.String("node_id", nodeID),
		zap.String("bind_addr", bindAddr),
		zap.String("advertise", advertise),
		zap.Int("max_nodes", config.MaxClusterNodes))

	return cm, nil
}

func (cm *ClusterManager) healthCheckLoop() {
	ticker := time.NewTicker(10 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ticker.C:
			cm.checkNodeHealth()
		case <-cm.stopChan:
			return
		}
	}
}

func (cm *ClusterManager) checkNodeHealth() {
	cm.mu.RLock()
	peers := make(map[string]string)
	for id, addr := range cm.peers {
		peers[id] = addr
	}
	cm.mu.RUnlock()

	for nodeID, addr := range peers {
		go func(id, address string) {
			client := &http.Client{Timeout: 2 * time.Second}
			resp, err := client.Get(fmt.Sprintf("http://%s/health", address))
			if err != nil || resp.StatusCode != 200 {
				log().Warn("Node health check failed",
					zap.String("node", id),
					zap.Error(err))
				cm.engine.shardMgr.HandleNodeFailure(id)
			}
			if resp != nil {
				resp.Body.Close()
			}
		}(nodeID, addr)
	}
}

func (cm *ClusterManager) autoDiscoveryLoop() {
	ticker := time.NewTicker(10 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ticker.C:
			cm.discoverNodes()
		case <-cm.stopChan:
			return
		}
	}
}

func (cm *ClusterManager) autoJoinLoop() {
	ticker := time.NewTicker(5 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ticker.C:
			if cm.raft.State() == raft.Leader {
				cm.handleAutoJoin()
			}
		case <-cm.stopChan:
			return
		}
	}
}

func (cm *ClusterManager) discoverNodes() {
	cm.mu.RLock()
	knownNodes := make(map[string]string)
	for id, addr := range cm.peers {
		knownNodes[id] = addr
	}
	cm.mu.RUnlock()

	for nodeID, addr := range knownNodes {
		if nodeID == cm.nodeID {
			continue
		}
		go cm.sendDiscovery(nodeID, addr)
	}
}

func (cm *ClusterManager) sendDiscovery(nodeID, addr string) {
	client := &http.Client{Timeout: 2 * time.Second}
	data, _ := json.Marshal(NodeDiscovery{
		NodeID:  cm.nodeID,
		Address: cm.advertise,
		Action:  "heartbeat",
	})
	client.Post(fmt.Sprintf("http://%s/discover", addr), "application/json", bytes.NewReader(data))
}

func (cm *ClusterManager) handleAutoJoin() {
	cm.mu.RLock()
	knownNodes := make(map[string]string)
	for id, addr := range cm.peers {
		knownNodes[id] = addr
	}
	cm.mu.RUnlock()

	for nodeID, addr := range knownNodes {
		if nodeID == cm.nodeID {
			continue
		}
		future := cm.raft.GetConfiguration()
		if err := future.Error(); err != nil {
			continue
		}
		config := future.Configuration()
		found := false
		for _, server := range config.Servers {
			if string(server.ID) == nodeID {
				found = true
				break
			}
		}
		if !found {
			log().Info("Auto-joining discovered node",
				zap.String("node", nodeID),
				zap.String("addr", addr))
			future := cm.raft.AddVoter(
				raft.ServerID(nodeID),
				raft.ServerAddress(addr),
				0, raftTimeout)
			if err := future.Error(); err != nil {
				log().Warn("Failed to auto-join node", zap.String("node", nodeID), zap.Error(err))
			} else {
				cm.engine.shardMgr.AddNodeToShards(nodeID)
				log().Info("Node auto-joined successfully", zap.String("node", nodeID))
			}
		}
	}
}

func (cm *ClusterManager) HandleJoin(w http.ResponseWriter, r *http.Request) {
	var req struct {
		NodeID  string `json:"node_id"`
		Address string `json:"address"`
	}
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if req.NodeID == "" || req.Address == "" {
		http.Error(w, "node_id and address are required", http.StatusBadRequest)
		return
	}

	if cm.raft.State() != raft.Leader {
		leader := string(cm.raft.Leader())
		if leader != "" {
			w.Header().Set("Location", leader)
			http.Error(w, fmt.Sprintf(`{"error":"not leader","leader":%q}`, leader), http.StatusTemporaryRedirect)
		} else {
			http.Error(w, `{"error":"no leader elected yet"}`, http.StatusServiceUnavailable)
		}
		return
	}

	future := cm.raft.AddVoter(
		raft.ServerID(req.NodeID),
		raft.ServerAddress(req.Address),
		0,
		raftTimeout,
	)
	if err := future.Error(); err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	cm.mu.Lock()
	cm.peers[req.NodeID] = req.Address
	cm.mu.Unlock()

	cm.engine.shardMgr.AddNodeToShards(req.NodeID)

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	json.NewEncoder(w).Encode(map[string]string{"status": "joined"})
}

func (cm *ClusterManager) HandleLeave(w http.ResponseWriter, r *http.Request) {
	var req struct {
		NodeID string `json:"node_id"`
	}
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	if cm.raft.State() != raft.Leader {
		leader := string(cm.raft.Leader())
		http.Error(w, fmt.Sprintf(`{"error":"not leader","leader":%q}`, leader), http.StatusServiceUnavailable)
		return
	}

	future := cm.raft.RemoveServer(raft.ServerID(req.NodeID), 0, raftTimeout)
	if err := future.Error(); err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	cm.mu.Lock()
	delete(cm.peers, req.NodeID)
	cm.mu.Unlock()

	cm.engine.shardMgr.RemoveNodeFromShards(req.NodeID)

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	json.NewEncoder(w).Encode(map[string]string{"status": "left"})
}

func (cm *ClusterManager) HandleStatus(w http.ResponseWriter, r *http.Request) {
	stats := cm.raft.Stats()
	state := cm.raft.State().String()

	cm.mu.RLock()
	peers := make([]string, 0, len(cm.peers))
	for id := range cm.peers {
		peers = append(peers, id)
	}
	cm.mu.RUnlock()

	status := map[string]any{
		"node_id":      cm.nodeID,
		"state":        state,
		"is_leader":    cm.raft.State() == raft.Leader,
		"peers":        peers,
		"stats":        stats,
		"started":      cm.started,
		"bind":         cm.bindAddr,
		"advertise":    cm.advertise,
		"leader":       string(cm.raft.Leader()),
		"auto_join":    cm.autoJoin,
		"max_nodes":    cm.config.MaxClusterNodes,
		"total_peers":  len(peers),
		"total_shards": cm.engine.shardMgr.shardCount,
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(status)
}

func (cm *ClusterManager) Start() {
	cm.mu.Lock()
	defer cm.mu.Unlock()
	cm.started = true
	log().Info("Cluster manager started (auto-mode)", zap.String("node_id", cm.nodeID))
}

func (cm *ClusterManager) Stop() {
	cm.mu.Lock()
	defer cm.mu.Unlock()

	if !cm.started {
		return
	}

	cm.stopOnce.Do(func() {
		close(cm.stopChan)
	})
	if cm.raft != nil {
		future := cm.raft.Shutdown()
		if err := future.Error(); err != nil {
			log().Warn("Raft shutdown error", zap.Error(err))
		}
	}
	if cm.discoverer != nil {
		cm.discoverer.Stop()
	}
	cm.cancel()
	cm.started = false
	log().Info("Cluster manager stopped", zap.String("node_id", cm.nodeID))
}

func (cm *ClusterManager) IsLeader() bool {
	return cm.raft != nil && cm.raft.State() == raft.Leader
}

func (cm *ClusterManager) GetLeader() string {
	if cm.raft == nil {
		return ""
	}
	return string(cm.raft.Leader())
}

func (cm *ClusterManager) GetPeers() []string {
	cm.mu.RLock()
	defer cm.mu.RUnlock()
	peers := make([]string, 0, len(cm.peers))
	for id := range cm.peers {
		peers = append(peers, id)
	}
	return peers
}

func (cm *ClusterManager) WaitForLeader(timeout time.Duration) error {
	deadline := time.Now().Add(timeout)
	ticker := time.NewTicker(200 * time.Millisecond)
	defer ticker.Stop()

	for {
		select {
		case <-ticker.C:
			if cm.raft != nil && cm.raft.Leader() != "" {
				log().Info("Leader elected",
					zap.String("leader", string(cm.raft.Leader())))
				return nil
			}
			if time.Now().After(deadline) {
				return fmt.Errorf("timeout waiting for leader after %s", timeout)
			}
		case <-cm.stopChan:
			return fmt.Errorf("cluster stopped while waiting for leader")
		case <-cm.ctx.Done():
			return cm.ctx.Err()
		}
	}
}

type TransactionHelper struct{}

var txHelper = &TransactionHelper{}

func (th *TransactionHelper) SafeUpdate(db *badger.DB, fn func(*badger.Txn) error) (err error) {
	var txn *badger.Txn

	defer func() {
		if r := recover(); r != nil {
			if txn != nil {
				txn.Discard()
			}
			log().Error("Panic in transaction",
				zap.Any("recover", r),
				zap.String("stack", string(debug.Stack())))
			err = fmt.Errorf("panic in transaction: %v", r)
		}
	}()

	txn = db.NewTransaction(true)
	if txn == nil {
		return fmt.Errorf("failed to create transaction")
	}

	defer txn.Discard()

	err = fn(txn)
	if err != nil {
		return err
	}

	err = txn.Commit()
	if err != nil {
		return err
	}

	return nil
}

func (th *TransactionHelper) SafeView(db *badger.DB, fn func(*badger.Txn) error) (err error) {
	var txn *badger.Txn

	defer func() {
		if r := recover(); r != nil {
			if txn != nil {
				txn.Discard()
			}
			log().Error("Panic in read transaction",
				zap.Any("recover", r),
				zap.String("stack", string(debug.Stack())))
			err = fmt.Errorf("panic in read transaction: %v", r)
		}
	}()

	txn = db.NewTransaction(false)
	if txn == nil {
		return fmt.Errorf("failed to create read transaction")
	}

	defer txn.Discard()

	err = fn(txn)
	return err
}
