// Code generated by splitting main.go. Part of package main.
package novodb

import (
	"fmt"
	"strconv"
	"strings"
)

func handleFind(eng *Engine, sess *Session, tokens []string) string {
	if len(tokens) < 2 {
		return "ERROR: FIND requires block name"
	}
	block := tokens[1]
	db := sess.currentDB
	if db == "" {
		return "ERROR: No database in use"
	}

	if !eng.dirMgr.BlockExists(db, block) {
		return "ERROR: Block not found: " + block
	}

	if len(tokens) >= 3 {
		nextToken := tokens[2]
		upperNext := strings.ToUpper(nextToken)
		if upperNext != "WHERE" && upperNext != "LIMIT" && upperNext != "ORDER" &&
			upperNext != "SELECT" && upperNext != "EXCLUDE" && upperNext != "OFFSET" &&
			upperNext != "ONLY" {
			doc, ok := eng.FindByID(db, block, nextToken)
			if !ok {
				return "Document not found: " + nextToken
			}
			return jsonOut(doc)
		}
	}

	q := &Query{
		Filters:  []Filter{},
		Limit:    100,
		Offset:   0,
		UseIndex: true,
	}

	outputAsTable := false
	i := 2
	for i < len(tokens) {
		token := tokens[i]

		if token == "--type:table" || token == "--format:table" {
			outputAsTable = true
			i++
			continue
		}

		switch strings.ToUpper(token) {
		case "WHERE":
			i++
			if i >= len(tokens) {
				return "ERROR: WHERE requires filter conditions"
			}
			filters, err := parseFilters(tokens, &i)
			if err != nil {
				return "ERROR: " + err.Error()
			}
			q.Filters = filters
		case "LIMIT":
			if i+1 < len(tokens) {
				limit, err := strconv.Atoi(tokens[i+1])
				if err == nil && limit > 0 {
					q.Limit = limit
				}
				i += 2
			} else {
				return "ERROR: LIMIT requires value"
			}
		case "OFFSET":
			if i+1 < len(tokens) {
				offset, err := strconv.Atoi(tokens[i+1])
				if err == nil && offset >= 0 {
					q.Offset = offset
				}
				i += 2
			} else {
				return "ERROR: OFFSET requires value"
			}
		case "SELECT", "ONLY":
			if i+1 < len(tokens) {
				q.Select = strings.Split(tokens[i+1], ",")
				for j := range q.Select {
					q.Select[j] = strings.TrimSpace(q.Select[j])
				}
				i += 2
			} else {
				return "ERROR: SELECT requires fields"
			}
		case "EXCLUDE":
			if i+1 < len(tokens) {
				q.Exclude = strings.Split(tokens[i+1], ",")
				for j := range q.Exclude {
					q.Exclude[j] = strings.TrimSpace(q.Exclude[j])
				}
				i += 2
			} else {
				return "ERROR: EXCLUDE requires fields"
			}
		case "ORDER":
			if i+1 < len(tokens) {
				fields := strings.Split(tokens[i+1], ",")
				for _, f := range fields {
					f = strings.TrimSpace(f)
					desc := false
					if strings.HasSuffix(f, ":DESC") {
						f = strings.TrimSuffix(f, ":DESC")
						desc = true
					}
					q.Sort = append(q.Sort, SortField{Field: f, Desc: desc})
				}
				i += 2
			} else {
				return "ERROR: ORDER requires fields"
			}
		default:
			if i+2 < len(tokens) {
				operator := strings.ToUpper(tokens[i+1])
				if operator == "=" || operator == "==" || operator == "!=" ||
					operator == ">" || operator == "<" || operator == ">=" || operator == "<=" ||
					operator == "LIKE" || operator == "CONTAINS" {
					fieldName := token
					fieldValue := tokens[i+2]
					var fieldFilter Filter
					fieldFilter.Field = fieldName
					fieldFilter.Op = operator
					if num, err := strconv.ParseFloat(fieldValue, 64); err == nil {
						fieldFilter.Value = num
					} else {
						fieldValue = strings.Trim(fieldValue, "\"'")
						fieldFilter.Value = fieldValue
					}
					q.Filters = append(q.Filters, fieldFilter)
					i += 3
					continue
				}
			}
			i++
		}
	}

	result, err := eng.Find(db, block, q)
	if err != nil {
		return "ERROR: " + err.Error()
	}

	if outputAsTable {
		return formatResultAsTable(result, q.Select)
	}

	var sb strings.Builder
	if result.Total == 0 {
		sb.WriteString("No documents found")
	} else {
		sb.WriteString(fmt.Sprintf("Found %d documents (scanned: %d, index: %s, took: %v)\n",
			result.Total, result.Scanned, result.IndexUsed, result.Took))
		for _, doc := range result.Docs {
			sb.WriteString(fmt.Sprintf("  _id: %s, shard: %s, data: %s\n",
				doc.ID, doc.ShardID, jsonOut(doc.Data)))
		}
	}
	return sb.String()
}

func formatResultAsTable(result *QueryResult, selectFields []string) string {
	if len(result.Docs) == 0 {
		return "No documents found"
	}

	var sb strings.Builder

	var fields []string
	if len(selectFields) > 0 {
		fields = selectFields
	} else {
		doc := result.Docs[0]
		fields = make([]string, 0, len(doc.Data)+2)
		fields = append(fields, "_id", "_shard_id")
		for k := range doc.Data {
			fields = append(fields, k)
		}
	}

	colWidths := make(map[string]int)
	for _, f := range fields {
		colWidths[f] = len(f)
	}

	for _, doc := range result.Docs {
		for _, f := range fields {
			var val string
			switch f {
			case "_id":
				val = doc.ID
			case "_shard_id":
				val = doc.ShardID
			default:
				if v, ok := doc.Data[f]; ok {
					val = fmt.Sprint(v)
				} else {
					val = ""
				}
			}
			if len(val) > colWidths[f] {
				colWidths[f] = len(val)
			}
		}
	}

	maxWidth := 120
	totalWidth := 0
	for _, f := range fields {
		totalWidth += colWidths[f] + 3
	}
	if totalWidth > maxWidth {
		for _, f := range fields {
			if colWidths[f] > 30 {
				colWidths[f] = 30
			}
		}
		totalWidth = 0
		for _, f := range fields {
			totalWidth += colWidths[f] + 3
		}
	}

	sb.WriteString("+" + strings.Repeat("-", totalWidth-1) + "+\n")

	sb.WriteString("|")
	for _, f := range fields {
		width := colWidths[f]
		if width < len(f) {
			width = len(f)
		}
		sb.WriteString(fmt.Sprintf(" %-*s |", width, f))
	}
	sb.WriteString("\n")

	sb.WriteString("+" + strings.Repeat("-", totalWidth-1) + "+\n")

	for _, doc := range result.Docs {
		sb.WriteString("|")
		for _, f := range fields {
			var val string
			switch f {
			case "_id":
				val = doc.ID
			case "_shard_id":
				val = doc.ShardID
			default:
				if v, ok := doc.Data[f]; ok {
					val = fmt.Sprint(v)
					if len(val) > 100 {
						val = val[:97] + "..."
					}
				} else {
					val = ""
				}
			}
			width := colWidths[f]
			if width < len(f) {
				width = len(f)
			}
			sb.WriteString(fmt.Sprintf(" %-*s |", width, val))
		}
		sb.WriteString("\n")
	}

	sb.WriteString("+" + strings.Repeat("-", totalWidth-1) + "+\n")

	sb.WriteString(fmt.Sprintf("Total: %d documents (scanned: %d, index: %s, took: %v)\n",
		result.Total, result.Scanned, result.IndexUsed, result.Took))

	return sb.String()
}

func handleGet(eng *Engine, sess *Session, tokens []string) string {
	if len(tokens) < 3 {
		return "ERROR: GET requires block name and ID"
	}
	block := tokens[1]
	id := tokens[2]
	db := sess.currentDB
	if db == "" {
		return "ERROR: No database in use"
	}
	doc, ok := eng.FindByID(db, block, id)
	if !ok {
		return "Document not found: " + id
	}
	return jsonOut(doc)
}

func handleSearch(eng *Engine, sess *Session, tokens []string) string {
	if len(tokens) < 3 {
		return "ERROR: SEARCH requires block name and search text"
	}
	block := tokens[1]
	text := tokens[2]
	db := sess.currentDB
	if db == "" {
		return "ERROR: No database in use"
	}

	dbs, err := eng.ShowDBs()
	if err != nil {
		return "ERROR: " + err.Error()
	}
	dbExists := false
	for _, d := range dbs {
		if d == db {
			dbExists = true
			break
		}
	}
	if !dbExists {
		return "ERROR: Database not found: " + db
	}

	blocks, err := eng.ShowBlocks(db)
	if err != nil {
		return "ERROR: " + err.Error()
	}
	blockExists := false
	for _, b := range blocks {
		if b == block {
			blockExists = true
			break
		}
	}
	if !blockExists {
		return "ERROR: Block not found: " + block
	}

	q := &Query{
		Filters:    []Filter{},
		Limit:      100,
		Offset:     0,
		UseIndex:   false,
		PreferScan: true,
	}

	showScore := false
	showMatches := false
	searchMode := "default"

	i := 3
	for i < len(tokens) {
		switch strings.ToUpper(tokens[i]) {
		case "LIMIT":
			if i+1 < len(tokens) {
				limit, err := strconv.Atoi(tokens[i+1])
				if err == nil && limit > 0 {
					q.Limit = limit
				}
				i += 2
			} else {
				return "ERROR: LIMIT requires value"
			}
		case "OFFSET":
			if i+1 < len(tokens) {
				offset, err := strconv.Atoi(tokens[i+1])
				if err == nil && offset >= 0 {
					q.Offset = offset
				}
				i += 2
			} else {
				return "ERROR: OFFSET requires value"
			}
		case "WHERE":
			i++
			if i >= len(tokens) {
				return "ERROR: WHERE requires filter conditions"
			}
			filters, err := parseFilters(tokens, &i)
			if err != nil {
				return "ERROR: " + err.Error()
			}
			q.Filters = append(q.Filters, filters...)
		case "ORDER":
			if i+1 < len(tokens) {
				fields := strings.Split(tokens[i+1], ",")
				for _, f := range fields {
					f = strings.TrimSpace(f)
					desc := false
					if strings.HasSuffix(f, ":DESC") {
						f = strings.TrimSuffix(f, ":DESC")
						desc = true
					}
					q.Sort = append(q.Sort, SortField{Field: f, Desc: desc})
				}
				i += 2
			} else {
				return "ERROR: ORDER requires fields"
			}
		case "ONLY", "SELECT":
			if i+1 < len(tokens) {
				q.Select = strings.Split(tokens[i+1], ",")
				for j := range q.Select {
					q.Select[j] = strings.TrimSpace(q.Select[j])
				}
				i += 2
			} else {
				return "ERROR: SELECT requires fields"
			}
		case "WITH", "SHOW":
			if i+1 < len(tokens) {
				opt := strings.ToUpper(tokens[i+1])
				if opt == "SCORE" || opt == "RELEVANCE" {
					showScore = true
					i += 2
				} else if opt == "MATCHES" {
					showMatches = true
					i += 2
				} else {
					i++
				}
			} else {
				i++
			}
		case "EXACT", "PHRASE":
			searchMode = "exact"
			i++
		case "FUZZY", "SIMILAR":
			searchMode = "fuzzy"
			i++
		default:
			i++
		}
	}

	if searchMode == "exact" && !strings.HasPrefix(text, `"`) {
		text = `"` + text + `"`
	}

	if searchMode == "fuzzy" && !strings.HasPrefix(text, "~") {
		text = "~" + text
	}

	result, err := eng.Search(db, block, text, q)
	if err != nil {
		return "ERROR: " + err.Error()
	}

	var sb strings.Builder
	if result.Total == 0 {
		sb.WriteString("No documents found matching search")
	} else {
		sb.WriteString(fmt.Sprintf("[SEARCH] Found %d documents matching '%s' (scanned: %d, took: %v)\n",
			result.Total, text, result.Scanned, result.Took))

		for idx, doc := range result.Docs {
			if showScore {
				searchText := strings.ToLower(strings.TrimSpace(text))
				words := strings.Fields(searchText)
				score, matches := calculateRelevance(doc, searchText, words)
				sb.WriteString(fmt.Sprintf("  %d. Score: %.2f | _id: %s, shard: %s, data: %s\n",
					idx+1, score, doc.ID, doc.ShardID, jsonOut(doc.Data)))
				if showMatches && len(matches) > 0 {
					sb.WriteString(fmt.Sprintf("     Matches: %s\n", strings.Join(matches, ", ")))
				}
			} else {
				sb.WriteString(fmt.Sprintf("  %d. _id: %s, shard: %s, data: %s\n",
					idx+1, doc.ID, doc.ShardID, jsonOut(doc.Data)))
			}
		}
	}
	return sb.String()
}
