// Code generated by splitting main.go. Part of package main.
package novodb

import (
	"fmt"
	"strings"
)

func handleAggregate(eng *Engine, sess *Session, aggOp string, tokens []string) string {
	if len(tokens) < 3 {
		return fmt.Sprintf("ERROR: %s requires block and field", aggOp)
	}
	block := tokens[1]
	field := tokens[2]
	db := sess.currentDB
	if db == "" {
		return "ERROR: No database in use"
	}

	if !eng.dirMgr.BlockExists(db, block) {
		return "ERROR: Block not found: " + block
	}

	var filters []Filter
	i := 3
	for i < len(tokens) {
		if strings.ToUpper(tokens[i]) == "WHERE" {
			i++
			var err error
			filters, err = parseFilters(tokens, &i)
			if err != nil {
				return "ERROR: " + err.Error()
			}
		} else {
			i++
		}
	}

	result, err := eng.Aggregate(db, block, aggOp, field, filters)
	if err != nil {
		return "ERROR: " + err.Error()
	}
	return fmt.Sprintf("%s of %s: %v", aggOp, field, result)
}

func handleGroup(eng *Engine, sess *Session, tokens []string) string {
	if len(tokens) < 4 {
		return "ERROR: GROUP requires block, BY, and field"
	}
	block := tokens[1]
	db := sess.currentDB
	if db == "" {
		return "ERROR: No database in use"
	}

	if !eng.dirMgr.BlockExists(db, block) {
		return "ERROR: Block not found: " + block
	}

	var byField string
	var aggOp string
	var aggField string
	var filters []Filter

	i := 2
	for i < len(tokens) {
		switch strings.ToUpper(tokens[i]) {
		case "BY":
			i++
			if i < len(tokens) {
				byField = tokens[i]
				i++
			}
		case "SUM", "AVG", "MIN", "MAX", "COUNT":
			aggOp = strings.ToUpper(tokens[i])
			i++
			if i < len(tokens) && !strings.EqualFold(tokens[i], "WHERE") {
				aggField = tokens[i]
				i++
			}
		case "WHERE":
			i++
			var err error
			filters, err = parseFilters(tokens, &i)
			if err != nil {
				return "ERROR: " + err.Error()
			}
		default:
			i++
		}
	}

	if byField == "" {
		return "ERROR: GROUP requires BY field"
	}

	results, err := eng.Group(db, block, byField, aggOp, aggField, filters)
	if err != nil {
		return "ERROR: " + err.Error()
	}
	return jsonOut(results)
}
