// Code generated by splitting main.go. Part of package main.
package novodb

import (
	"fmt"
	"strconv"
	"strings"
)

func handleDelete(eng *Engine, sess *Session, tokens []string) string {
	if len(tokens) < 2 {
		return "ERROR: DELETE requires block name"
	}
	block := tokens[1]
	db := sess.currentDB
	if db == "" {
		return "ERROR: No database in use"
	}

	if !eng.dirMgr.BlockExists(db, block) {
		return "ERROR: Block not found: " + block
	}

	var filters []Filter

	// Verificar si hay tokens suficientes
	if len(tokens) >= 3 {
		nextToken := tokens[2]
		upperNext := strings.ToUpper(nextToken)

		// Caso: DELETE block ALL
		if upperNext == "ALL" {
			if isInteractive() {
				fmt.Print("Delete ALL documents from " + block + "? (y/N): ")
				var response string
				fmt.Scanln(&response)
				if strings.ToLower(response) != "y" && strings.ToLower(response) != "yes" {
					return "Delete cancelled"
				}
			}
			count, err := eng.Delete(db, block, []Filter{})
			if err != nil {
				return "ERROR: " + err.Error()
			}
			return fmt.Sprintf("Deleted %d documents from %s", count, block)
		}

		// Caso: DELETE block WHERE ...
		if upperNext == "WHERE" {
			idx := 3 // start after WHERE
			var err error
			filters, err = parseFilters(tokens, &idx)
			if err != nil {
				// Si falla, intentar extraer manualmente
				if len(tokens) >= 5 && tokens[3] == "=" {
					fieldName := tokens[2] // WHERE ya fue procesado
					fieldValue := tokens[4]
					fieldValue = strings.Trim(fieldValue, "\"'")
					var filter Filter
					filter.Field = fieldName
					filter.Op = "="
					if num, err := strconv.ParseFloat(fieldValue, 64); err == nil {
						filter.Value = num
					} else {
						filter.Value = fieldValue
					}
					filters = []Filter{filter}
				} else {
					return "ERROR: " + err.Error()
				}
			}
		} else if upperNext == "ID" && len(tokens) >= 4 {
			// DELETE block ID valor
			idValue := tokens[3]
			idValue = strings.Trim(idValue, "\"'")
			var filter Filter
			filter.Field = "id"
			filter.Op = "="
			if num, err := strconv.ParseFloat(idValue, 64); err == nil {
				filter.Value = num
			} else {
				filter.Value = idValue
			}
			filters = []Filter{filter}
		} else if upperNext == "_ID" && len(tokens) >= 5 && tokens[3] == "=" {
			// DELETE block _id = "valor"
			idValue := tokens[4]
			idValue = strings.Trim(idValue, "\"'")
			var filter Filter
			filter.Field = "id" // Convertir _id a id
			filter.Op = "="
			if num, err := strconv.ParseFloat(idValue, 64); err == nil {
				filter.Value = num
			} else {
				filter.Value = idValue
			}
			filters = []Filter{filter}
		} else if len(tokens) >= 5 && tokens[3] == "=" {
			// DELETE block campo = "valor"
			fieldName := nextToken
			fieldValue := tokens[4]
			fieldValue = strings.Trim(fieldValue, "\"'")
			var filter Filter
			filter.Field = fieldName
			filter.Op = "="
			if num, err := strconv.ParseFloat(fieldValue, 64); err == nil {
				filter.Value = num
			} else {
				filter.Value = fieldValue
			}
			filters = []Filter{filter}
		} else {
			// Asumir que es un ID directo: DELETE block valor
			idValue := nextToken
			idValue = strings.Trim(idValue, "\"'")
			var filter Filter
			filter.Field = "id"
			filter.Op = "="
			if num, err := strconv.ParseFloat(idValue, 64); err == nil {
				filter.Value = num
			} else {
				filter.Value = idValue
			}
			filters = []Filter{filter}
		}
	}

	// VERIFICAR QUE NO QUEDE _id EN LOS FILTROS
	for idx := range filters {
		if filters[idx].Field == "_id" {
			filters[idx].Field = "id"
		}
	}

	if len(filters) == 0 {
		return "ERROR: DELETE requires WHERE clause, ID, or ALL"
	}

	count, err := eng.Delete(db, block, filters)
	if err != nil {
		return "ERROR: " + err.Error()
	}

	if count == 0 {
		return "Deleted 0 documents (verify your condition)"
	}
	return fmt.Sprintf("Deleted %d documents", count)
}
