// Code generated by splitting main.go. Part of package main.
package novodb

import (
	"encoding/json"
	"fmt"
	"os"
	"strconv"
	"strings"
	"time"
)

func handleAnalyze(eng *Engine, sess *Session, tokens []string) string {
	if len(tokens) < 3 {
		return "ERROR: ANALYZE requires object (DB or BLOCK)"
	}
	subCmd := strings.ToUpper(tokens[1])
	switch subCmd {
	case "DB":
		var db string
		if len(tokens) >= 3 {
			db = tokens[2]
		} else {
			db = sess.currentDB
		}
		if db == "" {
			return "ERROR: No database specified and no database in use"
		}
		if !eng.dirMgr.DBExists(db) {
			return "ERROR: Database not found: " + db
		}
		stats, err := eng.StatsDB(db)
		if err != nil {
			return "ERROR: " + err.Error()
		}
		if intelStats, ok := eng.intelEngine.stats[db]; ok {
			intelStats.ShardSkew = eng.shardMgr.calculateSkew()
			eng.intelEngine.UpdateStats(db, intelStats)
		}
		return "Database analyzed: " + db + "\n" + jsonOut(stats)

	case "BLOCK":
		var db, block string
		if len(tokens) >= 4 {
			db = tokens[2]
			block = tokens[3]
		} else if len(tokens) >= 3 {
			block = tokens[2]
			db = sess.currentDB
		}
		if db == "" {
			return "ERROR: No database specified and no database in use"
		}
		if block == "" {
			return "ERROR: Block name required"
		}
		if !eng.dirMgr.BlockExists(db, block) {
			return "ERROR: Block not found: " + block
		}
		info, err := eng.DescribeBlock(db, block)
		if err != nil {
			return "ERROR: " + err.Error()
		}
		count, _ := eng.Count(db, block, nil)
		info["analyzed_docs"] = count
		info["analyzed_at"] = time.Now().Unix()
		return "Block analyzed: " + block + "\n" + jsonOut(info)

	default:
		return "ERROR: Unknown ANALYZE object: " + subCmd
	}
}

func handleOptimize(eng *Engine, sess *Session, tokens []string) string {
	if len(tokens) < 3 {
		return "ERROR: OPTIMIZE requires object (DB or BLOCK)"
	}
	subCmd := strings.ToUpper(tokens[1])
	switch subCmd {
	case "DB":
		var db string
		if len(tokens) >= 3 {
			db = tokens[2]
		} else {
			db = sess.currentDB
		}
		if db == "" {
			return "ERROR: No database specified and no database in use"
		}
		if !eng.dirMgr.DBExists(db) {
			return "ERROR: Database not found: " + db
		}
		rounds, err := eng.Compact(db)
		if err != nil {
			return "ERROR: " + err.Error()
		}
		if cfg, ok := eng.intelEngine.GetConfig(db); ok {
			cfg.UpdatedAt = time.Now().Unix()
			eng.intelEngine.SetConfig(cfg)
		}
		return "Database optimized: " + db + " (GC rounds: " + strconv.Itoa(rounds) + ")"

	case "BLOCK":
		var db, block string
		if len(tokens) >= 4 {
			db = tokens[2]
			block = tokens[3]
		} else if len(tokens) >= 3 {
			block = tokens[2]
			db = sess.currentDB
		}
		if db == "" {
			return "ERROR: No database specified and no database in use"
		}
		if block == "" {
			return "ERROR: Block name required"
		}
		if !eng.dirMgr.BlockExists(db, block) {
			return "ERROR: Block not found: " + block
		}
		if err := eng.RebuildBlock(db, block); err != nil {
			return "ERROR: " + err.Error()
		}
		return "Block optimized: " + block

	default:
		return "ERROR: Unknown OPTIMIZE object: " + subCmd
	}
}

func handleExport(eng *Engine, sess *Session, tokens []string) string {
	if len(tokens) < 3 {
		return "ERROR: EXPORT requires block and file"
	}
	block := tokens[1]
	db := sess.currentDB
	if db == "" {
		return "ERROR: No database in use"
	}
	dest := tokens[2]
	dest = strings.Trim(dest, "\"'")

	if !eng.dirMgr.BlockExists(db, block) {
		return "ERROR: Block not found: " + block
	}

	var filters []Filter
	i := 3
	for i < len(tokens) {
		if strings.ToUpper(tokens[i]) == "WHERE" {
			i++
			var err error
			filters, err = parseFilters(tokens, &i)
			if err != nil {
				return "ERROR: " + err.Error()
			}
			break
		} else if strings.ToUpper(tokens[i]) == "SELECT" && i+1 < len(tokens) {
			i += 2
		} else {
			i++
		}
	}

	if len(filters) > 0 {
		q := &Query{Filters: filters, Limit: 1000000}
		result, err := eng.Find(db, block, q)
		if err != nil {
			return "ERROR: " + err.Error()
		}
		data, err := json.MarshalIndent(result.Docs, "", "  ")
		if err != nil {
			return "ERROR: " + err.Error()
		}
		if err := os.WriteFile(dest, data, 0644); err != nil {
			return "ERROR: " + err.Error()
		}
		return fmt.Sprintf("Exported %d documents to %s", len(result.Docs), dest)
	}

	count, err := eng.Export(db, block, dest)
	if err != nil {
		return "ERROR: " + err.Error()
	}
	return fmt.Sprintf("Exported %d documents to %s", count, dest)
}

func handleImport(eng *Engine, sess *Session, tokens []string) string {
	if len(tokens) < 3 {
		return "ERROR: IMPORT requires block and file"
	}
	block := tokens[1]
	db := sess.currentDB
	if db == "" {
		return "ERROR: No database in use"
	}
	src := tokens[2]
	src = strings.Trim(src, "\"'")

	inserted, errors, err := eng.Import(db, block, src)
	if err != nil {
		return "ERROR: " + err.Error()
	}
	return fmt.Sprintf("Imported: %d documents, Errors: %d", inserted, errors)
}

func handleBackupCmd(eng *Engine, sess *Session, tokens []string) string {
	if len(tokens) < 4 {
		return "ERROR: BACKUP requires DB name and file"
	}
	db := tokens[1]
	dest := tokens[2]
	dest = strings.Trim(dest, "\"'")

	if !eng.dirMgr.DBExists(db) {
		return "ERROR: Database not found: " + db
	}

	if err := eng.Backup(db, dest); err != nil {
		return "ERROR: " + err.Error()
	}
	return "Backup completed: " + dest
}

func handleRestoreCmd(eng *Engine, sess *Session, tokens []string) string {
	if len(tokens) < 4 {
		return "ERROR: RESTORE requires DB name and file"
	}
	db := tokens[1]
	src := tokens[2]
	src = strings.Trim(src, "\"'")

	if err := eng.Restore(db, src); err != nil {
		return "ERROR: " + err.Error()
	}
	return "Restore completed: " + src
}

func handleCompactCmd(eng *Engine, sess *Session, tokens []string) string {
	if len(tokens) < 2 {
		return "ERROR: COMPACT requires database name"
	}
	db := tokens[1]

	if !eng.dirMgr.DBExists(db) {
		return "ERROR: Database not found: " + db
	}

	rounds, err := eng.Compact(db)
	if err != nil {
		return "ERROR: " + err.Error()
	}
	return fmt.Sprintf("Compact completed: %d GC rounds", rounds)
}

func handleShardCmd(eng *Engine, sess *Session, tokens []string) string {
	if len(tokens) < 2 {
		return "ERROR: SHARD requires command (STATUS, REBALANCE, SCALE)"
	}
	subCmd := strings.ToUpper(tokens[1])
	switch subCmd {
	case "STATUS":
		sm := eng.shardMgr
		sm.mu.RLock()
		defer sm.mu.RUnlock()
		var sb strings.Builder
		sb.WriteString(fmt.Sprintf("Shard Manager Status:\n  Node: %s\n  Shards: %d\n  Replicas: %d\n  Max Shards: %d\n",
			sm.nodeID, sm.shardCount, sm.replicaCount, eng.config.MaxShardsPerNode))
		sb.WriteString(fmt.Sprintf("  Auto-Scale: %v, Predictive: %v\n",
			eng.config.AutoSplitEnabled, eng.config.PredictiveScaling))
		for id, shard := range sm.shards {
			sb.WriteString(fmt.Sprintf("  %s: docs=%d, size=%s, primary=%s, nodes=%v, status=%s\n",
				id, shard.DocCount, fmtBytes(shard.SizeBytes), shard.Primary, shard.Nodes, shard.Status))
		}
		sb.WriteString(fmt.Sprintf("  Total docs: %d, Skew: %.2f\n", sm.totalDocs(), sm.calculateSkew()))
		return sb.String()

	case "REBALANCE":
		eng.shardMgr.BalanceShards()
		return "Shard rebalance triggered"

	case "SCALE":
		if len(tokens) < 4 {
			return "ERROR: SHARD SCALE requires database name and target shard count"
		}
		db := tokens[2]
		target, err := strconv.Atoi(tokens[3])
		if err != nil {
			return "ERROR: Invalid shard count: " + tokens[3]
		}
		if target < 4 {
			return "ERROR: Shard count must be at least 4"
		}
		if target > eng.config.MaxShardsPerNode {
			return fmt.Sprintf("ERROR: Shard count exceeds max (%d)", eng.config.MaxShardsPerNode)
		}
		if cfg, ok := eng.intelEngine.GetConfig(db); ok {
			cfg.ShardCount = target
			cfg.UpdatedAt = time.Now().Unix()
			eng.intelEngine.SetConfig(cfg)
			return fmt.Sprintf("Database %s scaled to %d shards", db, target)
		}
		return "ERROR: Database not found: " + db

	default:
		return "ERROR: unknown SHARD command: " + subCmd
	}
}

func handleClusterCmd(eng *Engine, sess *Session, tokens []string) string {
	if eng.cluster == nil {
		return "Cluster mode is not enabled"
	}

	status := map[string]any{
		"node_id":   eng.nodeID,
		"state":     eng.cluster.raft.State().String(),
		"is_leader": eng.cluster.IsLeader(),
		"leader":    eng.cluster.GetLeader(),
		"peers":     eng.cluster.GetPeers(),
		"started":   eng.cluster.started,
		"max_nodes": eng.config.MaxClusterNodes,
		"auto_mode": true,
	}
	return jsonOut(status)
}
