// Code generated by splitting main.go. Part of package main.
package novodb

import (
	"fmt"
	"strings"
	"time"
)

func handleCreate(eng *Engine, sess *Session, tokens []string) string {
	subCmd := strings.ToUpper(tokens[1])
	switch subCmd {
	case "DB":
		if len(tokens) < 3 {
			return "ERROR: CREATE DB requires database name"
		}
		db := tokens[2]
		if err := eng.CreateDB(db); err != nil {
			return "ERROR: " + err.Error()
		}
		return "Database created: " + db

	case "BLOCK":
		var db, block string
		if len(tokens) == 3 {
			block = tokens[2]
			db = sess.currentDB
			if db == "" {
				return "ERROR: No database in use. Use: CREATE BLOCK <db> <block> or USE <db> first"
			}
		} else if len(tokens) >= 4 {
			db = tokens[2]
			block = tokens[3]
		} else {
			return "ERROR: CREATE BLOCK requires block name"
		}
		if db == "" {
			return "ERROR: No database specified and no database in use"
		}
		if err := eng.CreateBlock(db, block); err != nil {
			return "ERROR: " + err.Error()
		}
		return "Block created: " + block + " in database: " + db

	case "USER":
		if len(tokens) < 4 {
			return "ERROR: CREATE USER requires username and password"
		}
		username := tokens[2]
		password := tokens[3]
		role := "readwrite"
		for i := 4; i < len(tokens); i++ {
			if strings.ToUpper(tokens[i]) == "ROLE" && i+1 < len(tokens) {
				role = tokens[i+1]
				break
			}
		}
		if role != "admin" && role != "readwrite" && role != "readonly" {
			role = "readwrite"
		}
		if err := eng.CreateUser(username, password, role); err != nil {
			return "ERROR: " + err.Error()
		}
		return "User created: " + username + " (role: " + role + ")"

	default:
		return "ERROR: unknown CREATE object: " + subCmd
	}
}

func handleShow(eng *Engine, sess *Session, tokens []string) string {
	subCmd := strings.ToUpper(tokens[1])
	switch subCmd {
	case "DBS":
		dbs, err := eng.ShowDBs()
		if err != nil {
			return "ERROR: " + err.Error()
		}
		if len(dbs) == 0 {
			return "No databases found"
		}
		var sb strings.Builder
		sb.WriteString("Databases:\n")
		for _, db := range dbs {
			stats, _ := eng.StatsDB(db)
			docCount := int64(0)
			if stats != nil {
				if v, ok := stats["documents"].(int64); ok {
					docCount = v
				}
			}
			blocks, _ := eng.ShowBlocks(db)
			sb.WriteString(fmt.Sprintf("  %s (blocks: %d, docs: %d)\n", db, len(blocks), docCount))
		}
		return sb.String()

	case "BLOCKS":
		var db string
		if len(tokens) > 2 && !strings.EqualFold(tokens[2], "WHERE") && !strings.EqualFold(tokens[2], "LIMIT") {
			db = tokens[2]
		} else {
			db = sess.currentDB
		}
		if db == "" {
			return "ERROR: No database specified and no database in use"
		}
		blocks, err := eng.ShowBlocks(db)
		if err != nil {
			return "ERROR: " + err.Error()
		}
		if len(blocks) == 0 {
			return "No blocks found in database: " + db
		}
		var sb strings.Builder
		sb.WriteString(fmt.Sprintf("Blocks in %s:\n", db))
		sb.WriteString(fmt.Sprintf("%-20s %-10s %-12s %-15s %-20s\n", "NAME", "DOCS", "SIZE", "SHARDS", "CREATED"))
		sb.WriteString(strings.Repeat("-", 80) + "\n")
		for _, block := range blocks {
			info, err := eng.DescribeBlock(db, block)
			if err == nil {
				name := block
				if len(name) > 19 {
					name = name[:19]
				}
				docCount := int64(0)
				if v, ok := info["documents"].(int64); ok {
					docCount = v
				}
				size := "0 B"
				if v, ok := info["size_bytes"].(int64); ok {
					size = fmtBytes(v)
				}
				created := "N/A"
				if v, ok := info["created_at"].(int64); ok {
					created = time.Unix(v, 0).Format("2006-01-02 15:04")
				}
				shards := "N/A"
				if v, ok := info["shards"].(int); ok {
					shards = fmt.Sprintf("%d", v)
				} else if v, ok := info["shards"].(string); ok {
					shards = v
				}
				sb.WriteString(fmt.Sprintf("%-20s %-10d %-12s %-15s %-20s\n",
					name, docCount, size, shards, created))
			} else {
				sb.WriteString(fmt.Sprintf("  %s (error: %v)\n", block, err))
			}
		}
		sb.WriteString(strings.Repeat("-", 80) + "\n")
		sb.WriteString(fmt.Sprintf("Total blocks: %d\n", len(blocks)))
		return sb.String()

	case "USERS":
		users, err := eng.ShowUsers()
		if err != nil {
			return "ERROR: " + err.Error()
		}
		if len(users) == 0 {
			return "No users found"
		}
		var sb strings.Builder
		sb.WriteString("Users:\n")
		for _, u := range users {
			sb.WriteString(fmt.Sprintf("  %s (role: %s, locked: %v)\n", u["username"], u["role"], u["locked"]))
		}
		return sb.String()

	case "CACHE":
		stats := eng.l1Cache.stats()
		return "L1 Cache:\n" + jsonOut(stats)

	case "INDEXES":
		var db string
		if len(tokens) > 2 {
			db = tokens[2]
		} else {
			db = sess.currentDB
		}
		if db == "" {
			return "ERROR: No database specified and no database in use"
		}
		cfg, ok := eng.intelEngine.GetConfig(db)
		if !ok {
			return "ERROR: Database not found: " + db
		}
		var sb strings.Builder
		sb.WriteString(fmt.Sprintf("Indexes in %s:\n", db))
		if len(cfg.Indexes) == 0 {
			sb.WriteString("  No indexes defined\n")
		} else {
			for _, idx := range cfg.Indexes {
				sb.WriteString(fmt.Sprintf("  %s\n", idx))
			}
		}
		return sb.String()

	case "SHARDS":
		sm := eng.shardMgr
		sm.mu.RLock()
		defer sm.mu.RUnlock()
		var sb strings.Builder
		sb.WriteString(fmt.Sprintf("Shard Distribution:\n"))
		sb.WriteString(fmt.Sprintf("%-12s %-10s %-12s %-10s %-20s\n", "SHARD", "DOCS", "SIZE", "PRIMARY", "NODES"))
		sb.WriteString(strings.Repeat("-", 70) + "\n")
		for id, shard := range sm.shards {
			primaryShort := shard.Primary
			if len(primaryShort) > 10 {
				primaryShort = primaryShort[:8] + "..."
			}
			sb.WriteString(fmt.Sprintf("%-12s %-10d %-12s %-10s %-20v\n",
				id, shard.DocCount, fmtBytes(shard.SizeBytes), primaryShort, shard.Nodes))
		}
		sb.WriteString(strings.Repeat("-", 70) + "\n")
		sb.WriteString(fmt.Sprintf("Total shards: %d, Total docs: %d\n", sm.shardCount, sm.totalDocs()))
		return sb.String()

	case "VIEWS":
		viewsMu.RLock()
		defer viewsMu.RUnlock()
		if len(views) == 0 {
			return "No views defined"
		}
		var sb strings.Builder
		sb.WriteString("Views:\n")
		for name, v := range views {
			sb.WriteString(fmt.Sprintf("  %s (db: %s, block: %s)\n", name, v.DB, v.Block))
		}
		return sb.String()

	default:
		return "ERROR: unknown SHOW object: " + subCmd
	}
}
