// Code generated by splitting main.go. Part of package main.
package novodb

import (
	"encoding/json"
	"fmt"
	"strconv"
	"strings"
)

func handleUpdate(eng *Engine, sess *Session, tokens []string) string {
	if len(tokens) < 2 {
		return "ERROR: UPDATE requires block name"
	}

	// ============================================================
	// DETECTAR "UPDATE ALL"
	// ============================================================
	if len(tokens) >= 3 && strings.ToUpper(tokens[2]) == "ALL" {
		block := tokens[1]
		db := sess.currentDB
		if db == "" {
			return "ERROR: No database in use"
		}

		if !eng.dirMgr.BlockExists(db, block) {
			return "ERROR: Block not found: " + block
		}

		setPos := -1
		for j := 3; j < len(tokens); j++ {
			if strings.ToUpper(tokens[j]) == "SET" {
				setPos = j
				break
			}
		}

		if setPos == -1 || setPos+1 >= len(tokens) {
			return "ERROR: UPDATE ALL requires SET with values"
		}

		var op UpdateOp
		op.Set = make(map[string]any)

		jsonStr := strings.Join(tokens[setPos+1:], " ")
		if strings.HasPrefix(jsonStr, "{") {
			var setData map[string]any
			if err := json.Unmarshal([]byte(jsonStr), &setData); err == nil {
				for k, v := range setData {
					op.Set[k] = v
				}
			}
		} else {
			parts := strings.Split(jsonStr, ",")
			for _, part := range parts {
				part = strings.TrimSpace(part)
				if strings.Contains(part, "=") {
					kv := strings.SplitN(part, "=", 2)
					if len(kv) == 2 {
						key := strings.TrimSpace(kv[0])
						valStr := strings.TrimSpace(kv[1])
						var val any
						if num, err := strconv.ParseFloat(valStr, 64); err == nil {
							val = num
						} else {
							val = strings.Trim(valStr, "\"'")
						}
						op.Set[key] = val
					}
				}
			}
		}

		count, err := eng.Update(db, block, []Filter{}, op)
		if err != nil {
			return "ERROR: " + err.Error()
		}
		return fmt.Sprintf("Updated %d documents", count)
	}

	block := tokens[1]
	db := sess.currentDB
	if db == "" {
		return "ERROR: No database in use"
	}

	if !eng.dirMgr.BlockExists(db, block) {
		return "ERROR: Block not found: " + block
	}

	var filters []Filter
	var op UpdateOp
	op.Set = make(map[string]any)
	op.Inc = make(map[string]float64)
	op.Dec = make(map[string]float64)
	op.Push = make(map[string]any)
	op.Pull = make(map[string]any)

	i := 2
	var idValue string
	var hasID bool
	var fieldName string
	var fieldValue string
	var hasField bool
	var hasWhere bool
	var isIDFilter bool

	// ============================================================
	// ANALIZAR EL TOKEN INICIAL PARA DETECTAR ID O CAMPO
	// ============================================================
	if i < len(tokens) {
		firstToken := tokens[i]
		upperFirst := strings.ToUpper(firstToken)

		if upperFirst == "ID" && i+1 < len(tokens) {
			idValue = tokens[i+1]
			hasID = true
			isIDFilter = true
			i += 2
		} else if upperFirst == "WHERE" {
			hasWhere = true
			i++
		} else if upperFirst == "_ID" && i+2 < len(tokens) {
			if tokens[i+1] == "=" {
				idValue = tokens[i+2]
				hasID = true
				isIDFilter = true
				i += 3
			}
		} else if upperFirst == "ID" && i+2 < len(tokens) && tokens[i+1] == "=" {
			idValue = tokens[i+2]
			hasID = true
			isIDFilter = true
			i += 3
		} else {
			if i+2 < len(tokens) {
				operator := strings.ToUpper(tokens[i+1])
				if operator == "=" || operator == "==" || operator == "!=" ||
					operator == ">" || operator == "<" || operator == ">=" || operator == "<=" ||
					operator == "LIKE" || operator == "CONTAINS" {
					fieldName = firstToken
					fieldValue = tokens[i+2]
					hasField = true
					i += 3
				}
			}

			if !hasField && !hasWhere && !hasID {
				if i+1 < len(tokens) {
					nextUpper := strings.ToUpper(tokens[i+1])
					if nextUpper == "SET" || nextUpper == "INC" || nextUpper == "DEC" ||
						nextUpper == "PUSH" || nextUpper == "PULL" {
						idValue = firstToken
						hasID = true
						isIDFilter = true
						i++
					}
				} else {
					if i+1 < len(tokens) {
						idValue = firstToken
						hasID = true
						isIDFilter = true
						i++
					}
				}
			}
		}
	}

	// ============================================================
	// SI ES UN FILTRO POR ID, USAR id (NO _id)
	// ============================================================
	if isIDFilter && idValue != "" {
		idValue = strings.Trim(idValue, "\"'")

		// IMPORTANTE: Usar el campo "id" (no "_id")
		var idFilter Filter
		idFilter.Field = "id" // <- SIEMPRE "id", nunca "_id"
		idFilter.Op = "="
		if num, err := strconv.ParseFloat(idValue, 64); err == nil {
			idFilter.Value = num
		} else {
			idFilter.Value = idValue
		}
		filters = []Filter{idFilter}
	}

	// ============================================================
	// PROCESAR WHERE (convertir _id a id)
	// ============================================================
	if !isIDFilter {
		for j := i; j < len(tokens); j++ {
			if strings.ToUpper(tokens[j]) == "WHERE" {
				var err error
				filters, err = parseFilters(tokens, &j)
				if err != nil {
					return "ERROR: " + err.Error()
				}

				// Convertir cualquier filtro _id a id
				for idx := range filters {
					if filters[idx].Field == "_id" {
						filters[idx].Field = "id"
					}
				}
				break
			}
		}
	}

	if hasField && fieldName != "" && fieldValue != "" {
		fieldValue = strings.Trim(fieldValue, "\"'")
		var fieldFilter Filter
		fieldFilter.Field = fieldName
		fieldFilter.Op = "="
		if num, err := strconv.ParseFloat(fieldValue, 64); err == nil {
			fieldFilter.Value = num
		} else {
			fieldFilter.Value = fieldValue
		}
		filters = []Filter{fieldFilter}
	}

	// ============================================================
	// SI NO HAY WHERE NI ID Y HAY SET, ACTUALIZAR TODOS
	// ============================================================
	if !hasWhere && !hasID && !hasField && !isIDFilter {
		setPos := -1
		for j := i; j < len(tokens); j++ {
			if strings.ToUpper(tokens[j]) == "SET" {
				setPos = j
				break
			}
		}

		if setPos != -1 && setPos+1 < len(tokens) {
			jsonStr := strings.Join(tokens[setPos+1:], " ")
			if strings.HasPrefix(jsonStr, "{") {
				var setData map[string]any
				if err := json.Unmarshal([]byte(jsonStr), &setData); err == nil {
					for k, v := range setData {
						op.Set[k] = v
					}
				}
			} else {
				parts := strings.Split(jsonStr, ",")
				for _, part := range parts {
					part = strings.TrimSpace(part)
					if strings.Contains(part, "=") {
						kv := strings.SplitN(part, "=", 2)
						if len(kv) == 2 {
							key := strings.TrimSpace(kv[0])
							valStr := strings.TrimSpace(kv[1])
							var val any
							if num, err := strconv.ParseFloat(valStr, 64); err == nil {
								val = num
							} else {
								val = strings.Trim(valStr, "\"'")
							}
							op.Set[key] = val
						}
					}
				}
			}

			count, err := eng.Update(db, block, []Filter{}, op)
			if err != nil {
				return "ERROR: " + err.Error()
			}
			return fmt.Sprintf("Updated %d documents", count)
		}
	}

	// ============================================================
	// PROCESAR SET, INC, DEC, PUSH, PULL
	// ============================================================
	for i < len(tokens) {
		token := strings.ToUpper(tokens[i])

		switch token {
		case "SET":
			i++
			if i < len(tokens) {
				jsonStr := strings.Join(tokens[i:], " ")
				if strings.HasPrefix(jsonStr, "{") {
					jsonEnd := strings.Index(jsonStr, "}")
					if jsonEnd != -1 {
						jsonStr = jsonStr[:jsonEnd+1]
						var setData map[string]any
						if err := json.Unmarshal([]byte(jsonStr), &setData); err == nil {
							for k, v := range setData {
								op.Set[k] = v
							}
							i += len(strings.Split(jsonStr, " "))
							break
						}
					}
				}
				for i < len(tokens) {
					if strings.ToUpper(tokens[i]) == "WHERE" ||
						strings.ToUpper(tokens[i]) == "INC" ||
						strings.ToUpper(tokens[i]) == "DEC" ||
						strings.ToUpper(tokens[i]) == "PUSH" ||
						strings.ToUpper(tokens[i]) == "PULL" {
						break
					}
					if strings.Contains(tokens[i], "=") {
						parts := strings.SplitN(tokens[i], "=", 2)
						if len(parts) == 2 {
							key := strings.TrimSpace(parts[0])
							valStr := strings.TrimSpace(parts[1])
							var val any
							if err := json.Unmarshal([]byte(valStr), &val); err != nil {
								val = strings.Trim(valStr, "\"'")
							}
							op.Set[key] = val
							i++
							continue
						}
					} else if strings.Contains(tokens[i], ":") {
						parts := strings.SplitN(tokens[i], ":", 2)
						if len(parts) == 2 {
							key := strings.TrimSpace(parts[0])
							valStr := strings.TrimSpace(parts[1])
							var val any
							if err := json.Unmarshal([]byte(valStr), &val); err != nil {
								val = strings.Trim(valStr, "\"'")
							}
							op.Set[key] = val
							i++
							continue
						}
					}
					if i+2 < len(tokens) && tokens[i+1] == "=" {
						key := tokens[i]
						valStr := tokens[i+2]
						var val any
						if err := json.Unmarshal([]byte(valStr), &val); err != nil {
							val = strings.Trim(valStr, "\"'")
						}
						op.Set[key] = val
						i += 3
						continue
					}
					i++
				}
			}
		case "INC":
			i++
			for i < len(tokens) {
				if strings.ToUpper(tokens[i]) == "WHERE" ||
					strings.ToUpper(tokens[i]) == "SET" ||
					strings.ToUpper(tokens[i]) == "DEC" ||
					strings.ToUpper(tokens[i]) == "PUSH" ||
					strings.ToUpper(tokens[i]) == "PULL" {
					break
				}
				if strings.Contains(tokens[i], "=") {
					parts := strings.SplitN(tokens[i], "=", 2)
					if len(parts) == 2 {
						val, err := strconv.ParseFloat(parts[1], 64)
						if err == nil {
							op.Inc[parts[0]] = val
						}
					}
				} else if strings.Contains(tokens[i], ":") {
					parts := strings.SplitN(tokens[i], ":", 2)
					if len(parts) == 2 {
						val, err := strconv.ParseFloat(parts[1], 64)
						if err == nil {
							op.Inc[parts[0]] = val
						}
					}
				} else if i+2 < len(tokens) && tokens[i+1] == "=" {
					val, err := strconv.ParseFloat(tokens[i+2], 64)
					if err == nil {
						op.Inc[tokens[i]] = val
					}
					i += 2
				}
				i++
			}
		case "DEC":
			i++
			for i < len(tokens) {
				if strings.ToUpper(tokens[i]) == "WHERE" ||
					strings.ToUpper(tokens[i]) == "SET" ||
					strings.ToUpper(tokens[i]) == "INC" ||
					strings.ToUpper(tokens[i]) == "PUSH" ||
					strings.ToUpper(tokens[i]) == "PULL" {
					break
				}
				if strings.Contains(tokens[i], "=") {
					parts := strings.SplitN(tokens[i], "=", 2)
					if len(parts) == 2 {
						val, err := strconv.ParseFloat(parts[1], 64)
						if err == nil {
							op.Dec[parts[0]] = val
						}
					}
				} else if strings.Contains(tokens[i], ":") {
					parts := strings.SplitN(tokens[i], ":", 2)
					if len(parts) == 2 {
						val, err := strconv.ParseFloat(parts[1], 64)
						if err == nil {
							op.Dec[parts[0]] = val
						}
					}
				} else if i+2 < len(tokens) && tokens[i+1] == "=" {
					val, err := strconv.ParseFloat(tokens[i+2], 64)
					if err == nil {
						op.Dec[tokens[i]] = val
					}
					i += 2
				}
				i++
			}
		case "PUSH":
			i++
			for i < len(tokens) {
				if strings.ToUpper(tokens[i]) == "WHERE" ||
					strings.ToUpper(tokens[i]) == "SET" ||
					strings.ToUpper(tokens[i]) == "INC" ||
					strings.ToUpper(tokens[i]) == "DEC" ||
					strings.ToUpper(tokens[i]) == "PULL" {
					break
				}
				if strings.Contains(tokens[i], "=") {
					parts := strings.SplitN(tokens[i], "=", 2)
					if len(parts) == 2 {
						var val any
						if err := json.Unmarshal([]byte(parts[1]), &val); err != nil {
							val = strings.Trim(parts[1], "\"'")
						}
						op.Push[parts[0]] = val
					}
				} else if strings.Contains(tokens[i], ":") {
					parts := strings.SplitN(tokens[i], ":", 2)
					if len(parts) == 2 {
						var val any
						if err := json.Unmarshal([]byte(parts[1]), &val); err != nil {
							val = strings.Trim(parts[1], "\"'")
						}
						op.Push[parts[0]] = val
					}
				} else if i+2 < len(tokens) && tokens[i+1] == "=" {
					var val any
					if err := json.Unmarshal([]byte(tokens[i+2]), &val); err != nil {
						val = strings.Trim(tokens[i+2], "\"'")
					}
					op.Push[tokens[i]] = val
					i += 2
				}
				i++
			}
		case "PULL":
			i++
			for i < len(tokens) {
				if strings.ToUpper(tokens[i]) == "WHERE" ||
					strings.ToUpper(tokens[i]) == "SET" ||
					strings.ToUpper(tokens[i]) == "INC" ||
					strings.ToUpper(tokens[i]) == "DEC" ||
					strings.ToUpper(tokens[i]) == "PUSH" {
					break
				}
				if strings.Contains(tokens[i], "=") {
					parts := strings.SplitN(tokens[i], "=", 2)
					if len(parts) == 2 {
						var val any
						if err := json.Unmarshal([]byte(parts[1]), &val); err != nil {
							val = strings.Trim(parts[1], "\"'")
						}
						op.Pull[parts[0]] = val
					}
				} else if strings.Contains(tokens[i], ":") {
					parts := strings.SplitN(tokens[i], ":", 2)
					if len(parts) == 2 {
						var val any
						if err := json.Unmarshal([]byte(parts[1]), &val); err != nil {
							val = strings.Trim(parts[1], "\"'")
						}
						op.Pull[parts[0]] = val
					}
				} else if i+2 < len(tokens) && tokens[i+1] == "=" {
					var val any
					if err := json.Unmarshal([]byte(tokens[i+2]), &val); err != nil {
						val = strings.Trim(tokens[i+2], "\"'")
					}
					op.Pull[tokens[i]] = val
					i += 2
				}
				i++
			}
		default:
			if i+2 < len(tokens) {
				operator := strings.ToUpper(tokens[i+1])
				if operator == "=" || operator == "==" {
					fieldName := tokens[i]
					fieldValue := tokens[i+2]
					fieldValue = strings.Trim(fieldValue, "\"'")
					var fieldFilter Filter
					fieldFilter.Field = fieldName
					fieldFilter.Op = "="
					if num, err := strconv.ParseFloat(fieldValue, 64); err == nil {
						fieldFilter.Value = num
					} else {
						fieldFilter.Value = fieldValue
					}
					filters = []Filter{fieldFilter}
					i += 3
					continue
				}
			}
			i++
		}
	}

	if len(filters) == 0 && !hasID && !hasField && !hasWhere && !isIDFilter {
		return "ERROR: UPDATE requires WHERE clause, ID, field condition"
	}

	// ============================================================
	// VERIFICAR QUE EL FILTRO USARÁ EL CAMPO "id" CORRECTO
	// ============================================================
	for idx := range filters {
		if filters[idx].Field == "_id" {
			filters[idx].Field = "id"
		}
	}

	count, err := eng.Update(db, block, filters, op)
	if err != nil {
		return "ERROR: " + err.Error()
	}

	if count == 0 {
		return "Updated 0 documents (verify your condition)"
	}
	return fmt.Sprintf("Updated %d documents", count)
}
