// Code generated by splitting main.go. Part of package main.
package novodb

import (
	"encoding/json"
	"fmt"
	"strconv"
	"strings"
)

func handleInsert(eng *Engine, sess *Session, tokens []string) string {
	if len(tokens) < 3 {
		return "ERROR: INSERT requires block name and document data"
	}

	block := tokens[1]
	db := sess.currentDB
	if db == "" {
		return "ERROR: No database in use"
	}

	var customID string
	var dataTokens []string
	startIdx := 2

	if len(tokens) >= 4 {
		secondToken := tokens[2]
		if !strings.HasPrefix(secondToken, "{") &&
			!strings.HasPrefix(secondToken, "[") &&
			!strings.HasPrefix(secondToken, "\"") &&
			secondToken != "NULL" &&
			!strings.EqualFold(secondToken, "FROM") &&
			!strings.EqualFold(secondToken, "TO") &&
			!strings.EqualFold(secondToken, "WHERE") &&
			!strings.EqualFold(secondToken, "SET") &&
			!strings.EqualFold(secondToken, "LIMIT") &&
			!strings.EqualFold(secondToken, "ORDER") &&
			!strings.EqualFold(secondToken, "SELECT") {
			customID = strings.Trim(secondToken, "\"'")
			startIdx = 3
			dataTokens = tokens[startIdx:]
		} else {
			dataTokens = tokens[startIdx:]
		}
	} else {
		dataTokens = tokens[startIdx:]
	}

	if len(dataTokens) == 0 {
		return "ERROR: No document data provided"
	}

	if len(tokens) >= 3 && strings.ToUpper(tokens[2]) == "FROM" {
		if len(tokens) < 4 {
			return "ERROR: INSERT FROM requires file name"
		}
		srcFile := strings.Trim(tokens[3], "\"'")
		inserted, errors, err := eng.Import(db, block, srcFile)
		if err != nil {
			return "ERROR: " + err.Error()
		}
		return fmt.Sprintf("Imported: %d documents, Errors: %d", inserted, errors)
	}

	jsonStr := strings.Join(dataTokens, " ")

	if strings.HasPrefix(jsonStr, "{") {
		var data map[string]any
		if err := json.Unmarshal([]byte(jsonStr), &data); err == nil {
			if customID != "" {
				data["id"] = customID
			}
			var doc *Document
			var err error
			if customID != "" {
				doc, err = eng.insertWithID(db, block, customID, data)
			} else {
				doc, err = eng.Insert(db, block, data)
			}
			if err != nil {
				return "ERROR: " + err.Error()
			}
			if customID != "" {
				return fmt.Sprintf("Inserted document: %s (ID: %s, shard: %s)", doc.ID, customID, doc.ShardID)
			}
			return fmt.Sprintf("Inserted document: %s (shard: %s)", doc.ID, doc.ShardID)
		}
	}

	if strings.HasPrefix(jsonStr, "[") && strings.HasSuffix(jsonStr, "]") {
		var docs []map[string]any
		if err := json.Unmarshal([]byte(jsonStr), &docs); err == nil {
			if len(docs) > 0 {
				if customID != "" {
					docs[0]["id"] = customID
					doc, err := eng.insertWithID(db, block, customID, docs[0])
					if err != nil {
						return "ERROR: " + err.Error()
					}
					inserted, errors := int64(1), int64(0)
					for i := 1; i < len(docs); i++ {
						if _, err := eng.Insert(db, block, docs[i]); err != nil {
							errors++
						} else {
							inserted++
						}
					}
					return fmt.Sprintf("Inserted: %d documents, Errors: %d (first ID: %s)", inserted, errors, doc.ID)
				}
				inserted, errors := eng.InsertBatch(db, block, docs)
				return fmt.Sprintf("Inserted: %d documents, Errors: %d", inserted, errors)
			}
			return "ERROR: Empty document array"
		}
	}

	if strings.Contains(jsonStr, ";") {
		parts := strings.Split(jsonStr, ";")
		docs := make([]map[string]any, 0, len(parts))
		errors := 0

		for _, part := range parts {
			part = strings.TrimSpace(part)
			if part == "" {
				continue
			}

			if strings.HasPrefix(part, "{") {
				var data map[string]any
				if err := json.Unmarshal([]byte(part), &data); err == nil {
					docs = append(docs, data)
				} else {
					errors++
				}
				continue
			}

			data := make(map[string]any)
			fields := strings.Split(part, ",")
			success := false

			for _, field := range fields {
				field = strings.TrimSpace(field)
				if field == "" {
					continue
				}

				if strings.Contains(field, "=") {
					kv := strings.SplitN(field, "=", 2)
					if len(kv) == 2 {
						key := strings.TrimSpace(kv[0])
						valStr := strings.TrimSpace(kv[1])
						var parsed any
						if num, err := strconv.ParseFloat(valStr, 64); err == nil {
							parsed = num
						} else if strings.HasPrefix(valStr, "{") {
							var nested map[string]any
							if err := json.Unmarshal([]byte(valStr), &nested); err == nil {
								parsed = nested
							} else {
								parsed = strings.Trim(valStr, "\"'")
							}
						} else {
							parsed = strings.Trim(valStr, "\"'")
						}
						data[key] = parsed
						success = true
					}
				} else if strings.Contains(field, ":") {
					kv := strings.SplitN(field, ":", 2)
					if len(kv) == 2 {
						key := strings.TrimSpace(kv[0])
						valStr := strings.TrimSpace(kv[1])
						var parsed any
						if num, err := strconv.ParseFloat(valStr, 64); err == nil {
							parsed = num
						} else if strings.HasPrefix(valStr, "{") {
							var nested map[string]any
							if err := json.Unmarshal([]byte(valStr), &nested); err == nil {
								parsed = nested
							} else {
								parsed = strings.Trim(valStr, "\"'")
							}
						} else {
							parsed = strings.Trim(valStr, "\"'")
						}
						data[key] = parsed
						success = true
					}
				}
			}

			if success && len(data) > 0 {
				if customID != "" && len(docs) == 0 {
					data["id"] = customID
				}
				docs = append(docs, data)
			} else {
				errors++
			}
		}

		if len(docs) > 0 {
			if customID != "" && len(docs) > 0 {
				docs[0]["id"] = customID
				doc, err := eng.insertWithID(db, block, customID, docs[0])
				if err != nil {
					return "ERROR: " + err.Error()
				}
				inserted, batchErrors := int64(1), int64(0)
				for i := 1; i < len(docs); i++ {
					if _, err := eng.Insert(db, block, docs[i]); err != nil {
						batchErrors++
					} else {
						inserted++
					}
				}
				return fmt.Sprintf("Inserted: %d documents, Errors: %d (first ID: %s)", inserted, batchErrors+int64(errors), doc.ID)
			}
			inserted, batchErrors := eng.InsertBatch(db, block, docs)
			return fmt.Sprintf("Inserted: %d documents, Errors: %d", inserted, batchErrors+int64(errors))
		}

		if errors > 0 {
			return fmt.Sprintf("ERROR: Failed to parse %d document(s)", errors)
		}
	}

	data := make(map[string]any)
	fields := strings.Split(jsonStr, ",")
	success := false

	for _, field := range fields {
		field = strings.TrimSpace(field)
		if field == "" {
			continue
		}

		if strings.Contains(field, "=") {
			kv := strings.SplitN(field, "=", 2)
			if len(kv) == 2 {
				key := strings.TrimSpace(kv[0])
				valStr := strings.TrimSpace(kv[1])
				var parsed any
				if num, err := strconv.ParseFloat(valStr, 64); err == nil {
					parsed = num
				} else if strings.HasPrefix(valStr, "{") {
					var nested map[string]any
					if err := json.Unmarshal([]byte(valStr), &nested); err == nil {
						parsed = nested
					} else {
						parsed = strings.Trim(valStr, "\"'")
					}
				} else {
					parsed = strings.Trim(valStr, "\"'")
				}
				data[key] = parsed
				success = true
			}
		} else if strings.Contains(field, ":") {
			kv := strings.SplitN(field, ":", 2)
			if len(kv) == 2 {
				key := strings.TrimSpace(kv[0])
				valStr := strings.TrimSpace(kv[1])
				var parsed any
				if num, err := strconv.ParseFloat(valStr, 64); err == nil {
					parsed = num
				} else if strings.HasPrefix(valStr, "{") {
					var nested map[string]any
					if err := json.Unmarshal([]byte(valStr), &nested); err == nil {
						parsed = nested
					} else {
						parsed = strings.Trim(valStr, "\"'")
					}
				} else {
					parsed = strings.Trim(valStr, "\"'")
				}
				data[key] = parsed
				success = true
			}
		}
	}

	if success && len(data) > 0 {
		if customID != "" {
			data["id"] = customID
		}
		var doc *Document
		var err error
		if customID != "" {
			doc, err = eng.insertWithID(db, block, customID, data)
		} else {
			doc, err = eng.Insert(db, block, data)
		}
		if err != nil {
			return "ERROR: " + err.Error()
		}
		if customID != "" {
			return fmt.Sprintf("Inserted document: %s (ID: %s, shard: %s)", doc.ID, customID, doc.ShardID)
		}
		return fmt.Sprintf("Inserted document: %s (shard: %s)", doc.ID, doc.ShardID)
	}

	return "ERROR: Could not parse document data. Use JSON, key:value, or key=value format"
}
