// Code generated by splitting main.go. Part of package main.
package novodb

import (
	"bytes"
	"compress/gzip"
	"github.com/klauspost/compress/zstd"
	"io"
	"sync"
)

var zstdEncoder, _ = zstd.NewWriter(nil, zstd.WithEncoderLevel(zstd.SpeedDefault))

var zstdDecoder, _ = zstd.NewReader(nil)

var gzipPool = sync.Pool{
	New: func() interface{} {
		return gzip.NewWriter(nil)
	},
}

type CompressionType string

const (
	CompressionNone CompressionType = "none"
	CompressionZstd CompressionType = "zstd"
	CompressionGzip CompressionType = "gzip"
)

func compressData(data []byte, ctype CompressionType) ([]byte, bool, error) {
	if len(data) < 1024 {
		return data, false, nil
	}

	switch ctype {
	case CompressionZstd:
		compressed := zstdEncoder.EncodeAll(data, nil)
		if len(compressed) < len(data)*90/100 {
			return compressed, true, nil
		}
	case CompressionGzip:
		var buf bytes.Buffer
		gz := gzipPool.Get().(*gzip.Writer)
		gz.Reset(&buf)
		if _, err := gz.Write(data); err != nil {
			gz.Close()
			return data, false, err
		}
		gz.Close()
		gzipPool.Put(gz)
		compressed := buf.Bytes()
		if len(compressed) < len(data)*90/100 {
			return compressed, true, nil
		}
	}
	return data, false, nil
}

func decompressData(data []byte) ([]byte, error) {
	if decompressed, err := zstdDecoder.DecodeAll(data, nil); err == nil {
		return decompressed, nil
	}
	if r, err := gzip.NewReader(bytes.NewReader(data)); err == nil {
		defer r.Close()
		return io.ReadAll(r)
	}
	return data, nil
}
