// Code generated by splitting main.go. Part of package main.
package novodb

import (
	"time"
)

type Config struct {
	DataRoot      string `json:"data_root"`
	VMURL         string `json:"vm_url"`
	CacheMB       int    `json:"cache_mb"`
	L2CacheMB     int    `json:"l2_cache_mb"`
	Workers       int    `json:"workers"`
	LogLevel      string `json:"log_level"`
	MetricsPort   int    `json:"metrics_port"`
	RaftPort      int    `json:"raft_port"`
	RaftBind      string `json:"raft_bind"`
	QueryPort     int    `json:"query_port"`
	AdminPort     int    `json:"admin_port"`
	QueryUser     string `json:"query_user"`
	QueryPassword string `json:"query_password"`
	ShardCount    int    `json:"shard_count"`
	ReplicaCount  int    `json:"replica_count"`
	WALSegments   int    `json:"wal_segments"`
	AutoCluster   bool   `json:"auto_cluster"`

	FastStartup       bool `json:"fast_startup"`
	LazyIndexLoading  bool `json:"lazy_index_loading"`
	PreloadCache      bool `json:"preload_cache"`
	CompressLargeDocs bool `json:"compress_large_docs"`
	SkipLargeIndexes  bool `json:"skip_large_indexes"`
	UseStreamingWAL   bool `json:"use_streaming_wal"`

	MaxShardsPerNode  int   `json:"max_shards_per_node"`
	MaxClusterNodes   int   `json:"max_cluster_nodes"`
	AutoScaleInterval int   `json:"auto_scale_interval"`
	PredictionWindow  int   `json:"prediction_window"`
	MinShardDocs      int64 `json:"min_shard_docs"`
	MaxShardDocs      int64 `json:"max_shard_docs"`
	ScaleUpCooldown   int   `json:"scale_up_cooldown"`
	ScaleDownCooldown int   `json:"scale_down_cooldown"`
	AutoMergeEnabled  bool  `json:"auto_merge_enabled"`
	AutoSplitEnabled  bool  `json:"auto_split_enabled"`
	PredictiveScaling bool  `json:"predictive_scaling"`
	AggressiveScaling bool  `json:"aggressive_scaling"`
	MaxReplicas       int   `json:"max_replicas"`
	MinReplicas       int   `json:"min_replicas"`

	MaxDocumentSize    int64 `json:"max_document_size"`
	CompressThreshold  int64 `json:"compress_threshold"`
	IndexSkipThreshold int64 `json:"index_skip_threshold"`
	LargeDocThreshold  int64 `json:"large_doc_threshold"`

	MaxConcurrentQueries int           `json:"max_concurrent_queries"`
	QueryTimeout         time.Duration `json:"query_timeout"`
	TransactionTimeout   time.Duration `json:"transaction_timeout"`
	MaxQueryDepth        int           `json:"max_query_depth"`
	MaxBatchSize         int           `json:"max_batch_size"`
	RateLimit            int           `json:"rate_limit"`

	JWTSecret        string        `json:"jwt_secret"`
	TokenExpiry      time.Duration `json:"token_expiry"`
	MaxLoginAttempts int           `json:"max_login_attempts"`
	LockoutDuration  time.Duration `json:"lockout_duration"`
	TLSEnabled       bool          `json:"tls_enabled"`
	TLSCertFile      string        `json:"tls_cert_file"`
	TLSKeyFile       string        `json:"tls_key_file"`

	// FLEX-COLUMN Configuration
	FlexColumn *FlexColumnConfig `json:"flex_column"`
}

type FlexColumnConfig struct {
	Enabled              bool          `json:"enabled"`
	DocumentCacheMB      int           `json:"document_cache_mb"`
	ColumnarIndexEnabled bool          `json:"columnar_index_enabled"`
	AutoDetectHotFields  bool          `json:"auto_detect_hot_fields"`
	MaterializedViews    bool          `json:"materialized_views"`
	ColumnarCompression  string        `json:"columnar_compression"`
	MaxColumnarFields    int           `json:"max_columnar_fields"`
	HotFieldThreshold    float64       `json:"hot_field_threshold"`
	WorkerCount          int           `json:"worker_count"`
	UpdateQueueSize      int           `json:"update_queue_size"`
	ViewRefreshInterval  time.Duration `json:"view_refresh_interval"`
}

func DefaultFlexColumnConfig() *FlexColumnConfig {
	return &FlexColumnConfig{
		Enabled:              true,
		DocumentCacheMB:      defaultColumnarCacheMB,
		ColumnarIndexEnabled: true,
		AutoDetectHotFields:  true,
		MaterializedViews:    true,
		ColumnarCompression:  "zstd",
		MaxColumnarFields:    maxColumnarFields,
		HotFieldThreshold:    defaultHotFieldThreshold,
		WorkerCount:          4,
		UpdateQueueSize:      10000,
		ViewRefreshInterval:  5 * time.Minute,
	}
}
