// Code generated by splitting main.go. Part of package main.
package novodb

import (
	"crypto/rand"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"go.uber.org/zap"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"
)

func DefaultConfig() *Config {
	secretBytes := make([]byte, 32)
	if _, err := rand.Read(secretBytes); err != nil {
		log().Fatal("Failed to generate secure JWT secret (crypto/rand failed)",
			zap.Error(err))
	}
	jwtSecret := base64.URLEncoding.EncodeToString(secretBytes)

	return &Config{
		DataRoot:             defaultDataRoot,
		VMURL:                defaultVMURL,
		CacheMB:              defaultCacheMB,
		L2CacheMB:            defaultL2CacheMB,
		Workers:              defaultWorkers,
		LogLevel:             defaultLogLevel,
		MetricsPort:          defaultMetricsPort,
		RaftPort:             defaultRaftPort,
		RaftBind:             defaultRaftBind,
		QueryPort:            defaultQueryPort,
		AdminPort:            defaultAdminPort,
		QueryUser:            "admin",
		QueryPassword:        generateRandomPassword(),
		ShardCount:           defaultShardCount,
		ReplicaCount:         defaultReplicaCount,
		WALSegments:          defaultWALSegments,
		AutoCluster:          true,
		FastStartup:          false,
		LazyIndexLoading:     true,
		PreloadCache:         false,
		CompressLargeDocs:    true,
		SkipLargeIndexes:     true,
		UseStreamingWAL:      true,
		MaxShardsPerNode:     1000000,
		MaxClusterNodes:      10000000,
		AutoScaleInterval:    10,
		PredictionWindow:     48,
		MinShardDocs:         10000,
		MaxShardDocs:         1000000,
		ScaleUpCooldown:      60,
		ScaleDownCooldown:    300,
		AutoMergeEnabled:     true,
		AutoSplitEnabled:     true,
		PredictiveScaling:    true,
		AggressiveScaling:    true,
		MaxReplicas:          10,
		MinReplicas:          1,
		MaxDocumentSize:      10 << 20,
		CompressThreshold:    100 << 10,
		IndexSkipThreshold:   1 << 20,
		LargeDocThreshold:    5 << 20,
		MaxConcurrentQueries: 100000,
		QueryTimeout:         60 * time.Second,
		TransactionTimeout:   30 * time.Second,
		MaxQueryDepth:        10,
		MaxBatchSize:         10000,
		RateLimit:            10000,
		JWTSecret:            jwtSecret,
		TokenExpiry:          defaultTokenExpiry,
		MaxLoginAttempts:     maxLoginAttempts,
		LockoutDuration:      lockoutDuration,
		TLSEnabled:           false,
		FlexColumn:           DefaultFlexColumnConfig(),
	}
}

func (c *Config) LoadFromFile(path string) error {
	data, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, c)
}

func (c *Config) SaveToFile(path string) error {
	if dir := filepath.Dir(path); dir != "." && dir != "" {
		if err := os.MkdirAll(dir, 0755); err != nil {
			return err
		}
	}
	cfgCopy := *c
	cfgCopy.QueryPassword = "REDACTED"
	data, err := json.MarshalIndent(cfgCopy, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, data, 0600)
}

func (c *Config) MergeEnv() {
	if v := os.Getenv("NOVODB_DATA"); v != "" {
		c.DataRoot = v
	}
	if v := os.Getenv("NOVODB_VM"); v != "" {
		c.VMURL = v
	}
	if v := os.Getenv("NOVODB_CACHE"); v != "" {
		if n, err := strconv.Atoi(v); err == nil {
			c.CacheMB = n
		}
	}
	if v := os.Getenv("NOVODB_L2_CACHE"); v != "" {
		if n, err := strconv.Atoi(v); err == nil {
			c.L2CacheMB = n
		}
	}
	if v := os.Getenv("NOVODB_WORKERS"); v != "" {
		if n, err := strconv.Atoi(v); err == nil {
			c.Workers = n
		}
	}
	if v := os.Getenv("NOVODB_LOG_LEVEL"); v != "" {
		c.LogLevel = v
	}
	if v := os.Getenv("NOVODB_METRICS"); v != "" {
		if n, err := strconv.Atoi(v); err == nil {
			c.MetricsPort = n
		}
	}
	if v := os.Getenv("NOVODB_RAFT_PORT"); v != "" {
		if n, err := strconv.Atoi(v); err == nil {
			c.RaftPort = n
		}
	}
	if v := os.Getenv("NOVODB_RAFT_BIND"); v != "" {
		c.RaftBind = v
	}
	if v := os.Getenv("NOVODB_SHARD_COUNT"); v != "" {
		if n, err := strconv.Atoi(v); err == nil {
			c.ShardCount = n
		}
	}
	if v := os.Getenv("NOVODB_REPLICA_COUNT"); v != "" {
		if n, err := strconv.Atoi(v); err == nil {
			c.ReplicaCount = n
		}
	}
	if v := os.Getenv("NOVODB_QUERY_PORT"); v != "" {
		if n, err := strconv.Atoi(v); err == nil {
			c.QueryPort = n
		}
	}
	if v := os.Getenv("NOVODB_QUERY_USER"); v != "" {
		c.QueryUser = v
	}
	if v := os.Getenv("NOVODB_QUERY_PASSWORD"); v != "" {
		c.QueryPassword = v
	}
	if v := os.Getenv("NOVODB_FAST_STARTUP"); v != "" {
		c.FastStartup = strings.ToLower(v) == "true" || v == "1"
	}
	if v := os.Getenv("NOVODB_COMPRESS_LARGE"); v != "" {
		c.CompressLargeDocs = strings.ToLower(v) == "true" || v == "1"
	}
	if v := os.Getenv("NOVODB_MAX_DOC_SIZE"); v != "" {
		if n, err := strconv.ParseInt(v, 10, 64); err == nil {
			c.MaxDocumentSize = n
		}
	}
	if v := os.Getenv("NOVODB_JWT_SECRET"); v != "" {
		c.JWTSecret = v
	}
	if v := os.Getenv("NOVODB_TLS_ENABLED"); v != "" {
		c.TLSEnabled = strings.ToLower(v) == "true" || v == "1"
	}
}

func (c *Config) Validate() error {
	if c.DataRoot == "" {
		return fmt.Errorf("data_root cannot be empty")
	}
	if c.CacheMB < 64 {
		return fmt.Errorf("cache_mb must be at least 64")
	}
	if c.L2CacheMB < 64 {
		return fmt.Errorf("l2_cache_mb must be at least 64")
	}
	if c.ShardCount < 1 {
		return fmt.Errorf("shard_count must be at least 1")
	}
	if c.ReplicaCount < 1 {
		return fmt.Errorf("replica_count must be at least 1")
	}
	if c.MaxShardsPerNode < 1 {
		return fmt.Errorf("max_shards_per_node must be at least 1")
	}
	if c.MaxClusterNodes < 1 {
		return fmt.Errorf("max_cluster_nodes must be at least 1")
	}
	if c.QueryTimeout <= 0 {
		return fmt.Errorf("query_timeout must be positive")
	}
	if c.TransactionTimeout <= 0 {
		return fmt.Errorf("transaction_timeout must be positive")
	}
	if c.MaxDocumentSize < 1024 {
		return fmt.Errorf("max_document_size must be at least 1KB")
	}
	if c.MaxBatchSize < 1 {
		return fmt.Errorf("max_batch_size must be at least 1")
	}
	if c.MaxQueryDepth < 1 {
		return fmt.Errorf("max_query_depth must be at least 1")
	}
	if c.RateLimit < 1 {
		return fmt.Errorf("rate_limit must be at least 1")
	}
	if c.JWTSecret == "" {
		return fmt.Errorf("jwt_secret cannot be empty")
	}
	return nil
}
