// Code generated by splitting main.go. Part of package main.
package novodb

import (
	"encoding/json"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"sync"
)

type DirectoryManager struct {
	dataRoot string
	mu       sync.RWMutex
}

func NewDirectoryManager(dataRoot string) *DirectoryManager {
	return &DirectoryManager{
		dataRoot: dataRoot,
	}
}

func (dm *DirectoryManager) Init() error {
	if err := os.MkdirAll(dm.dataRoot, 0750); err != nil {
		return err
	}

	systemDirs := []string{
		filepath.Join(dm.dataRoot, "__users"),
		filepath.Join(dm.dataRoot, "__raft"),
		filepath.Join(dm.dataRoot, "__shards"),
		filepath.Join(dm.dataRoot, "__cluster"),
		filepath.Join(dm.dataRoot, "__system"),
	}

	for _, dir := range systemDirs {
		if err := os.MkdirAll(dir, 0750); err != nil {
			return err
		}
	}

	return nil
}

func (dm *DirectoryManager) DBPath(name string) string {
	return filepath.Join(dm.dataRoot, name)
}

func (dm *DirectoryManager) DBExists(name string) bool {
	_, err := os.Stat(dm.DBPath(name))
	return err == nil
}

func (dm *DirectoryManager) BlockPath(dbName, blockName string) string {
	return filepath.Join(dm.DBPath(dbName), blockName)
}

func (dm *DirectoryManager) BlockDataPath(dbName, blockName string) string {
	return filepath.Join(dm.BlockPath(dbName, blockName), "__data")
}

func (dm *DirectoryManager) BlockIndexPath(dbName, blockName string) string {
	return filepath.Join(dm.BlockPath(dbName, blockName), "__index")
}

func (dm *DirectoryManager) BlockMetaPath(dbName, blockName string) string {
	return filepath.Join(dm.BlockPath(dbName, blockName), "__meta")
}

func (dm *DirectoryManager) BlockExists(dbName, blockName string) bool {
	_, err := os.Stat(dm.BlockPath(dbName, blockName))
	return err == nil
}

func (dm *DirectoryManager) CreateBlockDirectories(dbName, blockName string) error {
	paths := []string{
		dm.BlockPath(dbName, blockName),
		dm.BlockDataPath(dbName, blockName),
		dm.BlockIndexPath(dbName, blockName),
		dm.BlockMetaPath(dbName, blockName),
	}

	for _, path := range paths {
		if err := os.MkdirAll(path, 0750); err != nil {
			return err
		}
	}

	return nil
}

func (dm *DirectoryManager) RemoveBlockDirectories(dbName, blockName string) error {
	return os.RemoveAll(dm.BlockPath(dbName, blockName))
}

func (dm *DirectoryManager) ListDatabases() ([]string, error) {
	entries, err := os.ReadDir(dm.dataRoot)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, err
	}

	var dbs []string
	for _, entry := range entries {
		if entry.IsDir() && !strings.HasPrefix(entry.Name(), "__") {
			dbs = append(dbs, entry.Name())
		}
	}
	sort.Strings(dbs)
	return dbs, nil
}

func (dm *DirectoryManager) ListBlocks(dbName string) ([]string, error) {
	dbPath := dm.DBPath(dbName)
	entries, err := os.ReadDir(dbPath)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, err
	}

	var blocks []string
	for _, entry := range entries {
		if entry.IsDir() && !strings.HasPrefix(entry.Name(), "__") {
			blocks = append(blocks, entry.Name())
		}
	}
	sort.Strings(blocks)
	return blocks, nil
}

func (dm *DirectoryManager) SaveBlockMeta(dbName, blockName string, meta BlockMeta) error {
	metaPath := dm.BlockMetaPath(dbName, blockName)
	metaFile := filepath.Join(metaPath, "block.json")

	data, err := json.MarshalIndent(meta, "", "  ")
	if err != nil {
		return err
	}

	return os.WriteFile(metaFile, data, 0644)
}

func (dm *DirectoryManager) LoadBlockMeta(dbName, blockName string) (BlockMeta, error) {
	metaFile := filepath.Join(dm.BlockMetaPath(dbName, blockName), "block.json")

	data, err := os.ReadFile(metaFile)
	if err != nil {
		return BlockMeta{}, err
	}

	var meta BlockMeta
	if err := json.Unmarshal(data, &meta); err != nil {
		return BlockMeta{}, err
	}

	return meta, nil
}

func (dm *DirectoryManager) SaveDBMeta(dbName string, meta map[string]any) error {
	metaPath := filepath.Join(dm.DBPath(dbName), "__meta")
	if err := os.MkdirAll(metaPath, 0750); err != nil {
		return err
	}

	metaFile := filepath.Join(metaPath, "db.json")
	data, err := json.MarshalIndent(meta, "", "  ")
	if err != nil {
		return err
	}

	return os.WriteFile(metaFile, data, 0644)
}

func (dm *DirectoryManager) LoadDBMeta(dbName string) (map[string]any, error) {
	metaFile := filepath.Join(dm.DBPath(dbName), "__meta", "db.json")

	data, err := os.ReadFile(metaFile)
	if err != nil {
		return nil, err
	}

	var meta map[string]any
	if err := json.Unmarshal(data, &meta); err != nil {
		return nil, err
	}

	return meta, nil
}
