// Code generated by splitting main.go. Part of package main.
package novodb

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go.uber.org/zap"
	"net/http"
	"strings"
	"sync"
	"sync/atomic"
	"time"
)

type DistributedQueryExecutor struct {
	engine   *Engine
	cluster  *ClusterManager
	shardMgr *ShardManager
	nodeID   string
	client   *http.Client
}

func NewDistributedQueryExecutor(engine *Engine, cluster *ClusterManager, shardMgr *ShardManager) *DistributedQueryExecutor {
	return &DistributedQueryExecutor{
		engine:   engine,
		cluster:  cluster,
		shardMgr: shardMgr,
		nodeID:   cluster.nodeID,
		client: &http.Client{
			Timeout: 60 * time.Second,
			Transport: &http.Transport{
				MaxIdleConns:        10000,
				MaxIdleConnsPerHost: 10000,
				IdleConnTimeout:     120 * time.Second,
				DisableCompression:  false,
			},
		},
	}
}

type DistributedQueryResult struct {
	Results       []QueryResult
	TotalDocs     int64
	TotalScanned  int64
	Errors        []error
	NodesQueried  int
	ShardsQueried int
}

func (dqe *DistributedQueryExecutor) ExecuteDistributedQuery(dbName, block string, q *Query) (*DistributedQueryResult, error) {
	start := time.Now()
	defer func() {
		log().Debug("Distributed query completed",
			zap.String("db", dbName),
			zap.String("block", block),
			zap.Duration("duration", time.Since(start)))
	}()

	if dqe.cluster == nil || !dqe.cluster.started {
		result, err := dqe.engine.Find(dbName, block, q)
		if err != nil {
			return nil, err
		}
		return &DistributedQueryResult{
			Results:       []QueryResult{*result},
			TotalDocs:     result.Total,
			TotalScanned:  result.Scanned,
			NodesQueried:  1,
			ShardsQueried: 0,
		}, nil
	}

	if !dqe.cluster.IsLeader() {
		leader := dqe.cluster.GetLeader()
		if leader == "" {
			return nil, fmt.Errorf("no leader available")
		}
		return dqe.forwardToLeader(leader, dbName, block, q)
	}

	shardIDs := dqe.shardMgr.GetShardsForFilter(dbName, block, q.Filters)
	if len(shardIDs) == 0 {
		result, err := dqe.engine.Find(dbName, block, q)
		if err != nil {
			return nil, err
		}
		return &DistributedQueryResult{
			Results:       []QueryResult{*result},
			TotalDocs:     result.Total,
			TotalScanned:  result.Scanned,
			NodesQueried:  1,
			ShardsQueried: 0,
		}, nil
	}

	nodeShards := make(map[string][]string)
	for _, shardID := range shardIDs {
		if dqe.shardMgr.IsShardPrimary(shardID) || dqe.shardMgr.IsShardLocal(shardID) {
			nodeShards[dqe.nodeID] = append(nodeShards[dqe.nodeID], shardID)
		} else {
			primary := dqe.shardMgr.GetShardPrimary(shardID)
			if primary != "" {
				nodeShards[primary] = append(nodeShards[primary], shardID)
			}
		}
	}

	var wg sync.WaitGroup
	var mu sync.Mutex
	results := make([]QueryResult, 0)
	errors := make([]error, 0)
	totalDocs := int64(0)
	totalScanned := int64(0)
	var nodesQueried int32 = 0

	sem := make(chan struct{}, 5000)

	for node, shards := range nodeShards {
		if node == "" {
			continue
		}
		wg.Add(1)
		sem <- struct{}{}
		go func(node string, shards []string) {
			defer wg.Done()
			defer func() { <-sem }()
			atomic.AddInt32(&nodesQueried, 1)

			if node == dqe.nodeID {
				for _, shardID := range shards {
					result, err := dqe.engine.Find(dbName, block, q)
					if err != nil {
						mu.Lock()
						errors = append(errors, fmt.Errorf("local shard %s: %w", shardID, err))
						mu.Unlock()
						continue
					}
					mu.Lock()
					results = append(results, *result)
					totalDocs += result.Total
					totalScanned += result.Scanned
					mu.Unlock()
				}
			} else {
				shardIDs := strings.Join(shards, ",")
				resp, err := dqe.forwardQueryToNode(node, dbName, block, q, shardIDs)
				if err != nil {
					mu.Lock()
					errors = append(errors, fmt.Errorf("node %s shards %s: %w", node, shardIDs, err))
					mu.Unlock()
					return
				}
				mu.Lock()
				results = append(results, *resp)
				totalDocs += resp.Total
				totalScanned += resp.Scanned
				mu.Unlock()
			}
		}(node, shards)
	}

	wg.Wait()

	return &DistributedQueryResult{
		Results:       results,
		TotalDocs:     totalDocs,
		TotalScanned:  totalScanned,
		Errors:        errors,
		NodesQueried:  int(nodesQueried),
		ShardsQueried: len(shardIDs),
	}, nil
}

func (dqe *DistributedQueryExecutor) forwardToLeader(leader, dbName, block string, q *Query) (*DistributedQueryResult, error) {
	req := struct {
		DB    string `json:"db"`
		Block string `json:"block"`
		Query *Query `json:"query"`
	}{
		DB:    dbName,
		Block: block,
		Query: q,
	}

	data, err := json.Marshal(req)
	if err != nil {
		return nil, err
	}

	resp, err := dqe.client.Post(
		fmt.Sprintf("http://%s/raft/query", leader),
		"application/json",
		bytes.NewReader(data),
	)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	var result DistributedQueryResult
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, err
	}

	return &result, nil
}

func (dqe *DistributedQueryExecutor) forwardQueryToNode(node, dbName, block string, q *Query, shardIDs string) (*QueryResult, error) {
	req := struct {
		DB       string `json:"db"`
		Block    string `json:"block"`
		Query    *Query `json:"query"`
		ShardIDs string `json:"shard_ids"`
	}{
		DB:       dbName,
		Block:    block,
		Query:    q,
		ShardIDs: shardIDs,
	}

	data, err := json.Marshal(req)
	if err != nil {
		return nil, err
	}

	resp, err := dqe.client.Post(
		fmt.Sprintf("http://%s/raft/query_local", node),
		"application/json",
		bytes.NewReader(data),
	)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	var result QueryResult
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, err
	}

	return &result, nil
}

func (dqe *DistributedQueryExecutor) HandleQueryLocal(w http.ResponseWriter, r *http.Request) {
	var req struct {
		DB       string `json:"db"`
		Block    string `json:"block"`
		Query    *Query `json:"query"`
		ShardIDs string `json:"shard_ids"`
	}
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	if req.ShardIDs != "" {
		shards := strings.Split(req.ShardIDs, ",")
		hasPrimary := false
		for _, shardID := range shards {
			if dqe.shardMgr.IsShardPrimary(shardID) || dqe.shardMgr.IsShardLocal(shardID) {
				hasPrimary = true
				break
			}
		}
		if !hasPrimary {
			http.Error(w, "Not primary for any of the requested shards", http.StatusServiceUnavailable)
			return
		}
	}

	result, err := dqe.engine.Find(req.DB, req.Block, req.Query)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(result)
}

func (dqe *DistributedQueryExecutor) HandleQuery(w http.ResponseWriter, r *http.Request) {
	var req struct {
		DB    string `json:"db"`
		Block string `json:"block"`
		Query *Query `json:"query"`
	}
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	result, err := dqe.ExecuteDistributedQuery(req.DB, req.Block, req.Query)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(result)
}
