// Code generated by splitting main.go. Part of package main.
package novodb

type Document struct {
	ID      string         `json:"_id"`
	Data    map[string]any `json:"data"`
	Meta    DocMeta        `json:"meta"`
	ShardID string         `json:"_shard_id,omitempty"`
	LargeID string         `json:"_large_id,omitempty"`
}

type DocMeta struct {
	CreatedAt int64 `json:"created_at"`
	UpdatedAt int64 `json:"updated_at"`
	Version   int64 `json:"version"`
}

type BlockMeta struct {
	Name      string `json:"name"`
	DB        string `json:"db"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
	DocCount  int64  `json:"doc_count"`
	SizeBytes int64  `json:"size_bytes"`
}
