// Code generated by splitting main.go. Part of package main.
package novodb

import (
	"fmt"
	"path/filepath"
	"strings"
	"time"

	"novodb/internal/novodb/parse"
)

type Session struct {
	currentDB string
	authUser  string
	authRole  string
	token     string
	currentTx *Transaction
}

func parseAndExec(eng *Engine, sess *Session, input string) string {
	input = strings.TrimSpace(input)
	if input == "" || strings.HasPrefix(input, "--") {
		return ""
	}

	if !eng.rateLimiter.Allow(sess.authUser) {
		return "ERROR: rate limit exceeded"
	}

	blocked, reason, err := eng.riskEngine.Evaluate(input, sess.authUser)
	if err != nil && blocked {
		return "ERROR: " + reason
	}

	tokens := parse.Tokenize(input)
	if len(tokens) == 0 {
		return ""
	}

	cmd := strings.ToUpper(tokens[0])

	switch cmd {
	case "VERSION":
		return "NovoDB v" + Version + " (DataEngine - Enterprise Edition - OPTIMIZED FOR LARGE DOCUMENTS)"

	case "PING":
		return "PONG " + time.Now().UTC().Format(time.RFC3339)

	case "STATUS":
		return handleStatusCmd(eng, sess)

	case "HEALTH":
		return handleHealthCmd(eng)

	case "HELP":
		return helpText()

	case "EXIT", "QUIT", "\\Q":
		return "__EXIT__"

	case "PWD":
		if sess.currentDB != "" {
			return filepath.Join(eng.dataRoot, sess.currentDB)
		}
		return eng.dataRoot

	case "CD":
		if len(tokens) < 2 {
			return "ERROR: CD requires database name"
		}
		db := tokens[1]
		if err := eng.UseDB(db); err != nil {
			return "ERROR: " + err.Error()
		}
		sess.currentDB = db
		return "Now using database: " + db

	case "LS":
		if len(tokens) >= 2 && !strings.HasPrefix(tokens[1], "-") {
			db := tokens[1]
			blocks, err := eng.ShowBlocks(db)
			if err != nil {
				return "ERROR: " + err.Error()
			}
			if len(blocks) == 0 {
				return "No blocks found in " + db
			}
			var sb strings.Builder
			sb.WriteString("Blocks in " + db + ":\n")
			for _, b := range blocks {
				sb.WriteString("  " + b + "\n")
			}
			return sb.String()
		}
		if sess.currentDB != "" {
			blocks, err := eng.ShowBlocks(sess.currentDB)
			if err != nil {
				return "ERROR: " + err.Error()
			}
			if len(blocks) == 0 {
				return "No blocks found in " + sess.currentDB
			}
			var sb strings.Builder
			sb.WriteString("Blocks in " + sess.currentDB + ":\n")
			for _, b := range blocks {
				sb.WriteString("  " + b + "\n")
			}
			return sb.String()
		}
		dbs, err := eng.ShowDBs()
		if err != nil {
			return "ERROR: " + err.Error()
		}
		if len(dbs) == 0 {
			return "No databases found"
		}
		var sb strings.Builder
		sb.WriteString("Databases:\n")
		for _, db := range dbs {
			sb.WriteString("  " + db + "\n")
		}
		return sb.String()

	case "TREE":
		return handleTree(eng, sess)

	case "CREATE":
		if len(tokens) < 3 {
			return "ERROR: CREATE requires at least 3 arguments"
		}
		return handleCreate(eng, sess, tokens)

	case "DROP":
		if len(tokens) < 3 {
			return "ERROR: DROP requires at least 3 arguments"
		}
		return handleDrop(eng, sess, tokens)

	case "RENAME":
		if len(tokens) < 5 {
			return "ERROR: RENAME requires object, old name, TO, and new name"
		}
		return handleRename(eng, sess, tokens)

	case "SHOW":
		if len(tokens) < 2 {
			return "ERROR: SHOW requires an argument"
		}
		return handleShow(eng, sess, tokens)

	case "INFO":
		if len(tokens) < 3 {
			return "ERROR: INFO requires DB or BLOCK and name"
		}
		return handleInfo(eng, sess, tokens)

	case "DESCRIBE":
		if len(tokens) < 3 {
			return "ERROR: DESCRIBE requires DB or BLOCK and name"
		}
		return handleDescribe(eng, sess, tokens)

	case "STATS":
		return handleStats(eng, sess, tokens)

	case "SIZE":
		return handleSize(eng, sess, tokens)

	case "USE":
		if len(tokens) < 2 {
			return "ERROR: USE requires database name"
		}
		db := tokens[1]
		if err := eng.UseDB(db); err != nil {
			return "ERROR: " + err.Error()
		}
		sess.currentDB = db
		return "Using database: " + db

	case "INSERT":
		return handleInsert(eng, sess, tokens)

	case "FIND":
		return handleFind(eng, sess, tokens)

	case "GET":
		return handleGet(eng, sess, tokens)

	case "SEARCH":
		return handleSearch(eng, sess, tokens)

	case "UPDATE":
		return handleUpdate(eng, sess, tokens)

	case "DELETE":
		return handleDelete(eng, sess, tokens)

	case "CLEAR", "EMPTY":
		return handleClear(eng, sess, tokens)

	case "COUNT":
		return handleCount(eng, sess, tokens)

	case "SUM", "AVG", "MIN", "MAX", "MEDIAN", "MODE", "STDDEV":
		return handleAggregate(eng, sess, cmd, tokens)

	case "GROUP":
		return handleGroup(eng, sess, tokens)

	case "JOIN":
		return handleJoin(eng, sess, tokens)

	case "EXPORT":
		return handleExport(eng, sess, tokens)

	case "IMPORT":
		return handleImport(eng, sess, tokens)

	case "BACKUP":
		return handleBackupCmd(eng, sess, tokens)

	case "RESTORE":
		return handleRestoreCmd(eng, sess, tokens)

	case "COMPACT":
		return handleCompactCmd(eng, sess, tokens)

	case "ANALYZE":
		return handleAnalyze(eng, sess, tokens)

	case "OPTIMIZE":
		return handleOptimize(eng, sess, tokens)

	case "REBUILD":
		return handleRebuild(eng, sess, tokens)

	case "CHECK":
		return handleCheck(eng, sess, tokens)

	case "REPAIR":
		return handleRepair(eng, sess, tokens)

	case "SHARD":
		return handleShardCmd(eng, sess, tokens)

	case "CLUSTER":
		return handleClusterCmd(eng, sess, tokens)

	case "VIEW":
		return handleViewCmd(eng, sess, tokens)

	// FLEX-COLUMN commands
	case "FLEX":
		return handleFlexCommand(eng, sess, tokens)

	// ACID TRANSACTION COMMANDS
	case "BEGIN":
		return handleTransaction(eng, sess, tokens)

	case "COMMIT":
		return handleTransaction(eng, sess, tokens)

	case "ROLLBACK", "ABORT":
		return handleTransaction(eng, sess, tokens)

	case "TX", "TRANSACTION":
		return handleTransaction(eng, sess, tokens)

	default:
		if len(tokens) == 1 {
			viewsMu.RLock()
			_, ok := views[tokens[0]]
			viewsMu.RUnlock()
			if ok {
				return handleViewCmd(eng, sess, []string{"VIEW", tokens[0]})
			}
		}
		return fmt.Sprintf("ERROR: unknown command '%s' -- type HELP for available commands", tokens[0])
	}
}

func handleStatusCmd(eng *Engine, sess *Session) string {
	status := map[string]any{
		"version":          Version,
		"build":            Build,
		"node_id":          eng.nodeID,
		"data_root":        eng.dataRoot,
		"current_db":       sess.currentDB,
		"shards":           eng.shardMgr.shardCount,
		"replicas":         eng.shardMgr.replicaCount,
		"ops":              eng.opCount.Load(),
		"memory":           getMemStats(),
		"l1_cache":         eng.l1Cache.stats(),
		"metrics":          eng.metrics.Stats(),
		"uptime":           time.Since(eng.startupTime).Seconds(),
		"fast_startup":     eng.config.FastStartup,
		"max_nodes":        eng.config.MaxClusterNodes,
		"max_shards":       eng.config.MaxShardsPerNode,
		"max_doc_size":     eng.config.MaxDocumentSize,
		"compress_large":   eng.config.CompressLargeDocs,
		"lazy_index":       eng.config.LazyIndexLoading,
		"predictive_scale": eng.config.PredictiveScaling,
		"auto_cluster":     eng.config.AutoCluster,
		"buffer_pool":      eng.bufferPool.Stats(),
		"risk_engine": map[string]any{
			"enabled": eng.riskEngine.config.Enabled,
			"rules":   len(eng.riskEngine.rules),
		},
		"flex_column": eng.flexEngine.Stats(),
	}
	if eng.cluster != nil {
		status["cluster"] = map[string]any{
			"role":   eng.cluster.raft.State().String(),
			"leader": string(eng.cluster.raft.Leader()),
			"peers":  eng.cluster.GetPeers(),
		}
	}
	if eng.wal != nil {
		status["wal"] = eng.wal.Stats()
	}
	return jsonOut(status)
}

func handleHealthCmd(eng *Engine) string {
	health := map[string]any{
		"status":           "ok",
		"version":          Version,
		"uptime":           time.Since(eng.startupTime).Seconds(),
		"node_id":          eng.nodeID,
		"shards":           eng.shardMgr.shardCount,
		"ops":              eng.opCount.Load(),
		"max_nodes":        eng.config.MaxClusterNodes,
		"max_shards":       eng.config.MaxShardsPerNode,
		"fast_startup":     eng.config.FastStartup,
		"lazy_index":       eng.config.LazyIndexLoading,
		"compress_large":   eng.config.CompressLargeDocs,
		"max_doc_size":     eng.config.MaxDocumentSize,
		"auto_cluster":     eng.config.AutoCluster,
		"predictive_scale": eng.config.PredictiveScaling,
		"flex_column":      eng.flexEngine.Stats(),
	}
	return jsonOut(health)
}

func handleTree(eng *Engine, sess *Session) string {
	var sb strings.Builder
	sb.WriteString("Data Tree:\n")
	sb.WriteString(eng.dataRoot + "/\n")

	dbs, err := eng.ShowDBs()
	if err != nil {
		return "ERROR: " + err.Error()
	}

	for _, db := range dbs {
		prefix := "├── "
		sb.WriteString(prefix + db + "/\n")
		blocks, _ := eng.ShowBlocks(db)
		for i, block := range blocks {
			if i == len(blocks)-1 {
				sb.WriteString("    └── " + block + "/\n")
			} else {
				sb.WriteString("    ├── " + block + "/\n")
			}
		}
	}
	return sb.String()
}
