// Code generated by splitting main.go. Part of package main.
package novodb

import (
	"context"
	"fmt"
	"go.uber.org/zap"
	"net/http"
	"os"
	"path/filepath"
	"sync"
	"sync/atomic"
	"time"
)

type Engine struct {
	dataRoot      string
	vmURL         string
	pool          *dbPool
	dirMgr        *DirectoryManager
	l1Cache       *L1Cache
	l2Cache       *L2IndexCache
	wp            *workerPool
	lockManager   *shardedLockManager
	opCount       atomic.Int64
	vmClient      *http.Client
	metrics       *MetricsCollector
	queryOpt      *QueryOptimizer
	cluster       *ClusterManager
	shardMgr      *ShardManager
	distQuery     *DistributedQueryExecutor
	intelEngine   *IntelligentEngine
	flexEngine    *FlexColumnEngine
	nodeID        string
	wal           *WAL
	config        *Config
	startupTime   time.Time
	auditLogger   *AuditLogger
	tokenManager  *TokenManager
	rateLimiter   *RateLimiter
	externalStore ExternalStorage
	riskEngine    *RiskEngine
	stopChan      chan struct{}
	ctx           context.Context
	cancel        context.CancelFunc
	bufferPool    *BufferPool
	txManager     *TxManager
}

type MetricsCollector struct {
	mu            sync.RWMutex
	queryCount    atomic.Int64
	queryDuration atomic.Int64
	slowQuery     atomic.Int64
	errors        atomic.Int64
}

func NewMetricsCollector() *MetricsCollector {
	return &MetricsCollector{}
}

func (m *MetricsCollector) RecordQuery(duration time.Duration) {
	m.queryCount.Add(1)
	m.queryDuration.Add(int64(duration.Microseconds()))
	if duration > time.Second {
		m.slowQuery.Add(1)
	}
}

func (m *MetricsCollector) Stats() map[string]any {
	count := m.queryCount.Load()
	dur := m.queryDuration.Load()
	avg := float64(0)
	if count > 0 {
		avg = float64(dur) / float64(count) / 1000
	}
	return map[string]any{
		"queries":      count,
		"avg_ms":       avg,
		"slow_queries": m.slowQuery.Load(),
		"errors":       m.errors.Load(),
	}
}

func NewEngine(config *Config) *Engine {
	startTime := time.Now()

	ctx, cancel := context.WithCancel(context.Background())

	nodeID := os.Getenv("NOVODB_NODE_ID")
	if nodeID == "" {
		hostname, _ := os.Hostname()
		nodeID = fmt.Sprintf("%s-%d", hostname, time.Now().UnixNano()%10000)
	}

	dirMgr := NewDirectoryManager(config.DataRoot)
	if err := dirMgr.Init(); err != nil {
		log().Fatal("Failed to initialize directory structure", zap.Error(err))
	}

	l1 := newL1Cache(int64(config.CacheMB), true, 1*time.Hour)
	l2 := newL2IndexCache(config.L2CacheMB*1024, config.LazyIndexLoading, 24*time.Hour)

	intelEngine := NewIntelligentEngine(config)

	engine := &Engine{
		dataRoot:    config.DataRoot,
		vmURL:       config.VMURL,
		pool:        newDBPool(l1, l2, dirMgr),
		dirMgr:      dirMgr,
		l1Cache:     l1,
		l2Cache:     l2,
		wp:          newWorkerPool(config.Workers),
		lockManager: newShardedLockManager(100000),
		vmClient: &http.Client{
			Timeout: 5 * time.Second,
			Transport: &http.Transport{
				MaxIdleConns:        10000,
				MaxIdleConnsPerHost: 10000,
				IdleConnTimeout:     120 * time.Second,
				DisableCompression:  false,
			},
		},
		metrics:     NewMetricsCollector(),
		queryOpt:    NewQueryOptimizer(),
		nodeID:      nodeID,
		intelEngine: intelEngine,
		config:      config,
		startupTime: startTime,
		stopChan:    make(chan struct{}),
		ctx:         ctx,
		cancel:      cancel,
		bufferPool:  NewBufferPool(128 << 20),
	}

	engine.tokenManager = NewTokenManager(config.JWTSecret, config.TokenExpiry)
	engine.rateLimiter = NewRateLimiter(config.RateLimit, time.Minute)
	engine.riskEngine = NewRiskEngine()

	if config.LargeDocThreshold > 0 {
		externalPath := filepath.Join(config.DataRoot, "__external")
		if storage, err := NewFileSystemStorage(externalPath); err == nil {
			engine.externalStore = storage
			log().Info("External storage initialized", zap.String("path", externalPath))
		}
	}

	engine.shardMgr = NewShardManager(nodeID, config, intelEngine)

	// Initialize FLEX-COLUMN
	flexConfig := config.FlexColumn
	if flexConfig == nil {
		flexConfig = DefaultFlexColumnConfig()
	}
	engine.flexEngine = NewFlexColumnEngine(engine, flexConfig)

	walDir := filepath.Join(config.DataRoot, systemDB, "wal")
	if wal, err := NewWAL(walDir, config.WALSegments, config.UseStreamingWAL); err == nil {
		engine.wal = wal
		log().Info("WAL initialized",
			zap.String("dir", walDir),
			zap.Bool("streaming", config.UseStreamingWAL))
	} else {
		log().Warn("Failed to initialize WAL", zap.Error(err))
	}

	if engine.wal != nil {
		engine.txManager = NewTxManager(engine, engine.wal, config.TransactionTimeout)
		log().Info("ACID Transaction Manager initialized",
			zap.String("isolation", engine.txManager.isolation),
			zap.Duration("timeout", config.TransactionTimeout))
	} else {
		log().Warn("ACID Transaction Manager initialized without WAL (durability not guaranteed)")
		engine.txManager = NewTxManager(engine, nil, config.TransactionTimeout)
	}

	auditPath := filepath.Join(config.DataRoot, "__audit.log")
	if auditLogger, err := NewAuditLogger(auditPath); err == nil {
		engine.auditLogger = auditLogger
		log().Info("Audit logger initialized", zap.String("path", auditPath))
	} else {
		log().Warn("Failed to initialize audit logger", zap.Error(err))
	}

	if engine.wal != nil && !config.FastStartup {
		if applied, err := engine.wal.RecoverApply(engine); err == nil {
			log().Info("WAL recovery completed", zap.Int64("entries", applied))
		} else {
			log().Warn("WAL recovery failed", zap.Error(err))
		}
	} else if engine.wal != nil && config.FastStartup {
		log().Warn("FAST STARTUP: WAL recovery skipped - data loss possible on crash")
		if err := engine.wal.Truncate(); err != nil {
			log().Warn("Failed to truncate WAL", zap.Error(err))
		}
	}

	go engine.backgroundCleanup()

	log().Info("Engine initialized successfully",
		zap.String("node_id", nodeID),
		zap.Duration("startup_time", time.Since(startTime)),
		zap.Bool("acid_enabled", engine.txManager != nil),
		zap.String("isolation_level", engine.txManager.isolation),
		zap.Int("shards", config.ShardCount),
		zap.Int("replicas", config.ReplicaCount),
		zap.Int("max_nodes", config.MaxClusterNodes),
		zap.Int("max_shards_per_node", config.MaxShardsPerNode),
		zap.Int64("max_document_size", config.MaxDocumentSize),
		zap.Int64("compress_threshold", config.CompressThreshold),
		zap.Int64("large_doc_threshold", config.LargeDocThreshold),
		zap.Bool("fast_startup", config.FastStartup),
		zap.Bool("compress_large_docs", config.CompressLargeDocs),
		zap.Bool("lazy_index_loading", config.LazyIndexLoading),
		zap.Bool("predictive_scaling", config.PredictiveScaling),
		zap.Bool("auto_cluster", config.AutoCluster),
		zap.String("wal_status", map[bool]string{true: "enabled", false: "disabled"}[engine.wal != nil]),
		zap.Bool("flex_column_enabled", flexConfig.Enabled),
		zap.Bool("flex_columnar_index", flexConfig.ColumnarIndexEnabled),
		zap.Bool("flex_materialized_views", flexConfig.MaterializedViews),
	)

	return engine
}

func (e *Engine) backgroundCleanup() {
	ticker := time.NewTicker(1 * time.Hour)
	defer ticker.Stop()

	for {
		select {
		case <-ticker.C:
			e.cleanupExpiredData()
		case <-e.stopChan:
			return
		case <-e.ctx.Done():
			return
		}
	}
}

func (e *Engine) cleanupExpiredData() {
	e.l1Cache.cleanupExpired()
	if e.tokenManager != nil {
		e.tokenManager.Cleanup()
	}
	log().Debug("Background cleanup completed")
}

func (e *Engine) InitCluster() error {
	if !e.config.AutoCluster {
		log().Info("Auto-cluster disabled, running in standalone mode")
		return nil
	}

	cluster, err := NewClusterManager(e, e.config)
	if err != nil {
		return err
	}
	e.cluster = cluster
	e.distQuery = NewDistributedQueryExecutor(e, cluster, e.shardMgr)
	cluster.Start()

	if e.wal != nil && !e.config.FastStartup {
		if applied, err := e.wal.RecoverApply(e); err == nil {
			log().Info("WAL recovery applied", zap.Int64("entries", applied))
		} else {
			log().Warn("WAL recovery failed", zap.Error(err))
		}
	} else if e.wal != nil && e.config.FastStartup {
		if err := e.wal.Truncate(); err != nil {
			log().Warn("Failed to truncate WAL", zap.Error(err))
		}
	}

	startupDuration := time.Since(e.startupTime)
	metricStartupTime.Set(startupDuration.Seconds())
	log().Info("Engine startup completed",
		zap.Duration("duration", startupDuration),
		zap.Bool("fast_startup", e.config.FastStartup),
		zap.Bool("compress_large", e.config.CompressLargeDocs),
		zap.Int64("max_doc_size", e.config.MaxDocumentSize))

	log().Info("Auto-cluster initialized",
		zap.String("node_id", e.nodeID),
		zap.Int("shards", e.shardMgr.shardCount),
		zap.Int("replicas", e.shardMgr.replicaCount),
		zap.Int("max_nodes", e.config.MaxClusterNodes))

	return nil
}
