// Code generated by splitting main.go. Part of package main.
package novodb

import (
	"crypto/rand"
	"fmt"
	"go.uber.org/zap"
	"sort"
	"sync"
	"sync/atomic"
	"time"
)

type FlexColumnEngine struct {
	engine *Engine
	config *FlexColumnConfig

	mu sync.RWMutex
	// index[db][block][field][value] = set of document IDs
	index map[string]map[string]map[string]map[string]map[string]struct{}
	// docFields[db][block][docID] = field -> indexed value (string form)
	docFields map[string]map[string]map[string]map[string]string
	// fieldStats[db][block][field] = number of writes touching that field
	fieldStats map[string]map[string]map[string]int64

	queries atomic.Int64
	hits    atomic.Int64

	stopCh chan struct{}
	wg     sync.WaitGroup
}

func NewFlexColumnEngine(engine *Engine, config *FlexColumnConfig) *FlexColumnEngine {
	if config == nil {
		config = DefaultFlexColumnConfig()
	}
	f := &FlexColumnEngine{
		engine:     engine,
		config:     config,
		index:      make(map[string]map[string]map[string]map[string]map[string]struct{}),
		docFields:  make(map[string]map[string]map[string]map[string]string),
		fieldStats: make(map[string]map[string]map[string]int64),
		stopCh:     make(chan struct{}),
	}
	if config.Enabled {
		f.wg.Add(1)
		go f.maintenanceLoop()
	}
	return f
}

func (f *FlexColumnEngine) maintenanceLoop() {
	defer f.wg.Done()
	interval := f.config.ViewRefreshInterval
	if interval <= 0 {
		interval = 5 * time.Minute
	}
	ticker := time.NewTicker(interval)
	defer ticker.Stop()
	for {
		select {
		case <-ticker.C:
			// Periodic housekeeping hook (hot-field promotion, view refresh,
			// etc.). Intentionally a no-op placeholder: the index is kept
			// consistent synchronously on every write, so there is nothing
			// that strictly needs to happen here today.
		case <-f.stopCh:
			return
		}
	}
}

func (f *FlexColumnEngine) Stop() {
	if f == nil {
		return
	}
	select {
	case <-f.stopCh:
		// already closed
	default:
		close(f.stopCh)
	}
	f.wg.Wait()
}

// indexableFields returns up to config.MaxColumnarFields scalar field names
// from a document, sorted for determinism.
func (f *FlexColumnEngine) indexableFields(data map[string]any) []string {
	if len(data) == 0 {
		return nil
	}
	fields := make([]string, 0, len(data))
	for k, v := range data {
		switch v.(type) {
		case string, float64, int, int64, bool:
			fields = append(fields, k)
		}
	}
	sort.Strings(fields)
	if f.config.MaxColumnarFields > 0 && len(fields) > f.config.MaxColumnarFields {
		fields = fields[:f.config.MaxColumnarFields]
	}
	return fields
}

func (f *FlexColumnEngine) ensureMapsLocked(dbName, block string) {
	if f.index[dbName] == nil {
		f.index[dbName] = make(map[string]map[string]map[string]map[string]struct{})
	}
	if f.index[dbName][block] == nil {
		f.index[dbName][block] = make(map[string]map[string]map[string]struct{})
	}
	if f.docFields[dbName] == nil {
		f.docFields[dbName] = make(map[string]map[string]map[string]string)
	}
	if f.docFields[dbName][block] == nil {
		f.docFields[dbName][block] = make(map[string]map[string]string)
	}
	if f.fieldStats[dbName] == nil {
		f.fieldStats[dbName] = make(map[string]map[string]int64)
	}
	if f.fieldStats[dbName][block] == nil {
		f.fieldStats[dbName][block] = make(map[string]int64)
	}
}

func (f *FlexColumnEngine) addIndexLocked(dbName, block, field, val, id string) {
	fieldMap := f.index[dbName][block]
	if fieldMap[field] == nil {
		fieldMap[field] = make(map[string]map[string]struct{})
	}
	if fieldMap[field][val] == nil {
		fieldMap[field][val] = make(map[string]struct{})
	}
	fieldMap[field][val][id] = struct{}{}
}

func (f *FlexColumnEngine) removeDocIndexLocked(dbName, block, id string) {
	blockDocs, ok := f.docFields[dbName][block]
	if !ok {
		return
	}
	fields, ok := blockDocs[id]
	if !ok {
		return
	}
	fieldMap := f.index[dbName][block]
	for field, val := range fields {
		if vals, ok := fieldMap[field]; ok {
			if ids, ok := vals[val]; ok {
				delete(ids, id)
				if len(ids) == 0 {
					delete(vals, val)
				}
			}
		}
	}
	delete(blockDocs, id)
}

// InsertWithColumnar indexes the scalar fields of a newly inserted document.
func (f *FlexColumnEngine) InsertWithColumnar(dbName, block string, doc *Document) {
	if f == nil || f.config == nil || !f.config.Enabled || doc == nil {
		return
	}
	fields := f.indexableFields(doc.Data)
	if len(fields) == 0 {
		return
	}
	f.mu.Lock()
	defer f.mu.Unlock()
	f.ensureMapsLocked(dbName, block)

	stored := make(map[string]string, len(fields))
	for _, field := range fields {
		val := fmt.Sprint(doc.Data[field])
		f.addIndexLocked(dbName, block, field, val, doc.ID)
		stored[field] = val
		f.fieldStats[dbName][block][field]++
	}
	f.docFields[dbName][block][doc.ID] = stored
}

// UpdateWithColumnar re-indexes a document after an update by removing its
// previous index entries and inserting fresh ones based on the new data.
func (f *FlexColumnEngine) UpdateWithColumnar(dbName, block string, oldDoc, newDoc *Document) {
	if f == nil || f.config == nil || !f.config.Enabled || newDoc == nil {
		return
	}
	if oldDoc != nil {
		f.mu.Lock()
		f.ensureMapsLocked(dbName, block)
		f.removeDocIndexLocked(dbName, block, oldDoc.ID)
		f.mu.Unlock()
	}
	f.InsertWithColumnar(dbName, block, newDoc)
}

// DeleteWithColumnar removes a document's entries from the columnar index.
func (f *FlexColumnEngine) DeleteWithColumnar(dbName, block, id string) {
	if f == nil || f.config == nil || !f.config.Enabled {
		return
	}
	f.mu.Lock()
	defer f.mu.Unlock()
	if f.docFields[dbName] == nil || f.docFields[dbName][block] == nil {
		return
	}
	f.removeDocIndexLocked(dbName, block, id)
}

// QueryWithColumnar attempts to accelerate a single-field equality query
// using the in-memory columnar index. It returns (nil, nil) whenever it
// cannot help, signaling the caller to fall back to the normal scan/index
// path in engine.Find.
func (f *FlexColumnEngine) QueryWithColumnar(dbName, block string, q *Query) (*QueryResult, error) {
	if f == nil || f.config == nil || !f.config.Enabled || q == nil {
		return nil, nil
	}
	if len(q.Filters) != 1 {
		return nil, nil
	}
	filter := q.Filters[0]
	if filter.Op != "=" && filter.Op != "==" {
		return nil, nil
	}

	start := time.Now()

	f.mu.RLock()
	blockIndex, ok := f.index[dbName][block]
	if !ok {
		f.mu.RUnlock()
		return nil, nil
	}
	valsIdx, ok := blockIndex[filter.Field]
	if !ok {
		f.mu.RUnlock()
		return nil, nil
	}
	valKey := fmt.Sprint(filter.Value)
	idSet := valsIdx[valKey]
	ids := make([]string, 0, len(idSet))
	for id := range idSet {
		ids = append(ids, id)
	}
	f.mu.RUnlock()

	f.queries.Add(1)
	f.hits.Add(1)

	docs := make([]Document, 0, len(ids))
	for _, id := range ids {
		if doc, ok := f.engine.FindByID(dbName, block, id); ok {
			docs = append(docs, *doc)
		}
	}

	if len(q.Sort) > 0 {
		sortDocs(docs, q.Sort)
	}

	total := int64(len(docs))

	offset := q.Offset
	if offset < 0 {
		offset = 0
	}
	if offset > len(docs) {
		offset = len(docs)
	}
	docs = docs[offset:]
	if q.Limit > 0 && q.Limit < len(docs) {
		docs = docs[:q.Limit]
	}

	if len(q.Select) > 0 || len(q.Exclude) > 0 {
		for i := range docs {
			docs[i].Data = project(docs[i].Data, q.Select, q.Exclude)
		}
	}

	return &QueryResult{
		Docs:      docs,
		Total:     total,
		Scanned:   int64(len(ids)),
		IndexUsed: "flex-column:" + filter.Field,
		Took:      time.Since(start),
	}, nil
}

// HotFields reports write counts per indexed field, used by FLEX HOT.
// If block is empty, it aggregates across every block in the database.
func (f *FlexColumnEngine) HotFields(dbName, block string) map[string]int64 {
	if f == nil {
		return nil
	}
	f.mu.RLock()
	defer f.mu.RUnlock()

	result := make(map[string]int64)
	if block != "" {
		for field, count := range f.fieldStats[dbName][block] {
			result[field] = count
		}
		return result
	}
	for blk, stats := range f.fieldStats[dbName] {
		for field, count := range stats {
			result[blk+"."+field] = count
		}
	}
	return result
}

// Stats returns a snapshot of the FLEX-COLUMN engine for STATUS/HEALTH/FLEX STATS.
func (f *FlexColumnEngine) Stats() map[string]any {
	if f == nil {
		return map[string]any{"enabled": false}
	}
	f.mu.RLock()
	defer f.mu.RUnlock()

	indexedBlocks := 0
	indexedFields := 0
	indexedDocs := 0
	for _, blocks := range f.index {
		for _, fields := range blocks {
			indexedBlocks++
			indexedFields += len(fields)
		}
	}
	for _, blocks := range f.docFields {
		for _, docs := range blocks {
			indexedDocs += len(docs)
		}
	}

	return map[string]any{
		"enabled":              f.config.Enabled,
		"columnar_index":       f.config.ColumnarIndexEnabled,
		"materialized_views":   f.config.MaterializedViews,
		"columnar_compression": f.config.ColumnarCompression,
		"max_columnar_fields":  f.config.MaxColumnarFields,
		"indexed_blocks":       indexedBlocks,
		"indexed_fields":       indexedFields,
		"indexed_documents":    indexedDocs,
		"queries":              f.queries.Load(),
		"hits":                 f.hits.Load(),
	}
}

func generateRandomPassword() string {
	const charset = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*()"
	buf := make([]byte, 24)
	if _, err := rand.Read(buf); err != nil {
		log().Fatal("Failed to generate secure random password (crypto/rand failed)",
			zap.Error(err))
	}
	for i := range buf {
		buf[i] = charset[int(buf[i])%len(charset)]
	}
	return string(buf)
}
