// Code generated by splitting main.go. Part of package main.
package novodb

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/prometheus/client_golang/prometheus/promhttp"
	"go.uber.org/zap"
	"net/http"
	"strings"
	"time"
)

type AdminServer struct {
	engine   *Engine
	config   *Config
	mux      *http.ServeMux
	server   *http.Server
	tokenMgr *TokenManager
}

func NewAdminServer(engine *Engine, config *Config) *AdminServer {
	as := &AdminServer{
		engine:   engine,
		config:   config,
		mux:      http.NewServeMux(),
		tokenMgr: engine.tokenManager,
	}

	as.mux.HandleFunc("/api/v1/health", as.handleHealth)
	as.mux.HandleFunc("/api/v1/status", as.handleStatus)
	as.mux.HandleFunc("/api/v1/dbs", as.handleDatabases)
	as.mux.HandleFunc("/api/v1/db/", as.handleDB)
	as.mux.HandleFunc("/api/v1/query", as.handleQuery)
	as.mux.HandleFunc("/api/v1/backup", as.handleBackup)
	as.mux.HandleFunc("/api/v1/restore", as.handleRestore)
	as.mux.HandleFunc("/api/v1/compact", as.handleCompact)
	as.mux.HandleFunc("/api/v1/users", as.handleUsers)
	as.mux.HandleFunc("/api/v1/auth/login", as.handleLogin)
	as.mux.HandleFunc("/api/v1/auth/logout", as.handleLogout)
	as.mux.HandleFunc("/api/v1/token", as.handleToken)
	as.mux.HandleFunc("/api/v1/metrics", promhttp.Handler().ServeHTTP)

	return as
}

func (as *AdminServer) auth(r *http.Request) (*TokenClaims, bool) {
	user, pass, ok := r.BasicAuth()
	if ok {
		if ok, _ := as.engine.AuthUser(user, pass); ok {
			return &TokenClaims{Username: user, Role: "admin"}, true
		}
	}

	token := r.Header.Get("Authorization")
	if strings.HasPrefix(token, "Bearer ") {
		token = strings.TrimPrefix(token, "Bearer ")
		if claims, err := as.tokenMgr.ValidateToken(token); err == nil {
			return claims, true
		}
	}

	return nil, false
}

func (as *AdminServer) handleToken(w http.ResponseWriter, r *http.Request) {
	if r.Method != "POST" {
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
		return
	}

	user, pass, ok := r.BasicAuth()
	if !ok {
		http.Error(w, "Unauthorized - Basic Auth required", http.StatusUnauthorized)
		return
	}

	if ok, _ := as.engine.AuthUser(user, pass); !ok {
		http.Error(w, "Invalid credentials", http.StatusUnauthorized)
		return
	}

	var role string
	users, _ := as.engine.ShowUsers()
	for _, u := range users {
		if u["username"] == user {
			if r, ok := u["role"].(string); ok {
				role = r
			}
			break
		}
	}
	if role == "" {
		role = "readwrite"
	}

	token, err := as.tokenMgr.GenerateToken(user, user, role)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(map[string]any{
		"token":   token,
		"user":    user,
		"role":    role,
		"expires": time.Now().Add(as.config.TokenExpiry).Unix(),
	})
}

func (as *AdminServer) handleHealth(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(map[string]any{
		"status":     "ok",
		"version":    Version,
		"uptime":     time.Since(startTimeGlobal).String(),
		"max_nodes":  as.config.MaxClusterNodes,
		"max_shards": as.config.MaxShardsPerNode,
	})
}

func (as *AdminServer) handleStatus(w http.ResponseWriter, r *http.Request) {
	claims, ok := as.auth(r)
	if !ok {
		http.Error(w, "Unauthorized", http.StatusUnauthorized)
		return
	}

	dbs, _ := as.engine.ShowDBs()
	status := map[string]any{
		"version":    Version,
		"node_id":    as.engine.nodeID,
		"databases":  len(dbs),
		"shards":     as.engine.shardMgr.shardCount,
		"replicas":   as.engine.shardMgr.replicaCount,
		"ops":        as.engine.opCount.Load(),
		"memory":     getMemStats(),
		"l1_cache":   as.engine.l1Cache.stats(),
		"metrics":    as.engine.metrics.Stats(),
		"uptime":     time.Since(as.engine.startupTime).Seconds(),
		"user":       claims.Username,
		"role":       claims.Role,
		"max_shards": as.config.MaxShardsPerNode,
		"max_nodes":  as.config.MaxClusterNodes,
		"flex_stats": as.engine.flexEngine.Stats(),
	}

	if as.engine.cluster != nil {
		status["cluster"] = map[string]any{
			"role":   as.engine.cluster.raft.State().String(),
			"leader": string(as.engine.cluster.raft.Leader()),
			"peers":  as.engine.cluster.GetPeers(),
		}
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(status)
}

func (as *AdminServer) handleDatabases(w http.ResponseWriter, r *http.Request) {
	if _, ok := as.auth(r); !ok {
		http.Error(w, "Unauthorized", http.StatusUnauthorized)
		return
	}

	switch r.Method {
	case "GET":
		dbs, err := as.engine.ShowDBs()
		if err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(dbs)

	case "POST":
		var req struct {
			Name string `json:"name"`
		}
		if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
			http.Error(w, err.Error(), http.StatusBadRequest)
			return
		}
		if err := as.engine.CreateDB(req.Name); err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
		w.WriteHeader(http.StatusCreated)
		json.NewEncoder(w).Encode(map[string]string{"status": "created", "name": req.Name})

	default:
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
	}
}

func (as *AdminServer) handleDB(w http.ResponseWriter, r *http.Request) {
	if _, ok := as.auth(r); !ok {
		http.Error(w, "Unauthorized", http.StatusUnauthorized)
		return
	}

	path := strings.TrimPrefix(r.URL.Path, "/api/v1/db/")
	parts := strings.Split(path, "/")
	if len(parts) == 0 || parts[0] == "" {
		http.Error(w, "Database name required", http.StatusBadRequest)
		return
	}
	dbName := parts[0]

	switch r.Method {
	case "GET":
		info, err := as.engine.DescribeDB(dbName)
		if err != nil {
			http.Error(w, err.Error(), http.StatusNotFound)
			return
		}
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(info)

	case "DELETE":
		if err := as.engine.DropDB(dbName); err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(map[string]string{"status": "deleted"})

	default:
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
	}
}

func (as *AdminServer) handleQuery(w http.ResponseWriter, r *http.Request) {
	claims, ok := as.auth(r)
	if !ok {
		http.Error(w, "Unauthorized", http.StatusUnauthorized)
		return
	}

	if r.Method != "POST" {
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
		return
	}

	var req struct {
		Query string `json:"query"`
		DB    string `json:"db"`
	}
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	sess := &Session{
		currentDB: req.DB,
		authUser:  claims.Username,
		authRole:  claims.Role,
		token:     r.Header.Get("Authorization"),
	}

	result := parseAndExec(as.engine, sess, req.Query)

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(map[string]any{
		"success": result != "ERROR",
		"result":  result,
		"db":      req.DB,
	})
}

func (as *AdminServer) handleBackup(w http.ResponseWriter, r *http.Request) {
	if _, ok := as.auth(r); !ok {
		http.Error(w, "Unauthorized", http.StatusUnauthorized)
		return
	}

	if r.Method != "POST" {
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
		return
	}

	var req struct {
		DB   string `json:"db"`
		File string `json:"file"`
	}
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	if err := as.engine.Backup(req.DB, req.File); err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(map[string]string{"status": "backup complete"})
}

func (as *AdminServer) handleRestore(w http.ResponseWriter, r *http.Request) {
	if _, ok := as.auth(r); !ok {
		http.Error(w, "Unauthorized", http.StatusUnauthorized)
		return
	}

	if r.Method != "POST" {
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
		return
	}

	var req struct {
		DB   string `json:"db"`
		File string `json:"file"`
	}
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	if err := as.engine.Restore(req.DB, req.File); err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(map[string]string{"status": "restore complete"})
}

func (as *AdminServer) handleCompact(w http.ResponseWriter, r *http.Request) {
	if _, ok := as.auth(r); !ok {
		http.Error(w, "Unauthorized", http.StatusUnauthorized)
		return
	}

	if r.Method != "POST" {
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
		return
	}

	var req struct {
		DB string `json:"db"`
	}
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	rounds, err := as.engine.Compact(req.DB)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(map[string]any{
		"status": "compact complete",
		"rounds": rounds,
	})
}

func (as *AdminServer) handleUsers(w http.ResponseWriter, r *http.Request) {
	if _, ok := as.auth(r); !ok {
		http.Error(w, "Unauthorized", http.StatusUnauthorized)
		return
	}

	switch r.Method {
	case "GET":
		users, err := as.engine.ShowUsers()
		if err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(users)

	case "POST":
		var req struct {
			Username string `json:"username"`
			Password string `json:"password"`
			Role     string `json:"role"`
		}
		if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
			http.Error(w, err.Error(), http.StatusBadRequest)
			return
		}
		if err := as.engine.CreateUser(req.Username, req.Password, req.Role); err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
		w.WriteHeader(http.StatusCreated)
		json.NewEncoder(w).Encode(map[string]string{"status": "created"})

	default:
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
	}
}

func (as *AdminServer) handleLogin(w http.ResponseWriter, r *http.Request) {
	if r.Method != "POST" {
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
		return
	}

	var req struct {
		Username string `json:"username"`
		Password string `json:"password"`
	}
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	ok, role := as.engine.AuthUser(req.Username, req.Password)
	if !ok {
		http.Error(w, "Invalid credentials", http.StatusUnauthorized)
		return
	}

	token, err := as.tokenMgr.GenerateToken(req.Username, req.Username, role)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(map[string]any{
		"token":   token,
		"user":    req.Username,
		"role":    role,
		"expires": time.Now().Add(as.config.TokenExpiry).Unix(),
	})
}

func (as *AdminServer) handleLogout(w http.ResponseWriter, r *http.Request) {
	if r.Method != "POST" {
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
		return
	}

	token := r.Header.Get("Authorization")
	if strings.HasPrefix(token, "Bearer ") {
		token = strings.TrimPrefix(token, "Bearer ")
		as.tokenMgr.RevokeToken(token)
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(map[string]string{"status": "logged out"})
}

func (as *AdminServer) Start() {
	addr := fmt.Sprintf(":%d", as.config.AdminPort)
	as.server = &http.Server{
		Addr:         addr,
		Handler:      as.mux,
		ReadTimeout:  30 * time.Second,
		WriteTimeout: 30 * time.Second,
		IdleTimeout:  60 * time.Second,
	}

	go func() {
		log().Info("Admin server started", zap.Int("port", as.config.AdminPort))
		if as.config.TLSEnabled {
			if err := as.server.ListenAndServeTLS(as.config.TLSCertFile, as.config.TLSKeyFile); err != nil && err != http.ErrServerClosed {
				log().Error("Admin server failed", zap.Error(err))
			}
		} else {
			if err := as.server.ListenAndServe(); err != nil && err != http.ErrServerClosed {
				log().Error("Admin server failed", zap.Error(err))
			}
		}
	}()
}

func (as *AdminServer) Stop() {
	if as.server != nil {
		ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
		defer cancel()
		as.server.Shutdown(ctx)
	}
}
