// Code generated by splitting main.go. Part of package main.
package novodb

import (
	"context"
	"encoding/json"
	"fmt"
	"go.uber.org/zap"
	"net/http"
	"strings"
	"time"
)

type QueryServer struct {
	engine   *Engine
	config   *Config
	mux      *http.ServeMux
	server   *http.Server
	tokenMgr *TokenManager
}

func NewQueryServer(engine *Engine, config *Config) *QueryServer {
	qs := &QueryServer{
		engine:   engine,
		config:   config,
		mux:      http.NewServeMux(),
		tokenMgr: engine.tokenManager,
	}

	qs.mux.HandleFunc("/query", qs.handleQuery)
	qs.mux.HandleFunc("/status", qs.handleStatus)
	qs.mux.HandleFunc("/health", qs.handleHealth)

	return qs
}

func (qs *QueryServer) auth(r *http.Request) bool {
	user, pass, ok := r.BasicAuth()
	if ok {
		if ok, _ := qs.engine.AuthUser(user, pass); ok {
			return true
		}
	}

	token := r.Header.Get("Authorization")
	if strings.HasPrefix(token, "Bearer ") {
		token = strings.TrimPrefix(token, "Bearer ")
		if claims, err := qs.tokenMgr.ValidateToken(token); err == nil {
			ctx := context.WithValue(r.Context(), "user", claims.Username)
			ctx = context.WithValue(ctx, "role", claims.Role)
			*r = *r.WithContext(ctx)
			return true
		}
	}

	return false
}

func (qs *QueryServer) handleQuery(w http.ResponseWriter, r *http.Request) {
	if !qs.auth(r) {
		http.Error(w, "Unauthorized", http.StatusUnauthorized)
		return
	}

	query := r.URL.Query().Get("query")
	if query == "" {
		http.Error(w, "Missing 'query' parameter", http.StatusBadRequest)
		return
	}

	db := r.URL.Query().Get("db")
	if db == "" {
		db = "default"
	}

	sess := &Session{currentDB: db}

	result := parseAndExec(qs.engine, sess, query)

	if result == "__EXIT__" {
		result = "Connection closed"
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(map[string]any{
		"success": true,
		"result":  result,
		"db":      db,
	})
}

func (qs *QueryServer) handleStatus(w http.ResponseWriter, r *http.Request) {
	if !qs.auth(r) {
		http.Error(w, "Unauthorized", http.StatusUnauthorized)
		return
	}

	dbs, _ := qs.engine.ShowDBs()
	shards := qs.engine.shardMgr.GetAllShards()

	status := map[string]any{
		"version":              Version,
		"node_id":              qs.engine.nodeID,
		"databases":            len(dbs),
		"shards":               len(shards),
		"shard_count":          qs.engine.shardMgr.shardCount,
		"ops":                  qs.engine.opCount.Load(),
		"memory":               getMemStats(),
		"l1_cache":             qs.engine.l1Cache.stats(),
		"metrics":              qs.engine.metrics.Stats(),
		"max_shards_per_node":  qs.engine.config.MaxShardsPerNode,
		"max_cluster_nodes":    qs.engine.config.MaxClusterNodes,
		"auto_scaling_enabled": qs.engine.config.AutoCluster,
		"predictive_scaling":   qs.engine.config.PredictiveScaling,
		"fast_startup":         qs.engine.config.FastStartup,
		"lazy_index_loading":   qs.engine.config.LazyIndexLoading,
		"compress_large_docs":  qs.engine.config.CompressLargeDocs,
		"max_document_size":    qs.engine.config.MaxDocumentSize,
		"startup_duration":     time.Since(qs.engine.startupTime).Seconds(),
		"flex_stats":           qs.engine.flexEngine.Stats(),
	}

	if qs.engine.cluster != nil {
		status["cluster"] = map[string]any{
			"role":        qs.engine.cluster.raft.State().String(),
			"leader":      string(qs.engine.cluster.raft.Leader()),
			"peers":       qs.engine.cluster.GetPeers(),
			"total_nodes": len(qs.engine.cluster.GetPeers()) + 1,
			"max_nodes":   qs.engine.config.MaxClusterNodes,
		}
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(status)
}

func (qs *QueryServer) handleHealth(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(map[string]any{
		"status":              "ok",
		"version":             Version,
		"uptime":              time.Since(startTimeGlobal).String(),
		"unlimited_mode":      true,
		"max_nodes":           qs.engine.config.MaxClusterNodes,
		"max_shards":          qs.engine.config.MaxShardsPerNode,
		"fast_startup":        qs.engine.config.FastStartup,
		"lazy_index_loading":  qs.engine.config.LazyIndexLoading,
		"compress_large_docs": qs.engine.config.CompressLargeDocs,
		"max_document_size":   qs.engine.config.MaxDocumentSize,
		"startup_duration":    time.Since(qs.engine.startupTime).Seconds(),
	})
}

func (qs *QueryServer) Start() {
	addr := fmt.Sprintf(":%d", qs.config.QueryPort)
	qs.server = &http.Server{
		Addr:         addr,
		Handler:      qs.mux,
		ReadTimeout:  30 * time.Second,
		WriteTimeout: 30 * time.Second,
		IdleTimeout:  60 * time.Second,
	}

	go func() {
		log().Info("HTTP Query Server started",
			zap.Int("port", qs.config.QueryPort),
			zap.String("user", qs.config.QueryUser),
			zap.Int64("max_doc_size", qs.config.MaxDocumentSize))

		if qs.config.TLSEnabled {
			if err := qs.server.ListenAndServeTLS(qs.config.TLSCertFile, qs.config.TLSKeyFile); err != nil && err != http.ErrServerClosed {
				log().Error("Query server failed", zap.Error(err))
			}
		} else {
			if err := qs.server.ListenAndServe(); err != nil && err != http.ErrServerClosed {
				log().Error("Query server failed", zap.Error(err))
			}
		}
	}()
}

func (qs *QueryServer) Stop() {
	if qs.server != nil {
		ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
		defer cancel()
		qs.server.Shutdown(ctx)
	}
}
