// Code generated by splitting main.go. Part of package main.
package novodb

import (
	"fmt"
	badger "github.com/dgraph-io/badger/v4"
	"go.uber.org/zap"
	"strings"
)

func (e *Engine) buildSecondaryIndex(dbName, block string, doc *Document) error {
	db, err := e.pool.openBlock(dbName, block)
	if err != nil {
		return err
	}

	for field, value := range doc.Data {
		if !shouldIndexField(e.config, field, value) {
			continue
		}

		switch v := value.(type) {
		case string, float64, int, int64, bool:
			strVal := fmt.Sprint(v)
			key := secondaryIndexKey(block, field, strVal, doc.ID)
			if err := txHelper.SafeUpdate(db, func(txn *badger.Txn) error {
				return txn.Set(key, []byte{})
			}); err != nil {
				log().Error("Failed to build index",
					zap.String("block", block),
					zap.String("field", field),
					zap.Error(err))
			}
		}
	}
	return nil
}

func (e *Engine) dropSecondaryIndex(dbName, block string, doc *Document) error {
	db, err := e.pool.openBlock(dbName, block)
	if err != nil {
		return err
	}

	for field, value := range doc.Data {
		if !shouldIndexField(e.config, field, value) {
			continue
		}
		switch v := value.(type) {
		case string, float64, int, int64, bool:
			strVal := fmt.Sprint(v)
			key := secondaryIndexKey(block, field, strVal, doc.ID)
			if err := txHelper.SafeUpdate(db, func(txn *badger.Txn) error {
				return txn.Delete(key)
			}); err != nil {
				log().Error("Failed to drop index",
					zap.String("block", block),
					zap.String("field", field),
					zap.Error(err))
			}
		}
	}
	return nil
}

func (e *Engine) lookupByIndex(dbName, block, field, value string, page int, pageSize int) (*IndexResult, error) {
	if cached, ok := e.l2Cache.get(block, field, value); ok {
		start := page * pageSize
		end := start + pageSize
		if start >= len(cached.DocIDs) {
			return &IndexResult{
				DocIDs:  []string{},
				Total:   cached.Total,
				HasMore: false,
			}, nil
		}
		if end > len(cached.DocIDs) {
			end = len(cached.DocIDs)
		}
		return &IndexResult{
			DocIDs:  cached.DocIDs[start:end],
			Total:   cached.Total,
			HasMore: end < len(cached.DocIDs),
		}, nil
	}

	if e.config.LazyIndexLoading {
		e.l2Cache.set(block, field, value, []string{}, 0, false, "")
	}

	db, err := e.pool.openBlock(dbName, block)
	if err != nil {
		return nil, err
	}

	var docIDs []string
	prefix := secondaryIndexPrefix(block, field, value)

	err = txHelper.SafeView(db, func(txn *badger.Txn) error {
		opts := badger.DefaultIteratorOptions
		opts.PrefetchValues = false
		it := txn.NewIterator(opts)
		defer it.Close()

		for it.Seek(prefix); it.ValidForPrefix(prefix); it.Next() {
			key := string(it.Item().KeyCopy(nil))
			parts := strings.Split(key, "/")
			if len(parts) >= 5 {
				docIDs = append(docIDs, parts[4])
			}
		}
		return nil
	})

	if err != nil {
		return nil, err
	}

	total := int64(len(docIDs))
	hasMore := false
	if pageSize > 0 {
		start := page * pageSize
		end := start + pageSize
		if start < len(docIDs) {
			if end > len(docIDs) {
				end = len(docIDs)
			}
			hasMore = end < len(docIDs)
			docIDs = docIDs[start:end]
		} else {
			docIDs = []string{}
		}
	}

	result := &IndexResult{
		DocIDs:  docIDs,
		Total:   total,
		HasMore: hasMore,
	}

	if total <= 5000000 {
		e.l2Cache.set(block, field, value, docIDs, total, hasMore, "")
	}

	return result, nil
}

func shouldIndexField(config *Config, field string, value any) bool {
	if config.SkipLargeIndexes {
		switch v := value.(type) {
		case string:
			if int64(len(v)) > config.IndexSkipThreshold {
				return false
			}
		case map[string]any:
			if estimateSize(v) > config.IndexSkipThreshold {
				return false
			}
		case []any:
			if estimateArraySize(v) > config.IndexSkipThreshold {
				return false
			}
		}
	}
	return true
}

func estimateSize(v any) int64 {
	switch val := v.(type) {
	case string:
		return int64(len(val))
	case map[string]any:
		var size int64
		for k, subv := range val {
			size += int64(len(k)) + estimateSize(subv)
		}
		return size
	case []any:
		return estimateArraySize(val)
	default:
		return int64(len(fmt.Sprint(v)))
	}
}

func estimateArraySize(arr []any) int64 {
	var size int64
	for _, v := range arr {
		size += estimateSize(v)
	}
	return size
}
