// Code generated by splitting main.go. Part of package main.
package novodb

import (
	"github.com/prometheus/client_golang/prometheus"
	"sync"
)

var (
	metricOpsTotal = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "novodb_operations_total",
			Help: "Total number of operations",
		},
		[]string{"type", "db", "block", "shard", "node", "status"},
	)

	metricOpsDuration = prometheus.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "novodb_operation_duration_seconds",
			Help:    "Duration of operations",
			Buckets: prometheus.ExponentialBuckets(0.001, 2, 20),
		},
		[]string{"type", "db", "block", "shard", "node"},
	)

	metricCacheHits = prometheus.NewCounter(
		prometheus.CounterOpts{
			Name: "novodb_cache_hits_total",
			Help: "Total cache hits",
		},
	)

	metricCacheMisses = prometheus.NewCounter(
		prometheus.CounterOpts{
			Name: "novodb_cache_misses_total",
			Help: "Total cache misses",
		},
	)

	metricActiveQueries = prometheus.NewGauge(
		prometheus.GaugeOpts{
			Name: "novodb_active_queries",
			Help: "Number of active queries",
		},
	)

	metricIndexSize = prometheus.NewGaugeVec(
		prometheus.GaugeOpts{
			Name: "novodb_index_size_bytes",
			Help: "Size of secondary indexes",
		},
		[]string{"db", "block", "field", "shard", "node"},
	)

	metricDocumentsTotal = prometheus.NewGaugeVec(
		prometheus.GaugeOpts{
			Name: "novodb_documents_total",
			Help: "Total number of documents",
		},
		[]string{"db", "block", "shard", "node"},
	)

	metricShardDistribution = prometheus.NewGaugeVec(
		prometheus.GaugeOpts{
			Name: "novodb_shard_distribution",
			Help: "Distribution of documents across shards",
		},
		[]string{"db", "block", "shard", "node"},
	)

	metricClusterStatus = prometheus.NewGaugeVec(
		prometheus.GaugeOpts{
			Name: "novodb_cluster_status",
			Help: "Cluster node status",
		},
		[]string{"node", "role"},
	)

	metricRaftCommits = prometheus.NewCounter(
		prometheus.CounterOpts{
			Name: "novodb_raft_commits_total",
			Help: "Total Raft commits",
		},
	)

	metricAutoScaleEvents = prometheus.NewCounter(
		prometheus.CounterOpts{
			Name: "novodb_autoscale_events_total",
			Help: "Total auto-scale events",
		},
	)

	metricWALWrites = prometheus.NewCounter(
		prometheus.CounterOpts{
			Name: "novodb_wal_writes_total",
			Help: "Total WAL writes",
		},
	)

	metricCompactions = prometheus.NewCounter(
		prometheus.CounterOpts{
			Name: "novodb_compactions_total",
			Help: "Total compactions performed",
		},
	)

	metricTransactionCommits = prometheus.NewCounter(
		prometheus.CounterOpts{
			Name: "novodb_transaction_commits_total",
			Help: "Total transaction commits",
		},
	)

	metricTransactionRollbacks = prometheus.NewCounter(
		prometheus.CounterOpts{
			Name: "novodb_transaction_rollbacks_total",
			Help: "Total transaction rollbacks",
		},
	)

	metricStartupTime = prometheus.NewGauge(
		prometheus.GaugeOpts{
			Name: "novodb_startup_duration_seconds",
			Help: "Time taken to start up",
		},
	)

	metricDocSize = prometheus.NewHistogram(
		prometheus.HistogramOpts{
			Name:    "novodb_document_size_bytes",
			Help:    "Size of documents inserted",
			Buckets: []float64{1024, 10240, 102400, 1048576, 5242880, 10485760, 52428800},
		},
	)

	metricQueryLatency = prometheus.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "novodb_query_latency_seconds",
			Help:    "Query latency",
			Buckets: prometheus.ExponentialBuckets(0.001, 2, 15),
		},
		[]string{"db", "block", "type"},
	)

	metricMemoryUsage = prometheus.NewGauge(
		prometheus.GaugeOpts{
			Name: "novodb_memory_usage_bytes",
			Help: "Memory usage in bytes",
		},
	)

	metricDiskUsage = prometheus.NewGaugeVec(
		prometheus.GaugeOpts{
			Name: "novodb_disk_usage_bytes",
			Help: "Disk usage in bytes",
		},
		[]string{"db", "type"},
	)

	metricAuthFailures = prometheus.NewCounter(
		prometheus.CounterOpts{
			Name: "novodb_auth_failures_total",
			Help: "Total authentication failures",
		},
	)

	metricWALSize = prometheus.NewGauge(
		prometheus.GaugeOpts{
			Name: "novodb_wal_size_bytes",
			Help: "WAL size in bytes",
		},
	)

	metricRiskBlocks = prometheus.NewCounter(
		prometheus.CounterOpts{
			Name: "novodb_risk_blocks_total",
			Help: "Total operations blocked by risk engine",
		},
	)

	metricsOnce sync.Once
)

func initMetrics() {
	metricsOnce.Do(func() {
		prometheus.MustRegister(
			metricOpsTotal,
			metricOpsDuration,
			metricCacheHits,
			metricCacheMisses,
			metricActiveQueries,
			metricIndexSize,
			metricDocumentsTotal,
			metricShardDistribution,
			metricClusterStatus,
			metricRaftCommits,
			metricAutoScaleEvents,
			metricWALWrites,
			metricCompactions,
			metricTransactionCommits,
			metricTransactionRollbacks,
			metricStartupTime,
			metricDocSize,
			metricQueryLatency,
			metricMemoryUsage,
			metricDiskUsage,
			metricAuthFailures,
			metricWALSize,
			metricRiskBlocks,
		)
	})
}
