// Code generated by splitting main.go. Part of package main.
package novodb

import (
	"encoding/json"
	"fmt"
	"strconv"
	"strings"
)

func getNested(data map[string]any, path string) any {
	parts := strings.SplitN(path, ".", 2)
	v, ok := data[parts[0]]
	if !ok {
		return nil
	}
	if len(parts) == 1 {
		return v
	}
	sub, ok := v.(map[string]any)
	if !ok {
		return nil
	}
	return getNested(sub, parts[1])
}

func setNested(data map[string]any, path string, value any) {
	parts := strings.SplitN(path, ".", 2)
	if len(parts) == 1 {
		data[parts[0]] = value
		return
	}
	sub, ok := data[parts[0]].(map[string]any)
	if !ok {
		sub = make(map[string]any)
		data[parts[0]] = sub
	}
	setNested(sub, parts[1], value)
}

func getNestedF64(data map[string]any, path string) float64 { return toF64(getNested(data, path)) }

func getNestedArr(data map[string]any, path string) []any {
	if arr, ok := getNested(data, path).([]any); ok {
		return arr
	}
	return nil
}

func project(data map[string]any, include, exclude []string) map[string]any {
	out := make(map[string]any, len(data))
	if len(include) > 0 {
		for _, f := range include {
			out[f] = getNested(data, f)
		}
		return out
	}
	for k, v := range data {
		out[k] = v
	}
	for _, f := range exclude {
		delete(out, f)
	}
	return out
}

func toF64(v any) float64 {
	switch val := v.(type) {
	case float64:
		return val
	case float32:
		return float64(val)
	case int:
		return float64(val)
	case int64:
		return float64(val)
	case json.Number:
		f, _ := val.Float64()
		return f
	case string:
		f, _ := strconv.ParseFloat(val, 64)
		return f
	}
	f, _ := strconv.ParseFloat(fmt.Sprint(v), 64)
	return f
}
