// Code generated by splitting main.go. Part of package main.
package novodb

import (
	"encoding/json"
	"fmt"
	badger "github.com/dgraph-io/badger/v4"
	"math"
	"sort"
	"strings"
)

func (e *Engine) Aggregate(dbName, block, op, field string, filters []Filter) (float64, error) {
	if !e.dirMgr.BlockExists(dbName, block) {
		return 0, ErrBlockNotFound
	}

	db, err := e.pool.openBlock(dbName, block)
	if err != nil {
		return 0, err
	}

	prefix := docKeyPrefix(block)
	var (
		sum   float64
		count int64
		min_v = math.MaxFloat64
		max_v = -math.MaxFloat64
	)

	err = txHelper.SafeView(db, func(txn *badger.Txn) error {
		opts := badger.DefaultIteratorOptions
		opts.PrefetchValues = true
		it := txn.NewIterator(opts)
		defer it.Close()
		for it.Seek(prefix); it.ValidForPrefix(prefix); it.Next() {
			item := it.Item()
			if item == nil {
				continue
			}
			var doc Document
			if err := item.Value(func(v []byte) error { return json.Unmarshal(v, &doc) }); err != nil {
				continue
			}
			if !matchesFilters(doc, filters) {
				continue
			}
			v := getNestedF64(doc.Data, field)
			sum += v
			count++
			if v < min_v {
				min_v = v
			}
			if v > max_v {
				max_v = v
			}
		}
		return nil
	})

	if err != nil {
		return 0, err
	}

	switch strings.ToUpper(op) {
	case "SUM":
		return sum, nil
	case "AVG":
		if count == 0 {
			return 0, nil
		}
		return sum / float64(count), nil
	case "MIN":
		if count == 0 {
			return 0, nil
		}
		return min_v, nil
	case "MAX":
		if count == 0 {
			return 0, nil
		}
		return max_v, nil
	case "COUNT":
		return float64(count), nil
	}
	return 0, fmt.Errorf("unknown aggregation: %s", op)
}

type GroupResult struct {
	Key   string  `json:"key"`
	Count int64   `json:"count,omitempty"`
	Sum   float64 `json:"sum,omitempty"`
	Avg   float64 `json:"avg,omitempty"`
	Min   float64 `json:"min,omitempty"`
	Max   float64 `json:"max,omitempty"`
}

func (e *Engine) Group(dbName, block, byField, aggOp, aggField string, filters []Filter) ([]GroupResult, error) {
	if !e.dirMgr.BlockExists(dbName, block) {
		return nil, ErrBlockNotFound
	}

	db, err := e.pool.openBlock(dbName, block)
	if err != nil {
		return nil, err
	}

	prefix := docKeyPrefix(block)
	type acc struct {
		count int64
		sum   float64
		min   float64
		max   float64
	}
	groups := make(map[string]*acc, 128)

	err = txHelper.SafeView(db, func(txn *badger.Txn) error {
		opts := badger.DefaultIteratorOptions
		opts.PrefetchValues = true
		it := txn.NewIterator(opts)
		defer it.Close()
		for it.Seek(prefix); it.ValidForPrefix(prefix); it.Next() {
			item := it.Item()
			if item == nil {
				continue
			}
			var doc Document
			if err := item.Value(func(v []byte) error { return json.Unmarshal(v, &doc) }); err != nil {
				continue
			}
			if !matchesFilters(doc, filters) {
				continue
			}
			key := fmt.Sprint(getNested(doc.Data, byField))
			if _, ok := groups[key]; !ok {
				groups[key] = &acc{
					min: math.MaxFloat64,
					max: -math.MaxFloat64,
				}
			}
			groups[key].count++
			if aggField != "" {
				v := getNestedF64(doc.Data, aggField)
				groups[key].sum += v
				if v < groups[key].min {
					groups[key].min = v
				}
				if v > groups[key].max {
					groups[key].max = v
				}
			}
		}
		return nil
	})

	if err != nil {
		return nil, err
	}

	out := make([]GroupResult, 0, len(groups))
	for k, a := range groups {
		gr := GroupResult{Key: k, Count: a.count}
		if strings.ToUpper(aggOp) == "SUM" {
			gr.Sum = a.sum
		}
		if strings.ToUpper(aggOp) == "AVG" && a.count > 0 {
			gr.Avg = a.sum / float64(a.count)
		}
		if strings.ToUpper(aggOp) == "MIN" {
			gr.Min = a.min
		}
		if strings.ToUpper(aggOp) == "MAX" {
			gr.Max = a.max
		}
		if strings.ToUpper(aggOp) == "COUNT" {
			gr.Count = a.count
		}
		out = append(out, gr)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Count > out[j].Count })
	return out, nil
}
