// Code generated by splitting main.go. Part of package main.
package novodb

import (
	"go.uber.org/zap"
	"time"
)

func (e *Engine) Compact(dbName string) (int, error) {
	start := time.Now()

	if !e.dirMgr.DBExists(dbName) {
		return 0, ErrDBNotFound
	}

	db, err := e.pool.openDataPath(e.dirMgr.DBPath(dbName))
	if err != nil {
		return 0, err
	}

	rounds := 0
	for {
		err := db.RunValueLogGC(0.5)
		if err != nil {
			break
		}
		rounds++
	}

	log().Info("Compact completed",
		zap.String("db", dbName),
		zap.Int("rounds", rounds),
		zap.Duration("duration", time.Since(start)))

	metricCompactions.Inc()
	return rounds, nil
}
