// Code generated by splitting main.go. Part of package main.
package novodb

import (
	"encoding/json"
	"fmt"
	badger "github.com/dgraph-io/badger/v4"
	"go.uber.org/zap"
	"os"
	"time"
)

func (e *Engine) insertWithIDLocal(dbName, block, id string, data map[string]any, shardID string) (*Document, error) {
	if shardID == "" {
		shardID = e.shardMgr.GetShardForDoc(dbName, block, id)
	}

	if err := e.dirMgr.CreateBlockDirectories(dbName, block); err != nil {
		return nil, err
	}

	db, err := e.pool.openBlock(dbName, block)
	if err != nil {
		return nil, err
	}

	lockKey := dbName + "\x00" + block + "\x00" + shardID
	e.lockManager.Lock(lockKey)
	defer e.lockManager.Unlock(lockKey)

	now := time.Now().Unix()

	if id != "" {
		data["id"] = id
	}

	doc := Document{
		ID:      id,
		Data:    data,
		Meta:    DocMeta{CreatedAt: now, UpdatedAt: now, Version: 1},
		ShardID: shardID,
	}

	raw, err := json.Marshal(doc)
	if err != nil {
		return nil, err
	}

	if int64(len(raw)) > e.config.MaxDocumentSize {
		return nil, fmt.Errorf("%w: %d bytes (max: %d)", ErrDocTooLarge, len(raw), e.config.MaxDocumentSize)
	}

	metricDocSize.Observe(float64(len(raw)))

	if e.externalStore != nil && int64(len(raw)) > e.config.LargeDocThreshold {
		largeID, err := e.externalStore.Save(raw)
		if err != nil {
			return nil, fmt.Errorf("failed to store large document: %w", err)
		}
		doc.LargeID = largeID
		raw, _ = json.Marshal(doc)
	}

	compressedData := raw
	compressed := false
	if e.config.CompressLargeDocs && int64(len(raw)) > e.config.CompressThreshold {
		if comp, ok, err := compressData(raw, CompressionZstd); err == nil && ok {
			compressedData = comp
			compressed = true
		}
	}

	key := docKey(block, id)
	err = txHelper.SafeUpdate(db, func(txn *badger.Txn) error {
		return txn.Set(key, compressedData)
	})
	if err != nil {
		return nil, err
	}

	if e.wal != nil {
		walData := raw
		if compressed {
			walData = compressedData
		}
		if err := e.wal.Write("insert", dbName, block, walData); err != nil {
			log().Warn("WAL write failed", zap.Error(err))
		}
	}

	if int64(len(raw)) < e.config.IndexSkipThreshold {
		if err := e.buildSecondaryIndex(dbName, block, &doc); err != nil {
			log().Warn("Failed to build secondary index", zap.Error(err))
		}
	}

	e.queryOpt.UpdateIndexStats("_id", 0, 0)

	e.l1Cache.set(e.cacheKey(dbName, block, id), raw)
	e.shardMgr.UpdateShardStats(shardID, 1, int64(len(raw)))

	if meta, err := e.dirMgr.LoadBlockMeta(dbName, block); err == nil {
		meta.DocCount++
		meta.SizeBytes += int64(len(raw))
		meta.UpdatedAt = time.Now().Unix()
		e.dirMgr.SaveBlockMeta(dbName, block, meta)
	}

	go e.vmIndex(dbName, block, &doc)
	e.opCount.Add(1)

	// Update FLEX-COLUMN
	if e.flexEngine != nil {
		e.flexEngine.InsertWithColumnar(dbName, block, &doc)
	}

	metricOpsTotal.WithLabelValues("insert", dbName, block, shardID, e.nodeID, "success").Inc()
	metricDocumentsTotal.WithLabelValues(dbName, block, shardID, e.nodeID).Inc()

	if stats, ok := e.intelEngine.stats[dbName]; ok {
		stats.DocCount++
		stats.AvgDocSize = (stats.AvgDocSize*(stats.DocCount-1) + int64(len(raw))) / stats.DocCount
	}

	if e.auditLogger != nil {
		e.auditLogger.Log(AuditLog{
			UserID:   "system",
			Username: "system",
			Action:   "insert",
			DB:       dbName,
			Block:    block,
			DocID:    id,
			ShardID:  shardID,
			Status:   "success",
			Message:  fmt.Sprintf("size=%d compressed=%v", len(raw), compressed),
		})
	}

	return &doc, nil
}

func (e *Engine) updateLocal(dbName, block string, filters []Filter, op UpdateOp, shardID string) (int64, error) {
	start := time.Now()

	db, err := e.pool.openBlock(dbName, block)
	if err != nil {
		return 0, err
	}

	lockKey := dbName + "\x00" + block + "\x00" + shardID
	e.lockManager.Lock(lockKey)
	defer e.lockManager.Unlock(lockKey)

	prefix := docKeyPrefix(block)
	var updated int64
	var sizeDelta int64

	err = txHelper.SafeUpdate(db, func(txn *badger.Txn) error {
		opts := badger.DefaultIteratorOptions
		opts.PrefetchSize = 1000
		it := txn.NewIterator(opts)
		defer it.Close()

		for it.Seek(prefix); it.ValidForPrefix(prefix); it.Next() {
			var raw []byte
			item := it.Item()
			if item == nil {
				continue
			}
			err := item.Value(func(v []byte) error {
				raw = make([]byte, len(v))
				copy(raw, v)
				return nil
			})
			if err != nil {
				continue
			}
			var doc Document
			if err := json.Unmarshal(raw, &doc); err != nil {
				continue
			}
			if doc.ShardID != shardID && shardID != "" {
				continue
			}
			if !matchesFilters(doc, filters) {
				continue
			}

			e.dropSecondaryIndex(dbName, block, &doc)

			applyUpdateOp(&doc, op)
			doc.Meta.UpdatedAt = time.Now().Unix()
			doc.Meta.Version++

			newRaw, err2 := json.Marshal(doc)
			if err2 != nil {
				continue
			}

			if e.externalStore != nil && int64(len(newRaw)) > e.config.LargeDocThreshold {
				largeID, err3 := e.externalStore.Save(newRaw)
				if err3 != nil {
					continue
				}
				doc.LargeID = largeID
				newRaw, _ = json.Marshal(doc)
			}

			if e.config.CompressLargeDocs && int64(len(newRaw)) > e.config.CompressThreshold {
				if comp, ok, err := compressData(newRaw, CompressionZstd); err == nil && ok {
					newRaw = comp
				}
			}

			k := make([]byte, len(item.Key()))
			copy(k, item.Key())
			if err2 = txn.Set(k, newRaw); err2 != nil {
				return err2
			}

			if int64(len(newRaw)) < e.config.IndexSkipThreshold {
				e.buildSecondaryIndex(dbName, block, &doc)
			}

			// Update FLEX-COLUMN
			if e.flexEngine != nil {
				var oldDoc Document
				if err := json.Unmarshal(raw, &oldDoc); err == nil {
					e.flexEngine.UpdateWithColumnar(dbName, block, &oldDoc, &doc)
				} else {
					e.flexEngine.InsertWithColumnar(dbName, block, &doc)
				}
			}

			if e.wal != nil {
				if err := e.wal.Write("update", dbName, block, newRaw); err != nil {
					log().Warn("WAL update write failed", zap.Error(err))
				}
			}

			e.l1Cache.set(e.cacheKey(dbName, block, doc.ID), newRaw)
			go e.vmIndex(dbName, block, &doc)
			updated++
			sizeDelta += int64(len(newRaw)) - int64(len(raw))
		}
		return nil
	})

	if updated > 0 {
		if meta, err := e.dirMgr.LoadBlockMeta(dbName, block); err == nil {
			meta.DocCount += updated
			meta.SizeBytes += sizeDelta
			meta.UpdatedAt = time.Now().Unix()
			e.dirMgr.SaveBlockMeta(dbName, block, meta)
		}
	}

	e.opCount.Add(updated)
	metricOpsTotal.WithLabelValues("update", dbName, block, shardID, e.nodeID, "success").Add(float64(updated))
	metricOpsDuration.WithLabelValues("update", dbName, block, shardID, e.nodeID).Observe(time.Since(start).Seconds())

	if e.auditLogger != nil && updated > 0 {
		e.auditLogger.Log(AuditLog{
			UserID:   "system",
			Username: "system",
			Action:   "update",
			DB:       dbName,
			Block:    block,
			ShardID:  shardID,
			Status:   "success",
			Message:  fmt.Sprintf("updated=%d", updated),
		})
	}

	return updated, err
}

func (e *Engine) deleteLocal(dbName, block string, filters []Filter, shardID string) (int64, error) {
	start := time.Now()

	db, err := e.pool.openBlock(dbName, block)
	if err != nil {
		return 0, err
	}

	lockKey := dbName + "\x00" + block + "\x00" + shardID
	e.lockManager.Lock(lockKey)
	defer e.lockManager.Unlock(lockKey)

	prefix := docKeyPrefix(block)
	var deleted int64
	var toDelete [][]byte
	var totalSize int64

	err = txHelper.SafeView(db, func(txn *badger.Txn) error {
		opts := badger.DefaultIteratorOptions
		it := txn.NewIterator(opts)
		defer it.Close()
		for it.Seek(prefix); it.ValidForPrefix(prefix); it.Next() {
			var raw []byte
			item := it.Item()
			if item == nil {
				continue
			}
			err := item.Value(func(v []byte) error {
				raw = make([]byte, len(v))
				copy(raw, v)
				return nil
			})
			if err != nil {
				continue
			}
			var doc Document
			if json.Unmarshal(raw, &doc) == nil {
				if doc.ShardID != shardID && shardID != "" {
					continue
				}
				if matchesFilters(doc, filters) {
					k := make([]byte, len(item.Key()))
					copy(k, item.Key())

					if err := e.dropSecondaryIndex(dbName, block, &doc); err != nil {
						log().Error("Failed to drop index on delete", zap.Error(err))
					}

					if doc.LargeID != "" && e.externalStore != nil {
						if err := e.externalStore.Delete(doc.LargeID); err != nil {
							log().Warn("Failed to delete external document", zap.Error(err))
						}
					}

					// Delete from FLEX-COLUMN
					if e.flexEngine != nil {
						e.flexEngine.DeleteWithColumnar(dbName, block, doc.ID)
					}

					if e.wal != nil {
						delData, _ := json.Marshal(filters)
						if err := e.wal.Write("delete", dbName, block, delData); err != nil {
							log().Warn("WAL delete write failed", zap.Error(err))
						}
					}

					toDelete = append(toDelete, k)
					totalSize += int64(len(raw))
				}
			}
		}
		return nil
	})
	if err != nil {
		return 0, err
	}

	batchSize := 10000
	for i := 0; i < len(toDelete); i += batchSize {
		end := i + batchSize
		if end > len(toDelete) {
			end = len(toDelete)
		}
		batch := toDelete[i:end]
		err = txHelper.SafeUpdate(db, func(txn *badger.Txn) error {
			for _, k := range batch {
				if err2 := txn.Delete(k); err2 != nil {
					return err2
				}
				keyStr := string(k)
				id := keyStr[len(prefixDoc)+len(block)+1:]
				e.l1Cache.del(e.cacheKey(dbName, block, id))
				deleted++
			}
			return nil
		})
		if err != nil {
			return deleted, err
		}
	}

	if deleted > 0 {
		if meta, err := e.dirMgr.LoadBlockMeta(dbName, block); err == nil {
			meta.DocCount -= deleted
			meta.SizeBytes -= totalSize
			meta.UpdatedAt = time.Now().Unix()
			e.dirMgr.SaveBlockMeta(dbName, block, meta)
		}
	}

	metricOpsTotal.WithLabelValues("delete", dbName, block, shardID, e.nodeID, "success").Add(float64(deleted))
	metricOpsDuration.WithLabelValues("delete", dbName, block, shardID, e.nodeID).Observe(time.Since(start).Seconds())
	metricDocumentsTotal.WithLabelValues(dbName, block, shardID, e.nodeID).Sub(float64(deleted))

	if stats, ok := e.intelEngine.stats[dbName]; ok {
		stats.DocCount -= deleted
	}

	if e.auditLogger != nil && deleted > 0 {
		e.auditLogger.Log(AuditLog{
			UserID:   "system",
			Username: "system",
			Action:   "delete",
			DB:       dbName,
			Block:    block,
			ShardID:  shardID,
			Status:   "success",
			Message:  fmt.Sprintf("deleted=%d", deleted),
		})
	}

	return deleted, nil
}

func (e *Engine) createDBLocal(name string) error {
	if err := validateName(name); err != nil {
		return err
	}

	dbPath := e.dirMgr.DBPath(name)
	if err := os.MkdirAll(dbPath, 0750); err != nil {
		return err
	}

	meta := map[string]any{
		"name":       name,
		"created_at": time.Now().Unix(),
		"version":    Version,
	}
	if err := e.dirMgr.SaveDBMeta(name, meta); err != nil {
		return err
	}

	log().Info("Database created", zap.String("db", name))
	cfg := &DBConfig{
		Name:        name,
		ShardCount:  e.shardMgr.shardCount,
		Replicas:    e.shardMgr.replicaCount,
		CacheSizeMB: e.l1Cache.maxBytes / 1024 / 1024,
		Compression: "zstd",
		AutoTune:    true,
		AutoScale:   true,
		Indexes:     []string{},
		Custom:      make(map[string]any),
		CreatedAt:   time.Now().Unix(),
		UpdatedAt:   time.Now().Unix(),
		Stats: &DBStats{
			LastOptimized: time.Now(),
		},
	}
	e.intelEngine.SetConfig(cfg)

	if e.auditLogger != nil {
		e.auditLogger.Log(AuditLog{
			UserID:   "system",
			Username: "system",
			Action:   "create_db",
			DB:       name,
			Status:   "success",
		})
	}
	return nil
}

func (e *Engine) dropDBLocal(name string) error {
	path := e.dirMgr.DBPath(name)
	if err := e.pool.closeAndRemove(path); err != nil {
		log().Warn("Failed to close DB before drop", zap.String("db", name), zap.Error(err))
	}

	if err := os.RemoveAll(path); err != nil {
		return err
	}

	log().Info("Database dropped", zap.String("db", name))
	e.intelEngine.mu.Lock()
	delete(e.intelEngine.configs, name)
	delete(e.intelEngine.stats, name)
	e.intelEngine.mu.Unlock()

	if e.auditLogger != nil {
		e.auditLogger.Log(AuditLog{
			UserID:   "system",
			Username: "system",
			Action:   "drop_db",
			DB:       name,
			Status:   "success",
		})
	}
	return nil
}

func (e *Engine) createBlockLocal(dbName, block string) error {
	if err := validateName(block); err != nil {
		return err
	}

	if !e.dirMgr.DBExists(dbName) {
		return ErrDBNotFound
	}

	if err := e.dirMgr.CreateBlockDirectories(dbName, block); err != nil {
		return err
	}

	meta := BlockMeta{
		Name:      block,
		DB:        dbName,
		CreatedAt: time.Now().Unix(),
		DocCount:  0,
		SizeBytes: 0,
	}
	if err := e.dirMgr.SaveBlockMeta(dbName, block, meta); err != nil {
		return err
	}

	log().Info("Block created", zap.String("db", dbName), zap.String("block", block))
	return nil
}

func (e *Engine) dropBlockLocal(dbName, block string) error {
	lockKey := dbName + "\x00" + block
	e.lockManager.Lock(lockKey)
	defer e.lockManager.Unlock(lockKey)

	dataPath := e.dirMgr.BlockDataPath(dbName, block)
	if err := e.pool.closeAndRemove(dataPath); err != nil {
		log().Warn("Failed to close block DB before drop", zap.String("block", block), zap.Error(err))
	}

	if err := e.dirMgr.RemoveBlockDirectories(dbName, block); err != nil {
		return err
	}

	log().Info("Block dropped", zap.String("db", dbName), zap.String("block", block))
	return nil
}

func (e *Engine) renameBlockLocal(dbName, oldName, newName string) error {
	if err := validateName(newName); err != nil {
		return err
	}

	if !e.dirMgr.BlockExists(dbName, oldName) {
		return ErrBlockNotFound
	}

	if e.dirMgr.BlockExists(dbName, newName) {
		return fmt.Errorf("block %s already exists", newName)
	}

	oldPath := e.dirMgr.BlockPath(dbName, oldName)
	newPath := e.dirMgr.BlockPath(dbName, newName)

	if err := os.Rename(oldPath, newPath); err != nil {
		return err
	}

	meta, err := e.dirMgr.LoadBlockMeta(dbName, newName)
	if err == nil {
		meta.Name = newName
		meta.UpdatedAt = time.Now().Unix()
		e.dirMgr.SaveBlockMeta(dbName, newName, meta)
	}

	log().Info("Block renamed",
		zap.String("db", dbName),
		zap.String("old", oldName),
		zap.String("new", newName))
	return nil
}
