// Code generated by splitting main.go. Part of package main.
package novodb

import (
	"encoding/json"
	"go.uber.org/zap"
)

func (e *Engine) CreateBlock(dbName, block string) error {
	if e.cluster != nil && e.cluster.IsLeader() {
		cmd := RaftCommand{
			Op:    "create_block",
			DB:    dbName,
			Block: block,
		}
		data, err := json.Marshal(cmd)
		if err != nil {
			return err
		}
		future := e.cluster.raft.Apply(data, raftTimeout)
		return future.Error()
	}
	return e.createBlockLocal(dbName, block)
}

func (e *Engine) DropBlock(dbName, block string) error {
	if e.cluster != nil && e.cluster.IsLeader() {
		cmd := RaftCommand{
			Op:    "drop_block",
			DB:    dbName,
			Block: block,
		}
		data, err := json.Marshal(cmd)
		if err != nil {
			return err
		}
		future := e.cluster.raft.Apply(data, raftTimeout)
		return future.Error()
	}
	return e.dropBlockLocal(dbName, block)
}

func (e *Engine) RenameBlock(dbName, oldName, newName string) error {
	if e.cluster != nil && e.cluster.IsLeader() {
		cmd := RaftCommand{
			Op:    "rename_block",
			DB:    dbName,
			Block: oldName,
			ID:    newName,
		}
		data, err := json.Marshal(cmd)
		if err != nil {
			return err
		}
		future := e.cluster.raft.Apply(data, raftTimeout)
		return future.Error()
	}
	return e.renameBlockLocal(dbName, oldName, newName)
}

func (e *Engine) ShowBlocks(dbName string) ([]string, error) {
	return e.dirMgr.ListBlocks(dbName)
}

func (e *Engine) DescribeBlock(dbName, block string) (map[string]any, error) {
	if !e.dirMgr.BlockExists(dbName, block) {
		return nil, ErrBlockNotFound
	}

	meta, err := e.dirMgr.LoadBlockMeta(dbName, block)
	if err != nil {
		return nil, err
	}

	count, _ := e.Count(dbName, block, nil)

	cfg, _ := e.intelEngine.GetConfig(dbName)
	indexes := []string{}
	if cfg != nil {
		indexes = cfg.Indexes
	}

	return map[string]any{
		"name":       block,
		"db":         dbName,
		"created_at": meta.CreatedAt,
		"updated_at": meta.UpdatedAt,
		"documents":  count,
		"doc_count":  meta.DocCount,
		"node_id":    e.nodeID,
		"size_bytes": meta.SizeBytes,
		"indexes":    indexes,
	}, nil
}

func (e *Engine) EmptyBlock(dbName, block string) (int64, error) {
	count, err := e.Count(dbName, block, nil)
	if err != nil {
		return 0, err
	}
	if count == 0 {
		return 0, nil
	}
	deleted, err := e.deleteLocal(dbName, block, []Filter{}, "")
	if err != nil {
		return deleted, err
	}
	log().Info("Block emptied",
		zap.String("db", dbName),
		zap.String("block", block),
		zap.Int64("deleted", deleted))
	return deleted, nil
}
