// Code generated by splitting main.go. Part of package main.
package novodb

import (
	"encoding/json"
	"fmt"
	"go.uber.org/zap"
	"sync/atomic"
	"time"
)

func (e *Engine) Insert(dbName, block string, data map[string]any) (*Document, error) {
	id := newID()
	data["id"] = id
	return e.insertWithID(dbName, block, id, data)
}

func (e *Engine) insertWithID(dbName, block, id string, data map[string]any) (*Document, error) {
	shardID := e.shardMgr.GetShardForDoc(dbName, block, id)

	if e.cluster != nil && e.cluster.IsLeader() {
		cmd := RaftCommand{
			Op:      "insert",
			DB:      dbName,
			Block:   block,
			ID:      id,
			ShardID: shardID,
			Data:    data,
		}
		cmdData, err := json.Marshal(cmd)
		if err != nil {
			return nil, err
		}
		future := e.cluster.raft.Apply(cmdData, raftTimeout)
		if err := future.Error(); err != nil {
			return nil, err
		}
		if doc, ok := future.Response().(*Document); ok {
			return doc, nil
		}
		return nil, fmt.Errorf("invalid response from Raft")
	}
	return e.insertWithIDLocal(dbName, block, id, data, shardID)
}

func (e *Engine) InsertBatch(dbName, block string, docs []map[string]any) (int64, int64) {
	if len(docs) == 0 {
		return 0, 0
	}

	if len(docs) > e.config.MaxBatchSize {
		log().Warn("Batch too large, truncating",
			zap.Int("requested", len(docs)),
			zap.Int("max", e.config.MaxBatchSize))
		docs = docs[:e.config.MaxBatchSize]
	}

	if e.cluster != nil && e.cluster.IsLeader() {
		var inserted, errors int64
		batchSize := 100
		for i := 0; i < len(docs); i += batchSize {
			end := i + batchSize
			if end > len(docs) {
				end = len(docs)
			}
			subBatch := docs[i:end]
			for _, data := range subBatch {
				if _, err := e.Insert(dbName, block, data); err != nil {
					errors++
				} else {
					inserted++
				}
			}
		}
		return inserted, errors
	}

	if err := e.dirMgr.CreateBlockDirectories(dbName, block); err != nil {
		return 0, int64(len(docs))
	}

	db, err := e.pool.openBlock(dbName, block)
	if err != nil {
		return 0, int64(len(docs))
	}

	lockKey := dbName + "\x00" + block
	e.lockManager.Lock(lockKey)
	defer e.lockManager.Unlock(lockKey)

	var inserted, errors atomic.Int64
	now := time.Now().Unix()
	var totalSize int64

	wb := db.NewWriteBatch()
	defer wb.Cancel()

	var docsToIndex []Document
	processed := 0

	for _, data := range docs {
		id := newID()
		shardID := e.shardMgr.GetShardForDoc(dbName, block, id)

		doc := Document{
			ID:      id,
			Data:    data,
			Meta:    DocMeta{CreatedAt: now, UpdatedAt: now, Version: 1},
			ShardID: shardID,
		}
		raw, err2 := json.Marshal(doc)
		if err2 != nil {
			errors.Add(1)
			continue
		}

		if int64(len(raw)) > e.config.MaxDocumentSize {
			errors.Add(1)
			continue
		}

		if e.externalStore != nil && int64(len(raw)) > e.config.LargeDocThreshold {
			largeID, err3 := e.externalStore.Save(raw)
			if err3 != nil {
				errors.Add(1)
				continue
			}
			doc.LargeID = largeID
			raw, _ = json.Marshal(doc)
		}

		compressedData := raw
		if e.config.CompressLargeDocs && int64(len(raw)) > e.config.CompressThreshold {
			if comp, ok, err := compressData(raw, CompressionZstd); err == nil && ok {
				compressedData = comp
			}
		}

		if err2 = wb.Set(docKey(block, id), compressedData); err2 != nil {
			errors.Add(1)
			continue
		}

		if e.wal != nil {
			if err := e.wal.Write("insert", dbName, block, compressedData); err != nil {
				log().Warn("WAL batch insert write failed", zap.Error(err))
			}
		}

		e.l1Cache.set(e.cacheKey(dbName, block, id), raw)
		docsToIndex = append(docsToIndex, doc)
		inserted.Add(1)
		totalSize += int64(len(raw))
		processed++

		if processed%1000 == 0 {
			if err2 := wb.Flush(); err2 != nil {
				log().Error("Batch flush failed", zap.Error(err2))
				return inserted.Load(), errors.Load()
			}
			wb = db.NewWriteBatch()
		}
	}

	if err2 := wb.Flush(); err2 != nil {
		log().Error("Final batch flush failed", zap.Error(err2))
		return inserted.Load(), errors.Load()
	}

	if inserted.Load() > 0 {
		if meta, err := e.dirMgr.LoadBlockMeta(dbName, block); err == nil {
			meta.DocCount += inserted.Load()
			meta.SizeBytes += totalSize
			meta.UpdatedAt = time.Now().Unix()
			e.dirMgr.SaveBlockMeta(dbName, block, meta)
		}
	}

	if len(docsToIndex) > 0 {
		go func() {
			for _, doc := range docsToIndex {
				if int64(len(doc.Data)) < e.config.IndexSkipThreshold {
					if err := e.buildSecondaryIndex(dbName, block, &doc); err != nil {
						log().Error("Failed to build index in batch", zap.Error(err))
					}
				}
				e.shardMgr.UpdateShardStats(doc.ShardID, 1, 0)

				// Update FLEX-COLUMN
				if e.flexEngine != nil {
					e.flexEngine.InsertWithColumnar(dbName, block, &doc)
				}
			}
		}()
	}

	e.opCount.Add(inserted.Load())
	metricOpsTotal.WithLabelValues("insert_batch", dbName, block, "", e.nodeID, "success").Add(float64(inserted.Load()))
	metricDocumentsTotal.WithLabelValues(dbName, block, "", e.nodeID).Add(float64(inserted.Load()))

	return inserted.Load(), errors.Load()
}
