// Code generated by splitting main.go. Part of package main.
package novodb

import (
	"bufio"
	"bytes"
	"encoding/csv"
	"encoding/json"
	"fmt"
	badger "github.com/dgraph-io/badger/v4"
	"go.uber.org/zap"
	"io"
	"os"
	"sort"
	"strings"
	"time"
)

func (e *Engine) Export(dbName, block, dest string) (int64, error) {
	start := time.Now()

	if !e.dirMgr.BlockExists(dbName, block) {
		return 0, ErrBlockNotFound
	}

	db, err := e.pool.openBlock(dbName, block)
	if err != nil {
		return 0, err
	}

	f, err := os.Create(dest)
	if err != nil {
		return 0, err
	}
	defer f.Close()
	bw := bufio.NewWriterSize(f, 128<<20)

	isCSV := strings.HasSuffix(strings.ToLower(dest), ".csv")
	prefix := docKeyPrefix(block)

	var csvW *csv.Writer
	var headers []string
	first := true
	var exported int64

	err = txHelper.SafeView(db, func(txn *badger.Txn) error {
		opts := badger.DefaultIteratorOptions
		opts.PrefetchSize = 20000
		it := txn.NewIterator(opts)
		defer it.Close()

		for it.Seek(prefix); it.ValidForPrefix(prefix); it.Next() {
			item := it.Item()
			if item == nil {
				continue
			}
			var doc Document
			item.Value(func(v []byte) error { return json.Unmarshal(v, &doc) })

			if isCSV {
				if first {
					headers = append(headers, "_id", "_shard_id")
					for k := range doc.Data {
						headers = append(headers, k)
					}
					sort.Strings(headers[2:])
					csvW = csv.NewWriter(bw)
					csvW.Write(headers)
					first = false
				}
				row := []string{doc.ID, doc.ShardID}
				for _, h := range headers[2:] {
					row = append(row, fmt.Sprint(doc.Data[h]))
				}
				csvW.Write(row)
			} else {
				b, _ := json.Marshal(doc)
				bw.Write(b)
				bw.WriteByte('\n')
			}
			exported++
		}
		return nil
	})

	if csvW != nil {
		csvW.Flush()
	}
	err = bw.Flush()

	log().Info("Export completed",
		zap.String("db", dbName),
		zap.String("block", block),
		zap.String("dest", dest),
		zap.Int64("exported", exported),
		zap.Duration("duration", time.Since(start)))

	return exported, err
}

func (e *Engine) Import(dbName, block, src string) (int64, int64, error) {
	start := time.Now()

	if err := e.dirMgr.CreateBlockDirectories(dbName, block); err != nil {
		return 0, 0, err
	}

	f, err := os.Open(src)
	if err != nil {
		return 0, 0, err
	}
	defer f.Close()

	var inserted, errors int64

	if strings.HasSuffix(strings.ToLower(src), ".csv") {
		r := csv.NewReader(bufio.NewReaderSize(f, 128<<20))
		headers, err := r.Read()
		if err != nil {
			return 0, 0, err
		}
		for {
			row, err := r.Read()
			if err == io.EOF {
				break
			}
			if err != nil {
				errors++
				continue
			}
			data := make(map[string]any, len(headers))
			for i, h := range headers {
				if i < len(row) {
					if h == "_shard_id" {
						continue
					}
					if h != "_id" {
						data[h] = row[i]
					}
				}
			}
			if _, err := e.Insert(dbName, block, data); err != nil {
				errors++
			} else {
				inserted++
			}
		}
	} else {
		scanner := bufio.NewScanner(f)
		scanner.Buffer(make([]byte, 128<<20), 128<<20)
		for scanner.Scan() {
			line := bytes.TrimSpace(scanner.Bytes())
			if len(line) == 0 {
				continue
			}
			var data map[string]any
			if json.Unmarshal(line, &data) != nil {
				errors++
				continue
			}
			delete(data, "_id")
			if _, err := e.Insert(dbName, block, data); err != nil {
				errors++
			} else {
				inserted++
			}
		}
	}

	log().Info("Import completed",
		zap.String("db", dbName),
		zap.String("block", block),
		zap.String("src", src),
		zap.Int64("inserted", inserted),
		zap.Int64("errors", errors),
		zap.Duration("duration", time.Since(start)))

	return inserted, errors, nil
}
