// Code generated by splitting main.go. Part of package main.
package novodb

import (
	"encoding/json"
	"fmt"
)

type UpdateOp struct {
	Set  map[string]any
	Inc  map[string]float64
	Dec  map[string]float64
	Push map[string]any
	Pull map[string]any
}

func (e *Engine) Update(dbName, block string, filters []Filter, op UpdateOp) (int64, error) {
	shardID := ""
	if e.cluster != nil && e.cluster.IsLeader() {
		cmd := RaftCommand{
			Op:       "update",
			DB:       dbName,
			Block:    block,
			Filters:  filters,
			UpdateOp: &op,
			ShardID:  shardID,
		}
		cmdData, err := json.Marshal(cmd)
		if err != nil {
			return 0, err
		}
		future := e.cluster.raft.Apply(cmdData, raftTimeout)
		if err := future.Error(); err != nil {
			return 0, err
		}
		if n, ok := future.Response().(int64); ok {
			return n, nil
		}
		return 0, fmt.Errorf("invalid response from Raft")
	}
	return e.updateLocal(dbName, block, filters, op, shardID)
}

func applyUpdateOp(doc *Document, op UpdateOp) {
	for k, v := range op.Set {
		setNested(doc.Data, k, v)
	}
	for k, v := range op.Inc {
		setNested(doc.Data, k, getNestedF64(doc.Data, k)+v)
	}
	for k, v := range op.Dec {
		setNested(doc.Data, k, getNestedF64(doc.Data, k)-v)
	}
	for k, v := range op.Push {
		arr := getNestedArr(doc.Data, k)
		setNested(doc.Data, k, append(arr, v))
	}
	for k, v := range op.Pull {
		arr := getNestedArr(doc.Data, k)
		var out []any
		for _, item := range arr {
			if fmt.Sprint(item) != fmt.Sprint(v) {
				out = append(out, item)
			}
		}
		setNested(doc.Data, k, out)
	}
}
