// Code generated by splitting main.go. Part of package main.
package novodb

import (
	"encoding/json"
	"fmt"
	badger "github.com/dgraph-io/badger/v4"
)

func (e *Engine) Delete(dbName, block string, filters []Filter) (int64, error) {
	shardID := ""
	if e.cluster != nil && e.cluster.IsLeader() {
		cmd := RaftCommand{
			Op:      "delete",
			DB:      dbName,
			Block:   block,
			Filters: filters,
			ShardID: shardID,
		}
		cmdData, err := json.Marshal(cmd)
		if err != nil {
			return 0, err
		}
		future := e.cluster.raft.Apply(cmdData, raftTimeout)
		if err := future.Error(); err != nil {
			return 0, err
		}
		if n, ok := future.Response().(int64); ok {
			return n, nil
		}
		return 0, fmt.Errorf("invalid response from Raft")
	}
	return e.deleteLocal(dbName, block, filters, shardID)
}

func (e *Engine) Count(dbName, block string, filters []Filter) (int64, error) {
	if !e.dirMgr.BlockExists(dbName, block) {
		return 0, nil
	}

	db, err := e.pool.openBlock(dbName, block)
	if err != nil {
		return 0, err
	}

	if len(filters) == 1 && filters[0].Op == "=" {
		plan := e.queryOpt.AnalyzeQuery(filters)
		if plan.UseIndex {
			result, err := e.lookupByIndex(dbName, block, plan.IndexField, plan.IndexValue, 0, 1)
			if err == nil {
				return result.Total, nil
			}
		}
	}

	prefix := docKeyPrefix(block)
	var count int64

	err = txHelper.SafeView(db, func(txn *badger.Txn) error {
		opts := badger.DefaultIteratorOptions
		if len(filters) == 0 {
			opts.PrefetchValues = false
		}
		it := txn.NewIterator(opts)
		defer it.Close()

		for it.Seek(prefix); it.ValidForPrefix(prefix); it.Next() {
			item := it.Item()
			if item == nil {
				continue
			}
			if len(filters) == 0 {
				count++
				continue
			}
			var doc Document
			err := item.Value(func(v []byte) error {
				return json.Unmarshal(v, &doc)
			})
			if err != nil {
				continue
			}
			if matchesFilters(doc, filters) {
				count++
			}
		}
		return nil
	})
	return count, err
}
