// Code generated by splitting main.go. Part of package main.
package novodb

import (
	"context"
	"encoding/json"
	badger "github.com/dgraph-io/badger/v4"
	"strconv"
	"strings"
	"sync"
	"time"
)

type Query struct {
	Filters    []Filter
	Select     []string
	Exclude    []string
	Sort       []SortField
	Limit      int
	Offset     int
	UseIndex   bool
	PreferScan bool
	ShardID    string
	Timeout    time.Duration
}

type Filter struct {
	Field  string
	Op     string
	Value  any
	Value2 any
	Values []any
	Logic  string
}

type SortField struct {
	Field string
	Desc  bool
}

type QueryResult struct {
	Docs      []Document    `json:"docs"`
	Total     int64         `json:"total"`
	Scanned   int64         `json:"scanned"`
	IndexUsed string        `json:"index_used"`
	Took      time.Duration `json:"took"`
}

func (e *Engine) Find(dbName, block string, q *Query) (*QueryResult, error) {
	start := time.Now()
	defer func() {
		e.metrics.RecordQuery(time.Since(start))
		metricActiveQueries.Dec()
	}()
	metricActiveQueries.Inc()

	if !e.dirMgr.BlockExists(dbName, block) {
		return nil, ErrBlockNotFound
	}

	// Try FLEX-COLUMN acceleration first
	if e.flexEngine != nil && e.flexEngine.config.Enabled {
		result, err := e.flexEngine.QueryWithColumnar(dbName, block, q)
		if err == nil && result != nil && len(result.Docs) > 0 {
			return result, nil
		}
	}

	ctx := context.Background()
	if q.Timeout > 0 {
		var cancel context.CancelFunc
		ctx, cancel = context.WithTimeout(ctx, q.Timeout)
		defer cancel()
	} else if e.config.QueryTimeout > 0 {
		var cancel context.CancelFunc
		ctx, cancel = context.WithTimeout(ctx, e.config.QueryTimeout)
		defer cancel()
	}

	db, err := e.pool.openBlock(dbName, block)
	if err != nil {
		return nil, err
	}

	var docIDs []string
	var scanAll bool
	var indexUsed string

	if !q.PreferScan && len(q.Filters) > 0 {
		plan := e.queryOpt.AnalyzeQuery(q.Filters)
		if plan.UseIndex && (q.UseIndex || !q.PreferScan) {
			page := 0
			pageSize := q.Limit
			if pageSize <= 0 {
				pageSize = 10000
			}
			result, err := e.lookupByIndex(dbName, block, plan.IndexField, plan.IndexValue, page, pageSize)
			if err == nil && len(result.DocIDs) > 0 {
				docIDs = result.DocIDs
				scanAll = false
				indexUsed = plan.IndexField
			}
		}
	}

	if scanAll || len(docIDs) == 0 {
		docIDs = nil
		indexUsed = "full_scan"
		result, err := e.scanBlock(ctx, dbName, block, q, db)
		if err == nil {
			e.intelEngine.RecordQuery(&QueryRecord{
				DB:        dbName,
				Block:     block,
				Filters:   q.Filters,
				Duration:  result.Took,
				Timestamp: time.Now(),
				IndexUsed: result.IndexUsed,
				Scanned:   result.Scanned,
				Returned:  result.Total,
			})
			e.updateDBStats(dbName, result)
			metricQueryLatency.WithLabelValues(dbName, block, "scan").Observe(result.Took.Seconds())
		}
		return result, err
	}

	var docs []Document
	var scanned int64

	sem := make(chan struct{}, 1000)
	var mu sync.Mutex
	var wg sync.WaitGroup

	for _, id := range docIDs {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		default:
		}

		wg.Add(1)
		sem <- struct{}{}
		go func(id string) {
			defer wg.Done()
			defer func() { <-sem }()

			ck := e.cacheKey(dbName, block, id)
			var doc Document
			var found bool

			if raw, ok := e.l1Cache.get(ck); ok {
				if json.Unmarshal(raw, &doc) == nil {
					found = true
				}
			}

			if !found {
				err := txHelper.SafeView(db, func(txn *badger.Txn) error {
					item, err := txn.Get(docKey(block, id))
					if err != nil {
						return err
					}
					return item.Value(func(v []byte) error {
						if e.config.CompressLargeDocs && len(v) > 0 {
							if decompressed, err := decompressData(v); err == nil {
								e.l1Cache.set(ck, decompressed)
								return json.Unmarshal(decompressed, &doc)
							}
						}
						e.l1Cache.set(ck, v)
						return json.Unmarshal(v, &doc)
					})
				})
				if err != nil {
					return
				}
			}

			mu.Lock()
			scanned++
			if matchesFilters(doc, q.Filters) {
				if q.ShardID == "" || doc.ShardID == q.ShardID {
					docs = append(docs, doc)
				}
			}
			mu.Unlock()
		}(id)
	}
	wg.Wait()

	total := int64(len(docs))
	docs = e.postProcessDocs(docs, q)

	result := &QueryResult{
		Docs:      docs,
		Total:     total,
		Scanned:   scanned,
		IndexUsed: indexUsed,
		Took:      time.Since(start),
	}

	e.intelEngine.RecordQuery(&QueryRecord{
		DB:        dbName,
		Block:     block,
		Filters:   q.Filters,
		Duration:  result.Took,
		Timestamp: time.Now(),
		IndexUsed: result.IndexUsed,
		Scanned:   result.Scanned,
		Returned:  result.Total,
	})
	e.updateDBStats(dbName, result)
	metricQueryLatency.WithLabelValues(dbName, block, "index").Observe(result.Took.Seconds())

	return result, nil
}

func (e *Engine) scanBlock(ctx context.Context, dbName, block string, q *Query, db *badger.DB) (*QueryResult, error) {
	start := time.Now()
	prefix := docKeyPrefix(block)

	var matched []Document
	var scanned int64

	limit := q.Limit
	offset := q.Offset
	if limit <= 0 {
		limit = 10000
	}
	if offset < 0 {
		offset = 0
	}

	err := txHelper.SafeView(db, func(txn *badger.Txn) error {
		opts := badger.DefaultIteratorOptions
		opts.PrefetchSize = 100
		opts.PrefetchValues = true
		it := txn.NewIterator(opts)
		defer it.Close()

		skipCount := 0

		for it.Seek(prefix); it.ValidForPrefix(prefix); it.Next() {
			select {
			case <-ctx.Done():
				return ctx.Err()
			default:
			}

			if skipCount < offset {
				skipCount++
				continue
			}

			if len(matched) >= limit && limit > 0 {
				break
			}

			var doc Document
			item := it.Item()
			if item == nil {
				continue
			}
			err := item.Value(func(v []byte) error {
				if e.config.CompressLargeDocs && len(v) > 0 {
					if decompressed, err := decompressData(v); err == nil {
						return json.Unmarshal(decompressed, &doc)
					}
				}
				return json.Unmarshal(v, &doc)
			})
			if err != nil {
				continue
			}

			scanned++

			if q.ShardID != "" && doc.ShardID != q.ShardID {
				continue
			}

			if matchesFilters(doc, q.Filters) {
				matched = append(matched, doc)
			}
		}
		return nil
	})

	if err != nil {
		return nil, err
	}

	total := int64(len(matched))
	docs := e.postProcessDocs(matched, q)

	return &QueryResult{
		Docs:      docs,
		Total:     total,
		Scanned:   scanned,
		IndexUsed: "full_scan",
		Took:      time.Since(start),
	}, nil
}

func (e *Engine) postProcessDocs(docs []Document, q *Query) []Document {
	if len(q.Sort) > 0 {
		sortDocs(docs, q.Sort)
	}

	if len(q.Select) > 0 || len(q.Exclude) > 0 {
		for i := range docs {
			docs[i].Data = project(docs[i].Data, q.Select, q.Exclude)
		}
	}

	if q.Limit > 0 && len(docs) > q.Limit {
		docs = docs[:q.Limit]
	}

	return docs
}

func (e *Engine) FindByID(dbName, block, id string) (*Document, bool) {
	if !e.dirMgr.BlockExists(dbName, block) {
		return nil, false
	}

	ck := e.cacheKey(dbName, block, id)
	if raw, ok := e.l1Cache.get(ck); ok {
		var doc Document
		if json.Unmarshal(raw, &doc) == nil {
			if doc.LargeID != "" && e.externalStore != nil {
				if externalData, err := e.externalStore.Load(doc.LargeID); err == nil {
					var fullDoc Document
					if json.Unmarshal(externalData, &fullDoc) == nil {
						return &fullDoc, true
					}
				}
			}
			metricCacheHits.Inc()
			return &doc, true
		}
	}

	db, err := e.pool.openBlock(dbName, block)
	if err != nil {
		return nil, false
	}

	var doc Document
	err = txHelper.SafeView(db, func(txn *badger.Txn) error {
		item, err := txn.Get(docKey(block, id))
		if err != nil {
			return err
		}
		return item.Value(func(v []byte) error {
			if e.config.CompressLargeDocs && len(v) > 0 {
				if decompressed, err := decompressData(v); err == nil {
					e.l1Cache.set(ck, decompressed)
					return json.Unmarshal(decompressed, &doc)
				}
			}
			e.l1Cache.set(ck, v)
			return json.Unmarshal(v, &doc)
		})
	})
	if err != nil {
		metricCacheMisses.Inc()
		return nil, false
	}

	if doc.LargeID != "" && e.externalStore != nil {
		if externalData, err := e.externalStore.Load(doc.LargeID); err == nil {
			var fullDoc Document
			if json.Unmarshal(externalData, &fullDoc) == nil {
				metricCacheHits.Inc()
				return &fullDoc, true
			}
		}
	}

	metricCacheHits.Inc()
	return &doc, true
}

func (e *Engine) updateDBStats(dbName string, result *QueryResult) {
	if stats, ok := e.intelEngine.stats[dbName]; ok {
		stats.QueryCount++
		stats.AvgQueryTime = (stats.AvgQueryTime*float64(stats.QueryCount-1) + float64(result.Took.Milliseconds())) / float64(stats.QueryCount)
		if result.IndexUsed != "full_scan" {
			stats.IndexHitRate = (stats.IndexHitRate*float64(stats.QueryCount-1) + 1) / float64(stats.QueryCount)
		} else {
			stats.IndexHitRate = (stats.IndexHitRate*float64(stats.QueryCount-1) + 0) / float64(stats.QueryCount)
		}
		cacheStats := e.l1Cache.stats()
		if hitRatio, ok := cacheStats["hit_ratio"].(string); ok {
			if val, err := strconv.ParseFloat(strings.TrimSuffix(hitRatio, "%"), 64); err == nil {
				stats.CacheHitRate = val / 100
			}
		}
	}
}
