// Code generated by splitting main.go. Part of package main.
package novodb

import (
	"fmt"
	"sync"
	"time"
)

type QueryOptimizer struct {
	mu              sync.RWMutex
	indexStats      map[string]*IndexStats
	tableStats      map[string]*TableStats
	lastAnalyze     time.Time
	analyzeInterval time.Duration
}

type IndexStats struct {
	Field       string
	Size        int64
	Selectivity float64
	LastUsed    time.Time
	UseCount    int64
}

type TableStats struct {
	TotalDocs     int64
	AvgDocSize    int64
	IndexedFields []string
}

func NewQueryOptimizer() *QueryOptimizer {
	return &QueryOptimizer{
		indexStats:      make(map[string]*IndexStats),
		tableStats:      make(map[string]*TableStats),
		analyzeInterval: 5 * time.Minute,
	}
}

func (qo *QueryOptimizer) UpdateIndexStats(field string, size int64, selectivity float64) {
	qo.mu.Lock()
	defer qo.mu.Unlock()
	if stat, ok := qo.indexStats[field]; ok {
		stat.Size = size
		stat.Selectivity = selectivity
		stat.LastUsed = time.Now()
		stat.UseCount++
	} else {
		qo.indexStats[field] = &IndexStats{
			Field:       field,
			Size:        size,
			Selectivity: selectivity,
			LastUsed:    time.Now(),
			UseCount:    1,
		}
	}
}

type QueryPlan struct {
	UseIndex      bool
	IndexField    string
	IndexValue    string
	ScanAll       bool
	EstimatedCost int64
}

func (qo *QueryOptimizer) AnalyzeQuery(filters []Filter) QueryPlan {
	qo.mu.RLock()
	defer qo.mu.RUnlock()

	plan := QueryPlan{
		UseIndex:      false,
		IndexField:    "",
		IndexValue:    "",
		ScanAll:       true,
		EstimatedCost: 0,
	}

	var bestIndex *IndexStats
	var bestField string

	for _, f := range filters {
		if f.Op == "=" || f.Op == "==" || f.Op == "IN" {
			stats, ok := qo.indexStats[f.Field]
			if ok && stats.Selectivity < 0.3 {
				if bestIndex == nil || stats.Selectivity < bestIndex.Selectivity {
					bestIndex = stats
					bestField = f.Field
					plan.IndexValue = fmt.Sprint(f.Value)
				}
			}
		}
	}

	if bestIndex != nil {
		plan.UseIndex = true
		plan.IndexField = bestField
		plan.ScanAll = false
		plan.EstimatedCost = int64(float64(bestIndex.Size) * bestIndex.Selectivity)
	}

	return plan
}
