// Code generated by splitting main.go. Part of package main.
package novodb

import (
	"fmt"
	"strings"
)

func matchesFilters(doc Document, filters []Filter) bool {
	if len(filters) == 0 {
		return true
	}
	result := false
	first := true
	for _, f := range filters {
		m := matchFilter(doc, f)
		if first {
			result = m
			first = false
		} else if strings.EqualFold(f.Logic, "OR") {
			result = result || m
		} else {
			result = result && m
		}
	}
	return result
}

func matchFilter(doc Document, f Filter) bool {
	val := getNested(doc.Data, f.Field)
	switch strings.ToUpper(f.Op) {
	case "=", "==":
		return fmt.Sprint(val) == fmt.Sprint(f.Value)
	case "!=", "<>":
		return fmt.Sprint(val) != fmt.Sprint(f.Value)
	case ">":
		return compareNumbers(val, f.Value) > 0
	case "<":
		return compareNumbers(val, f.Value) < 0
	case ">=":
		return compareNumbers(val, f.Value) >= 0
	case "<=":
		return compareNumbers(val, f.Value) <= 0
	case "LIKE":
		s := strings.ToLower(fmt.Sprint(val))
		p := strings.ToLower(fmt.Sprint(f.Value))
		if strings.HasPrefix(p, "%") && strings.HasSuffix(p, "%") {
			return strings.Contains(s, strings.Trim(p, "%"))
		} else if strings.HasPrefix(p, "%") {
			return strings.HasSuffix(s, strings.TrimPrefix(p, "%"))
		} else if strings.HasSuffix(p, "%") {
			return strings.HasPrefix(s, strings.TrimSuffix(p, "%"))
		}
		return s == p
	case "NOT LIKE":
		s := strings.ToLower(fmt.Sprint(val))
		p := strings.ToLower(fmt.Sprint(f.Value))
		if strings.HasPrefix(p, "%") && strings.HasSuffix(p, "%") {
			return !strings.Contains(s, strings.Trim(p, "%"))
		} else if strings.HasPrefix(p, "%") {
			return !strings.HasSuffix(s, strings.TrimPrefix(p, "%"))
		} else if strings.HasSuffix(p, "%") {
			return !strings.HasPrefix(s, strings.TrimSuffix(p, "%"))
		}
		return s != p
	case "CONTAINS":
		return strings.Contains(strings.ToLower(fmt.Sprint(val)), strings.ToLower(fmt.Sprint(f.Value)))
	case "NOT CONTAINS":
		return !strings.Contains(strings.ToLower(fmt.Sprint(val)), strings.ToLower(fmt.Sprint(f.Value)))
	case "EXISTS":
		return val != nil
	case "IN":
		sv := fmt.Sprint(val)
		for _, v := range f.Values {
			if fmt.Sprint(v) == sv {
				return true
			}
		}
		return false
	case "NOT IN":
		sv := fmt.Sprint(val)
		for _, v := range f.Values {
			if fmt.Sprint(v) == sv {
				return false
			}
		}
		return true
	case "BETWEEN":
		return compareNumbers(val, f.Value) >= 0 && compareNumbers(val, f.Value2) <= 0
	case "STARTS WITH":
		return strings.HasPrefix(fmt.Sprint(val), fmt.Sprint(f.Value))
	case "ENDS WITH":
		return strings.HasSuffix(fmt.Sprint(val), fmt.Sprint(f.Value))
	case "IS NULL":
		return val == nil || fmt.Sprint(val) == ""
	case "IS NOT NULL":
		return val != nil && fmt.Sprint(val) != ""
	}
	return false
}

func compareNumbers(a, b any) int {
	fa := toF64(a)
	fb := toF64(b)

	if fa != 0 || fb != 0 {
		if fa < fb {
			return -1
		}
		if fa > fb {
			return 1
		}
		return 0
	}

	sa := fmt.Sprint(a)
	sb := fmt.Sprint(b)
	return strings.Compare(sa, sb)
}
