// Code generated by splitting main.go. Part of package main.
package novodb

import (
	"bytes"
	"encoding/json"
	"fmt"
	"github.com/hashicorp/raft"
	"go.uber.org/zap"
	"io"
	"os"
	"sync"
	"time"
)

type RaftFSM struct {
	engine *Engine
	mu     sync.RWMutex
}

type RaftCommand struct {
	Op       string         `json:"op"`
	DB       string         `json:"db,omitempty"`
	Block    string         `json:"block,omitempty"`
	ID       string         `json:"id,omitempty"`
	ShardID  string         `json:"shard_id,omitempty"`
	Data     map[string]any `json:"data,omitempty"`
	Filters  []Filter       `json:"filters,omitempty"`
	UpdateOp *UpdateOp      `json:"update_op,omitempty"`
	TxID     string         `json:"tx_id,omitempty"`
}

func NewRaftFSM(engine *Engine) *RaftFSM {
	return &RaftFSM{engine: engine}
}

func (f *RaftFSM) Apply(raftLog *raft.Log) interface{} {
	var cmd RaftCommand
	if err := json.Unmarshal(raftLog.Data, &cmd); err != nil {
		log().Error("Failed to unmarshal Raft command", zap.Error(err))
		return err
	}

	f.mu.Lock()
	defer f.mu.Unlock()

	metricRaftCommits.Inc()

	start := time.Now()
	var result interface{}
	var err error

	switch cmd.Op {
	case "insert":
		result, err = f.engine.insertWithIDLocal(cmd.DB, cmd.Block, cmd.ID, cmd.Data, cmd.ShardID)
	case "update":
		if cmd.UpdateOp != nil {
			result, err = f.engine.updateLocal(cmd.DB, cmd.Block, cmd.Filters, *cmd.UpdateOp, cmd.ShardID)
		}
	case "delete":
		result, err = f.engine.deleteLocal(cmd.DB, cmd.Block, cmd.Filters, cmd.ShardID)
	case "create_db":
		err = f.engine.createDBLocal(cmd.DB)
	case "drop_db":
		err = f.engine.dropDBLocal(cmd.DB)
	case "create_block":
		err = f.engine.createBlockLocal(cmd.DB, cmd.Block)
	case "drop_block":
		err = f.engine.dropBlockLocal(cmd.DB, cmd.Block)
	case "rename_block":
		err = f.engine.renameBlockLocal(cmd.DB, cmd.Block, cmd.ID)
	default:
		log().Warn("Unknown Raft command", zap.String("op", cmd.Op))
		return fmt.Errorf("unknown operation: %s", cmd.Op)
	}

	if err != nil {
		log().Error("Raft operation failed",
			zap.String("op", cmd.Op),
			zap.String("db", cmd.DB),
			zap.Error(err))
		return err
	}

	metricOpsDuration.WithLabelValues(cmd.Op, cmd.DB, cmd.Block, cmd.ShardID, f.engine.nodeID).
		Observe(time.Since(start).Seconds())

	return result
}

func (f *RaftFSM) Snapshot() (raft.FSMSnapshot, error) {
	f.mu.RLock()
	defer f.mu.RUnlock()

	snapshot := &RaftSnapshot{
		engine: f.engine,
		data:   make(map[string][]byte),
	}

	dbs, err := f.engine.ShowDBs()
	if err != nil {
		return nil, err
	}

	for _, db := range dbs {
		path := f.engine.dirMgr.DBPath(db)
		dbHandle, err := f.engine.pool.openDataPath(path)
		if err != nil {
			continue
		}

		var buf bytes.Buffer
		_, err = dbHandle.Backup(&buf, 0)
		if err != nil {
			continue
		}
		snapshot.data[db] = buf.Bytes()
	}

	return snapshot, nil
}

func (f *RaftFSM) Restore(rc io.ReadCloser) error {
	f.mu.Lock()
	defer f.mu.Unlock()

	var snapshot RaftSnapshot
	if err := json.NewDecoder(rc).Decode(&snapshot); err != nil {
		return err
	}

	for db, data := range snapshot.data {
		path := f.engine.dirMgr.DBPath(db)
		os.RemoveAll(path)
		dbHandle, err := f.engine.pool.openDataPath(path)
		if err != nil {
			return err
		}
		if err := dbHandle.Load(bytes.NewReader(data), 512); err != nil {
			return err
		}
	}

	return nil
}

type RaftSnapshot struct {
	engine *Engine
	data   map[string][]byte
}

func (s *RaftSnapshot) Persist(sink raft.SnapshotSink) error {
	if err := json.NewEncoder(sink).Encode(s.data); err != nil {
		sink.Cancel()
		return err
	}
	return sink.Close()
}

func (s *RaftSnapshot) Release() {}
