// Code generated by splitting main.go. Part of package main.
package novodb

import (
	"fmt"
	"github.com/cespare/xxhash/v2"
	"go.uber.org/zap"
	"sync"
	"sync/atomic"
	"time"
)

type ShardInfo struct {
	ID             string    `json:"id"`
	Nodes          []string  `json:"nodes"`
	Primary        string    `json:"primary"`
	DocCount       int64     `json:"doc_count"`
	SizeBytes      int64     `json:"size_bytes"`
	LastRebalanced time.Time `json:"last_rebalanced"`
	Load           float64   `json:"load"`
	RangeStart     string    `json:"range_start"`
	RangeEnd       string    `json:"range_end"`
	Status         string    `json:"status"`
	LastScanned    time.Time `json:"last_scanned"`
}

type NodeInfo struct {
	ID         string    `json:"id"`
	Address    string    `json:"address"`
	Status     string    `json:"status"`
	DocCount   int64     `json:"doc_count"`
	LastSeen   time.Time `json:"last_seen"`
	Shards     []string  `json:"shards"`
	IsLeader   bool      `json:"is_leader"`
	LoadFactor float64   `json:"load_factor"`
}

type AutoScaleManager struct {
	mu              sync.RWMutex
	scaleHistory    []ScaleEvent
	thresholds      ScaleThresholds
	cooldowns       map[string]time.Time
	currentStrategy ScaleStrategy
}

type ScaleEvent struct {
	Timestamp  time.Time `json:"timestamp"`
	Type       string    `json:"type"`
	DB         string    `json:"db"`
	OldShards  int       `json:"old_shards"`
	NewShards  int       `json:"new_shards"`
	Reason     string    `json:"reason"`
	Successful bool      `json:"successful"`
	NodesAdded int       `json:"nodes_added"`
}

type ScaleThresholds struct {
	MaxDocsPerShard   int64         `json:"max_docs_per_shard"`
	MinDocsPerShard   int64         `json:"min_docs_per_shard"`
	MaxSizePerShard   int64         `json:"max_size_per_shard"`
	SkewThreshold     float64       `json:"skew_threshold"`
	GrowthTrigger     float64       `json:"growth_trigger"`
	ScaleUpCooldown   time.Duration `json:"scale_up_cooldown"`
	ScaleDownCooldown time.Duration `json:"scale_down_cooldown"`
}

type ScaleStrategy struct {
	Name           string  `json:"name"`
	Aggressiveness float64 `json:"aggressiveness"`
	MinShards      int     `json:"min_shards"`
	MaxShards      int     `json:"max_shards"`
}

func NewAutoScaleManager() *AutoScaleManager {
	return &AutoScaleManager{
		scaleHistory: make([]ScaleEvent, 0, 100000),
		cooldowns:    make(map[string]time.Time),
		thresholds: ScaleThresholds{
			MaxDocsPerShard:   shardMaxDocs,
			MinDocsPerShard:   shardMinDocs,
			MaxSizePerShard:   shardMaxSizeBytes,
			SkewThreshold:     0.25,
			GrowthTrigger:     1.2,
			ScaleUpCooldown:   60 * time.Second,
			ScaleDownCooldown: 300 * time.Second,
		},
		currentStrategy: ScaleStrategy{
			Name:           "aggressive",
			Aggressiveness: 2.0,
			MinShards:      4,
			MaxShards:      1000000,
		},
	}
}

type ShardManager struct {
	mu           sync.RWMutex
	shards       map[string]*ShardInfo
	nodeShards   map[string][]string
	shardCount   int
	replicaCount int
	nodeID       string
	engine       *IntelligentEngine
	clusterNodes map[string]*NodeInfo
	autoDiscover bool
	scaleManager *AutoScaleManager
	config       *Config
	stopChan     chan struct{}
}

func NewShardManager(nodeID string, config *Config, engine *IntelligentEngine) *ShardManager {
	shardCount := config.ShardCount
	if shardCount < 4 {
		shardCount = 4
	}
	sm := &ShardManager{
		shards:       make(map[string]*ShardInfo),
		nodeShards:   make(map[string][]string),
		shardCount:   shardCount,
		replicaCount: config.ReplicaCount,
		nodeID:       nodeID,
		engine:       engine,
		clusterNodes: make(map[string]*NodeInfo),
		autoDiscover: true,
		scaleManager: NewAutoScaleManager(),
		config:       config,
		stopChan:     make(chan struct{}),
	}
	sm.InitializeShards()
	go sm.scaleLoop()
	return sm
}

func (sm *ShardManager) InitializeShards() {
	sm.shards = make(map[string]*ShardInfo)
	sm.nodeShards = make(map[string][]string)

	for i := 0; i < sm.shardCount; i++ {
		shardID := fmt.Sprintf("shard_%d", i)
		rangeStart := fmt.Sprintf("%08x", i*int(0xFFFFFFFF/uint32(sm.shardCount)))
		rangeEnd := fmt.Sprintf("%08x", (i+1)*int(0xFFFFFFFF/uint32(sm.shardCount))-1)

		sm.shards[shardID] = &ShardInfo{
			ID:             shardID,
			Nodes:          []string{sm.nodeID},
			Primary:        sm.nodeID,
			DocCount:       0,
			SizeBytes:      0,
			LastRebalanced: time.Now(),
			Load:           0,
			RangeStart:     rangeStart,
			RangeEnd:       rangeEnd,
			Status:         "active",
			LastScanned:    time.Now(),
		}
		sm.nodeShards[sm.nodeID] = append(sm.nodeShards[sm.nodeID], shardID)
	}

	sm.clusterNodes[sm.nodeID] = &NodeInfo{
		ID:         sm.nodeID,
		Status:     "active",
		DocCount:   0,
		LastSeen:   time.Now(),
		Shards:     sm.nodeShards[sm.nodeID],
		IsLeader:   true,
		LoadFactor: 0,
	}
}

func (sm *ShardManager) scaleLoop() {
	ticker := time.NewTicker(scaleCheckInterval)
	defer ticker.Stop()

	for {
		select {
		case <-ticker.C:
			sm.checkAndScale()
		case <-sm.stopChan:
			return
		}
	}
}

func (sm *ShardManager) checkAndScale() {
	sm.mu.RLock()
	totalDocs := int64(0)
	for _, shard := range sm.shards {
		totalDocs += shard.DocCount
	}
	shardCount := sm.shardCount
	sm.mu.RUnlock()

	if totalDocs == 0 {
		return
	}

	docsPerShard := totalDocs / int64(shardCount)

	if docsPerShard > sm.config.MaxShardDocs && sm.config.AutoSplitEnabled {
		newShards := shardCount * 2
		if newShards <= sm.config.MaxShardsPerNode {
			sm.scaleUp(newShards)
		}
	} else if docsPerShard < sm.config.MinShardDocs && sm.config.AutoMergeEnabled {
		newShards := shardCount / 2
		if newShards >= 4 {
			sm.scaleDown(newShards)
		}
	}
}

func (sm *ShardManager) scaleUp(newShards int) {
	if sm.isInCooldown("scale_up") {
		return
	}

	sm.mu.Lock()
	defer sm.mu.Unlock()

	log().Info("Scaling up shards",
		zap.Int("old", sm.shardCount),
		zap.Int("new", newShards))

	sm.shardCount = newShards
	sm.InitializeShards()
	sm.setCooldown("scale_up")

	metricAutoScaleEvents.Inc()
}

func (sm *ShardManager) scaleDown(newShards int) {
	if sm.isInCooldown("scale_down") {
		return
	}

	sm.mu.Lock()
	defer sm.mu.Unlock()

	log().Info("Scaling down shards",
		zap.Int("old", sm.shardCount),
		zap.Int("new", newShards))

	sm.shardCount = newShards
	sm.InitializeShards()
	sm.setCooldown("scale_down")

	metricAutoScaleEvents.Inc()
}

func (sm *ShardManager) isInCooldown(action string) bool {
	sm.mu.RLock()
	defer sm.mu.RUnlock()

	if cooldown, ok := sm.scaleManager.cooldowns[action]; ok {
		if time.Since(cooldown) < sm.scaleManager.thresholds.ScaleUpCooldown {
			return true
		}
	}
	return false
}

func (sm *ShardManager) setCooldown(action string) {
	sm.scaleManager.cooldowns[action] = time.Now()
}

func (sm *ShardManager) GetShardForKey(key string) string {
	hash := xxhash.Sum64String(key)
	shardIdx := int(hash) % sm.shardCount
	return fmt.Sprintf("shard_%d", shardIdx)
}

func (sm *ShardManager) GetShardForDoc(db, block, id string) string {
	key := fmt.Sprintf("%s/%s/%s", db, block, id)
	return sm.GetShardForKey(key)
}

func (sm *ShardManager) GetShardsForFilter(db, block string, filters []Filter) []string {
	sm.mu.RLock()
	defer sm.mu.RUnlock()

	if len(filters) == 0 {
		allShards := make([]string, 0, len(sm.shards))
		for id := range sm.shards {
			allShards = append(allShards, id)
		}
		return allShards
	}

	for _, filter := range filters {
		if filter.Field == "_id" && (filter.Op == "=" || filter.Op == "==") {
			shardID := sm.GetShardForKey(fmt.Sprintf("%s/%s/%s", db, block, fmt.Sprint(filter.Value)))
			return []string{shardID}
		}
		if filter.Field == "_shard_id" && filter.Op == "=" {
			return []string{fmt.Sprint(filter.Value)}
		}
	}

	allShards := make([]string, 0, len(sm.shards))
	for id := range sm.shards {
		allShards = append(allShards, id)
	}
	return allShards
}

func (sm *ShardManager) IsShardLocal(shardID string) bool {
	sm.mu.RLock()
	defer sm.mu.RUnlock()
	shard, ok := sm.shards[shardID]
	if !ok {
		return false
	}
	for _, node := range shard.Nodes {
		if node == sm.nodeID {
			return true
		}
	}
	return false
}

func (sm *ShardManager) IsShardPrimary(shardID string) bool {
	sm.mu.RLock()
	defer sm.mu.RUnlock()
	shard, ok := sm.shards[shardID]
	if !ok {
		return false
	}
	return shard.Primary == sm.nodeID
}

func (sm *ShardManager) GetShardNodes(shardID string) []string {
	sm.mu.RLock()
	defer sm.mu.RUnlock()
	shard, ok := sm.shards[shardID]
	if !ok {
		return nil
	}
	return shard.Nodes
}

func (sm *ShardManager) GetShardPrimary(shardID string) string {
	sm.mu.RLock()
	defer sm.mu.RUnlock()
	shard, ok := sm.shards[shardID]
	if !ok {
		return ""
	}
	return shard.Primary
}

func (sm *ShardManager) GetAllShards() []string {
	sm.mu.RLock()
	defer sm.mu.RUnlock()
	shards := make([]string, 0, len(sm.shards))
	for id := range sm.shards {
		shards = append(shards, id)
	}
	return shards
}

func (sm *ShardManager) GetShardStats(shardID string) *ShardInfo {
	sm.mu.RLock()
	defer sm.mu.RUnlock()
	if shard, ok := sm.shards[shardID]; ok {
		return &ShardInfo{
			ID:             shard.ID,
			Nodes:          append([]string{}, shard.Nodes...),
			Primary:        shard.Primary,
			DocCount:       shard.DocCount,
			SizeBytes:      shard.SizeBytes,
			LastRebalanced: shard.LastRebalanced,
			Load:           shard.Load,
			RangeStart:     shard.RangeStart,
			RangeEnd:       shard.RangeEnd,
			Status:         shard.Status,
			LastScanned:    shard.LastScanned,
		}
	}
	return nil
}

func (sm *ShardManager) UpdateShardStats(shardID string, docCount, sizeBytes int64) {
	sm.mu.Lock()
	defer sm.mu.Unlock()
	if shard, ok := sm.shards[shardID]; ok {
		atomic.AddInt64(&shard.DocCount, docCount)
		atomic.AddInt64(&shard.SizeBytes, sizeBytes)
		shard.Load = float64(shard.DocCount) / float64(sm.config.MaxShardDocs)
	}
}

func (sm *ShardManager) HandleNodeFailure(nodeID string) {
	sm.mu.Lock()
	defer sm.mu.Unlock()

	if nodeInfo, ok := sm.clusterNodes[nodeID]; ok {
		nodeInfo.Status = "dead"
		nodeInfo.LastSeen = time.Now()
	}

	for shardID, shard := range sm.shards {
		if shard.Primary == nodeID {
			var newPrimary string
			for _, node := range shard.Nodes {
				if node != nodeID {
					if nodeInfo, ok := sm.clusterNodes[node]; ok && nodeInfo.Status == "active" {
						newPrimary = node
						break
					}
				}
			}
			if newPrimary != "" {
				shard.Primary = newPrimary
				log().Info("Elected new primary for shard after node failure",
					zap.String("shard", shardID),
					zap.String("new_primary", newPrimary),
					zap.String("failed_node", nodeID))
			} else {
				shard.Status = "degraded"
				log().Warn("Shard has no available primary after node failure",
					zap.String("shard", shardID),
					zap.String("failed_node", nodeID))
			}
		}
	}
}

func (sm *ShardManager) AddNodeToShards(nodeID string) {
	sm.mu.Lock()
	defer sm.mu.Unlock()

	if _, exists := sm.clusterNodes[nodeID]; !exists {
		sm.clusterNodes[nodeID] = &NodeInfo{
			ID:       nodeID,
			Status:   "joining",
			LastSeen: time.Now(),
			Shards:   []string{},
		}
	}

	for _, shard := range sm.shards {
		exists := false
		for _, n := range shard.Nodes {
			if n == nodeID {
				exists = true
				break
			}
		}
		if !exists && len(shard.Nodes) < sm.replicaCount {
			shard.Nodes = append(shard.Nodes, nodeID)
			sm.nodeShards[nodeID] = append(sm.nodeShards[nodeID], shard.ID)
		}
	}

	if nodeInfo, ok := sm.clusterNodes[nodeID]; ok {
		nodeInfo.Shards = sm.nodeShards[nodeID]
		nodeInfo.Status = "active"
		nodeInfo.LastSeen = time.Now()
	}

	sm.BalanceShards()
}

func (sm *ShardManager) RemoveNodeFromShards(nodeID string) {
	sm.mu.Lock()
	defer sm.mu.Unlock()

	for _, shard := range sm.shards {
		newNodes := make([]string, 0, len(shard.Nodes))
		for _, n := range shard.Nodes {
			if n != nodeID {
				newNodes = append(newNodes, n)
			}
		}
		shard.Nodes = newNodes
		if shard.Primary == nodeID && len(shard.Nodes) > 0 {
			shard.Primary = shard.Nodes[0]
		}
	}
	delete(sm.nodeShards, nodeID)
	if nodeInfo, ok := sm.clusterNodes[nodeID]; ok {
		nodeInfo.Status = "leaving"
	}
	sm.BalanceShards()
}

func (sm *ShardManager) BalanceShards() {
	sm.mu.Lock()
	defer sm.mu.Unlock()

	totalShards := len(sm.shards)
	if totalShards == 0 {
		return
	}

	nodeCount := make(map[string]int)
	totalDocs := int64(0)
	for _, shard := range sm.shards {
		for _, node := range shard.Nodes {
			nodeCount[node]++
		}
		totalDocs += shard.DocCount
	}

	avgDocs := float64(0)
	if len(nodeCount) > 0 {
		avgDocs = float64(totalDocs) / float64(len(nodeCount))
	}
	avgShards := totalShards / len(nodeCount)
	if avgShards < 1 {
		avgShards = 1
	}

	for node, count := range nodeCount {
		if count > avgShards*2 {
			toMove := count - avgShards
			for _, shard := range sm.shards {
				if toMove <= 0 {
					break
				}
				if shard.Primary == node && len(shard.Nodes) > 1 {
					for otherNode, otherCount := range nodeCount {
						if otherNode != node && otherCount < avgShards {
							nodeDocs := int64(0)
							for _, s := range sm.shards {
								for _, n := range s.Nodes {
									if n == otherNode {
										nodeDocs += s.DocCount
									}
								}
							}
							if float64(nodeDocs) < avgDocs {
								shard.Nodes = append(shard.Nodes, otherNode)
								nodeCount[otherNode]++
								toMove--
								break
							}
						}
					}
				}
			}
		}
	}
}

func (sm *ShardManager) calculateSkew() float64 {
	if len(sm.shards) == 0 {
		return 0
	}

	var maxDocs int64
	var minDocs int64 = -1
	var totalDocs int64

	for _, shard := range sm.shards {
		totalDocs += shard.DocCount
		if shard.DocCount > maxDocs {
			maxDocs = shard.DocCount
		}
		if minDocs == -1 || shard.DocCount < minDocs {
			minDocs = shard.DocCount
		}
	}

	if totalDocs == 0 {
		return 0
	}

	ideal := totalDocs / int64(len(sm.shards))
	if ideal == 0 {
		return 0
	}

	return float64(maxDocs-minDocs) / float64(ideal)
}

func (sm *ShardManager) totalDocs() int64 {
	sm.mu.RLock()
	defer sm.mu.RUnlock()
	var total int64
	for _, shard := range sm.shards {
		total += shard.DocCount
	}
	return total
}

func (sm *ShardManager) Close() {
	close(sm.stopChan)
}
