// Code generated by splitting main.go. Part of package main.
package novodb

import (
	"fmt"
	"sort"
	"strings"
)

func sortDocs(docs []Document, sorts []SortField) {
	sort.SliceStable(docs, func(i, j int) bool {
		for _, s := range sorts {
			vi := getNested(docs[i].Data, s.Field)
			vj := getNested(docs[j].Data, s.Field)
			fi, fj := toF64(vi), toF64(vj)
			cmp := 0
			if fi != 0 || fj != 0 {
				if fi < fj {
					cmp = -1
				} else if fi > fj {
					cmp = 1
				}
			} else {
				cmp = strings.Compare(fmt.Sprint(vi), fmt.Sprint(vj))
			}
			if cmp != 0 {
				if s.Desc {
					return cmp > 0
				}
				return cmp < 0
			}
		}
		return false
	})
}
