// Code generated by splitting main.go. Part of package main.
package novodb

import (
	"os"
	"path/filepath"
	"sync"
)

type ExternalStorage interface {
	Save(data []byte) (string, error)
	Load(id string) ([]byte, error)
	Delete(id string) error
	Exists(id string) bool
}

type FileSystemStorage struct {
	basePath string
	mu       sync.RWMutex
}

func NewFileSystemStorage(basePath string) (*FileSystemStorage, error) {
	if err := os.MkdirAll(basePath, 0750); err != nil {
		return nil, err
	}
	return &FileSystemStorage{basePath: basePath}, nil
}

func (fs *FileSystemStorage) Save(data []byte) (string, error) {
	id := newID()
	path := filepath.Join(fs.basePath, id[:2], id)
	if err := os.MkdirAll(filepath.Dir(path), 0750); err != nil {
		return "", err
	}
	if err := os.WriteFile(path, data, 0640); err != nil {
		return "", err
	}
	return id, nil
}

func (fs *FileSystemStorage) Load(id string) ([]byte, error) {
	path := filepath.Join(fs.basePath, id[:2], id)
	return os.ReadFile(path)
}

func (fs *FileSystemStorage) Delete(id string) error {
	path := filepath.Join(fs.basePath, id[:2], id)
	return os.Remove(path)
}

func (fs *FileSystemStorage) Exists(id string) bool {
	path := filepath.Join(fs.basePath, id[:2], id)
	_, err := os.Stat(path)
	return err == nil
}
