// Code generated by splitting main.go. Part of package main.
package novodb

import (
	"encoding/json"
	"fmt"
	"go.uber.org/zap"
	"sort"
	"sync"
	"time"
)

type Transaction struct {
	ID         string
	DB         string
	Block      string
	Status     string // "pending", "committed", "aborted"
	StartTime  time.Time
	Operations []TxOperation
	Mutations  []TxMutation
	mu         sync.RWMutex
	done       chan struct{}
	Version    int64
}

type TxOperation struct {
	Type    string // "insert", "update", "delete"
	ID      string
	Data    map[string]any
	Filters []Filter
	Update  *UpdateOp
}

type TxMutation struct {
	Key      []byte
	Value    []byte
	Type     string // "set", "delete"
	Document *Document
	OldValue []byte // For rollback
}

type TxManager struct {
	mu           sync.RWMutex
	transactions map[string]*Transaction
	wal          *WAL
	engine       *Engine
	timeout      time.Duration
	maxRetries   int
	stopChan     chan struct{}
	cleanupTick  *time.Ticker
	isolation    string // "read_committed", "repeatable_read", "serializable"
}

func NewTxManager(engine *Engine, wal *WAL, timeout time.Duration) *TxManager {
	if timeout == 0 {
		timeout = defaultTransactionTimeout * time.Second
	}
	tm := &TxManager{
		transactions: make(map[string]*Transaction),
		engine:       engine,
		wal:          wal,
		timeout:      timeout,
		maxRetries:   3,
		stopChan:     make(chan struct{}),
		cleanupTick:  time.NewTicker(30 * time.Second),
		isolation:    "repeatable_read",
	}
	go tm.cleanupLoop()
	return tm
}

func (tm *TxManager) Begin(dbName, block string) (*Transaction, error) {
	if dbName == "" {
		return nil, fmt.Errorf("database name is required")
	}

	tx := &Transaction{
		ID:         newID(),
		DB:         dbName,
		Block:      block,
		Status:     "pending",
		StartTime:  time.Now(),
		Operations: make([]TxOperation, 0),
		Mutations:  make([]TxMutation, 0),
		done:       make(chan struct{}),
		Version:    1,
	}

	tm.mu.Lock()
	tm.transactions[tx.ID] = tx
	tm.mu.Unlock()

	log().Info("Transaction started",
		zap.String("tx_id", tx.ID),
		zap.String("db", dbName),
		zap.String("block", block),
		zap.String("isolation", tm.isolation))

	return tx, nil
}

func (tm *TxManager) Commit(tx *Transaction) error {
	tx.mu.Lock()
	defer tx.mu.Unlock()

	if tx.Status != "pending" {
		return fmt.Errorf("transaction already %s", tx.Status)
	}

	if len(tx.Mutations) == 0 {
		tx.Status = "committed"
		close(tx.done)
		return nil
	}

	log().Info("Committing transaction",
		zap.String("tx_id", tx.ID),
		zap.Int("mutations", len(tx.Mutations)))

	var err error
	for retry := 0; retry < tm.maxRetries; retry++ {
		err = tm.applyMutations(tx)
		if err == nil {
			break
		}
		if retry < tm.maxRetries-1 {
			log().Warn("Transaction commit retry",
				zap.String("tx_id", tx.ID),
				zap.Int("retry", retry+1),
				zap.Error(err))
			time.Sleep(time.Duration(retry+1) * 100 * time.Millisecond)
		}
	}

	if err != nil {
		tx.Status = "aborted"
		return fmt.Errorf("commit failed after %d retries: %w", tm.maxRetries, err)
	}

	if tm.wal != nil {
		walData, _ := json.Marshal(map[string]interface{}{
			"tx_id":     tx.ID,
			"mutations": tx.Mutations,
			"db":        tx.DB,
			"block":     tx.Block,
			"timestamp": time.Now().Unix(),
		})
		if err := tm.wal.Write("tx_commit", tx.DB, tx.Block, walData); err != nil {
			log().Error("WAL commit failed", zap.Error(err))
		}
		if err := tm.wal.Sync(); err != nil {
			log().Error("WAL sync failed", zap.Error(err))
		}
	}

	tx.Status = "committed"
	close(tx.done)

	metricTransactionCommits.Inc()

	if stats, ok := tm.engine.intelEngine.stats[tx.DB]; ok {
		stats.LastOptimized = time.Now()
	}

	log().Info("Transaction committed successfully",
		zap.String("tx_id", tx.ID),
		zap.Duration("duration", time.Since(tx.StartTime)))

	return nil
}

func (tm *TxManager) Abort(tx *Transaction) error {
	tx.mu.Lock()
	defer tx.mu.Unlock()

	if tx.Status != "pending" {
		return fmt.Errorf("transaction already %s", tx.Status)
	}

	tx.Status = "aborted"
	close(tx.done)

	tm.releaseLocks(tx)

	metricTransactionRollbacks.Inc()

	log().Info("Transaction aborted",
		zap.String("tx_id", tx.ID),
		zap.Duration("duration", time.Since(tx.StartTime)))

	return nil
}

func (tm *TxManager) applyMutations(tx *Transaction) error {
	db, err := tm.engine.pool.openBlock(tx.DB, tx.Block)
	if err != nil {
		return err
	}

	lockKeys := make([]string, len(tx.Mutations))
	for i, m := range tx.Mutations {
		lockKeys[i] = string(m.Key)
	}
	sort.Strings(lockKeys)

	for _, key := range lockKeys {
		tm.engine.lockManager.Lock(key)
	}

	defer func() {
		for _, key := range lockKeys {
			tm.engine.lockManager.Unlock(key)
		}
	}()

	for _, m := range tx.Mutations {
		if err := tm.validateMutation(tx, m); err != nil {
			return err
		}
	}

	wb := db.NewWriteBatch()
	defer wb.Cancel()

	for _, m := range tx.Mutations {
		if m.Type == "set" {
			if err := wb.Set(m.Key, m.Value); err != nil {
				return err
			}
			if m.Document != nil {
				cacheKey := tm.engine.cacheKey(tx.DB, tx.Block, m.Document.ID)
				tm.engine.l1Cache.set(cacheKey, m.Value)
			}
		} else if m.Type == "delete" {
			if err := wb.Delete(m.Key); err != nil {
				return err
			}
			if m.Document != nil {
				cacheKey := tm.engine.cacheKey(tx.DB, tx.Block, m.Document.ID)
				tm.engine.l1Cache.del(cacheKey)
			}
		}
	}

	if err := wb.Flush(); err != nil {
		return err
	}

	for _, m := range tx.Mutations {
		if m.Document != nil && m.Type == "set" {
			if err := tm.engine.buildSecondaryIndex(tx.DB, tx.Block, m.Document); err != nil {
				log().Warn("Failed to build index in transaction", zap.Error(err))
			}
			// Update FLEX-COLUMN
			if tm.engine.flexEngine != nil {
				tm.engine.flexEngine.InsertWithColumnar(tx.DB, tx.Block, m.Document)
			}
		}
	}

	for _, m := range tx.Mutations {
		if m.Document != nil {
			tm.engine.shardMgr.UpdateShardStats(m.Document.ShardID, 1, int64(len(m.Value)))
		}
	}

	return nil
}

func (tm *TxManager) validateMutation(tx *Transaction, m TxMutation) error {
	switch tm.isolation {
	case "read_committed":
		return tm.validateReadCommitted(tx, m)
	case "repeatable_read":
		return tm.validateRepeatableRead(tx, m)
	case "serializable":
		return tm.validateSerializable(tx, m)
	default:
		return tm.validateRepeatableRead(tx, m)
	}
}

func (tm *TxManager) validateReadCommitted(tx *Transaction, m TxMutation) error {
	if m.Document == nil {
		return nil
	}

	existing, ok := tm.engine.FindByID(tx.DB, tx.Block, m.Document.ID)
	if ok && m.Type == "set" {
		if existing.Meta.Version > m.Document.Meta.Version {
			return fmt.Errorf("version conflict: document %s was modified", m.Document.ID)
		}
	}
	return nil
}

func (tm *TxManager) validateRepeatableRead(tx *Transaction, m TxMutation) error {
	return tm.validateReadCommitted(tx, m)
}

func (tm *TxManager) validateSerializable(tx *Transaction, m TxMutation) error {
	if m.Document == nil {
		return nil
	}

	tm.mu.RLock()
	defer tm.mu.RUnlock()

	for id, otherTx := range tm.transactions {
		if id == tx.ID || otherTx.Status != "pending" {
			continue
		}
		for _, om := range otherTx.Mutations {
			if om.Document != nil && om.Document.ID == m.Document.ID {
				return fmt.Errorf("serializable conflict: document %s is being modified by transaction %s",
					m.Document.ID, id)
			}
		}
	}
	return nil
}

func (tm *TxManager) releaseLocks(tx *Transaction) {
	lockKeys := make([]string, 0)
	for _, m := range tx.Mutations {
		lockKeys = append(lockKeys, string(m.Key))
	}
	sort.Strings(lockKeys)
	for _, key := range lockKeys {
		tm.engine.lockManager.Unlock(key)
	}
}

func (tm *TxManager) cleanupLoop() {
	for {
		select {
		case <-tm.cleanupTick.C:
			tm.cleanupExpired()
		case <-tm.stopChan:
			return
		}
	}
}

func (tm *TxManager) cleanupExpired() {
	tm.mu.Lock()
	defer tm.mu.Unlock()

	now := time.Now()
	for id, tx := range tm.transactions {
		if tx.Status == "pending" && now.Sub(tx.StartTime) > tm.timeout {
			log().Warn("Transaction expired, aborting",
				zap.String("tx_id", id),
				zap.Duration("age", now.Sub(tx.StartTime)))
			go tm.Abort(tx)
		}
		if tx.Status != "pending" && now.Sub(tx.StartTime) > time.Hour {
			delete(tm.transactions, id)
		}
	}
}

func (tm *TxManager) Insert(tx *Transaction, data map[string]any) (*Document, error) {
	tx.mu.Lock()
	defer tx.mu.Unlock()

	if tx.Status != "pending" {
		return nil, fmt.Errorf("transaction not active")
	}

	id := newID()
	doc := &Document{
		ID:   id,
		Data: data,
		Meta: DocMeta{
			CreatedAt: time.Now().Unix(),
			UpdatedAt: time.Now().Unix(),
			Version:   1,
		},
		ShardID: tm.engine.shardMgr.GetShardForDoc(tx.DB, tx.Block, id),
	}

	raw, err := json.Marshal(doc)
	if err != nil {
		return nil, err
	}

	if int64(len(raw)) > tm.engine.config.MaxDocumentSize {
		return nil, fmt.Errorf("%w: %d bytes", ErrDocTooLarge, len(raw))
	}

	if tm.engine.externalStore != nil && int64(len(raw)) > tm.engine.config.LargeDocThreshold {
		largeID, err := tm.engine.externalStore.Save(raw)
		if err != nil {
			return nil, err
		}
		doc.LargeID = largeID
		raw, _ = json.Marshal(doc)
	}

	if tm.engine.config.CompressLargeDocs && int64(len(raw)) > tm.engine.config.CompressThreshold {
		if comp, ok, err := compressData(raw, CompressionZstd); err == nil && ok {
			raw = comp
		}
	}

	tx.Mutations = append(tx.Mutations, TxMutation{
		Key:      docKey(tx.Block, id),
		Value:    raw,
		Type:     "set",
		Document: doc,
	})

	tx.Operations = append(tx.Operations, TxOperation{
		Type: "insert",
		ID:   id,
		Data: data,
	})

	metricDocSize.Observe(float64(len(raw)))

	return doc, nil
}

func (tm *TxManager) Update(tx *Transaction, filters []Filter, op UpdateOp) (int64, error) {
	tx.mu.Lock()
	defer tx.mu.Unlock()

	if tx.Status != "pending" {
		return 0, fmt.Errorf("transaction not active")
	}

	result, err := tm.engine.Find(tx.DB, tx.Block, &Query{
		Filters: filters,
		Limit:   10000,
	})
	if err != nil {
		return 0, err
	}

	if len(result.Docs) == 0 {
		return 0, nil
	}

	updated := 0
	for _, doc := range result.Docs {
		if tm.isModified(tx, doc.ID) {
			continue
		}

		oldRaw, _ := json.Marshal(doc)

		applyUpdateOp(&doc, op)
		doc.Meta.UpdatedAt = time.Now().Unix()
		doc.Meta.Version++

		newRaw, err := json.Marshal(doc)
		if err != nil {
			continue
		}

		if tm.engine.externalStore != nil && int64(len(newRaw)) > tm.engine.config.LargeDocThreshold {
			largeID, err := tm.engine.externalStore.Save(newRaw)
			if err != nil {
				continue
			}
			doc.LargeID = largeID
			newRaw, _ = json.Marshal(doc)
		}

		if tm.engine.config.CompressLargeDocs && int64(len(newRaw)) > tm.engine.config.CompressThreshold {
			if comp, ok, err := compressData(newRaw, CompressionZstd); err == nil && ok {
				newRaw = comp
			}
		}

		tx.Mutations = append(tx.Mutations, TxMutation{
			Key:      docKey(tx.Block, doc.ID),
			Value:    newRaw,
			Type:     "set",
			Document: &doc,
			OldValue: oldRaw,
		})

		updated++
	}

	return int64(updated), nil
}

func (tm *TxManager) Delete(tx *Transaction, filters []Filter) (int64, error) {
	tx.mu.Lock()
	defer tx.mu.Unlock()

	if tx.Status != "pending" {
		return 0, fmt.Errorf("transaction not active")
	}

	result, err := tm.engine.Find(tx.DB, tx.Block, &Query{
		Filters: filters,
		Limit:   10000,
	})
	if err != nil {
		return 0, err
	}

	if len(result.Docs) == 0 {
		return 0, nil
	}

	deleted := 0
	for _, doc := range result.Docs {
		if tm.isModified(tx, doc.ID) {
			continue
		}

		oldRaw, _ := json.Marshal(doc)

		if doc.LargeID != "" && tm.engine.externalStore != nil {
			tm.engine.externalStore.Delete(doc.LargeID)
		}

		tx.Mutations = append(tx.Mutations, TxMutation{
			Key:      docKey(tx.Block, doc.ID),
			Type:     "delete",
			Document: &doc,
			OldValue: oldRaw,
		})

		deleted++
	}

	return int64(deleted), nil
}

func (tm *TxManager) isModified(tx *Transaction, docID string) bool {
	for _, m := range tx.Mutations {
		if m.Document != nil && m.Document.ID == docID {
			return true
		}
	}
	return false
}

func (tm *TxManager) GetTx(id string) (*Transaction, bool) {
	tm.mu.RLock()
	defer tm.mu.RUnlock()
	tx, ok := tm.transactions[id]
	return tx, ok
}

func (tm *TxManager) GetActiveTransactions() []string {
	tm.mu.RLock()
	defer tm.mu.RUnlock()
	active := make([]string, 0)
	for id, tx := range tm.transactions {
		if tx.Status == "pending" {
			active = append(active, id)
		}
	}
	return active
}

func (tm *TxManager) Stats() map[string]any {
	tm.mu.RLock()
	defer tm.mu.RUnlock()

	active := 0
	committed := 0
	aborted := 0

	for _, tx := range tm.transactions {
		switch tx.Status {
		case "pending":
			active++
		case "committed":
			committed++
		case "aborted":
			aborted++
		}
	}

	return map[string]any{
		"active":    active,
		"committed": committed,
		"aborted":   aborted,
		"total":     len(tm.transactions),
		"timeout":   tm.timeout.String(),
		"isolation": tm.isolation,
	}
}

func (tm *TxManager) Close() {
	close(tm.stopChan)
	if tm.cleanupTick != nil {
		tm.cleanupTick.Stop()
	}
}
