// Code generated by splitting main.go. Part of package main.
package novodb

import (
	"crypto/rand"
	"crypto/subtle"
	"encoding/hex"
	"encoding/json"
	"fmt"
	badger "github.com/dgraph-io/badger/v4"
	"go.uber.org/zap"
	"golang.org/x/crypto/argon2"
	"time"
)

type User struct {
	Username  string `json:"username"`
	PassHash  string `json:"pass_hash"`
	Salt      string `json:"salt"`
	Role      string `json:"role"`
	CreatedAt int64  `json:"created_at"`
	Locked    bool   `json:"locked"`
	LockedAt  int64  `json:"locked_at"`
	Attempts  int    `json:"attempts"`
}

func hashPassword(password, saltHex string) string {
	salt, err := hex.DecodeString(saltHex)
	if err != nil {
		salt = []byte(saltHex)
	}
	hash := argon2.IDKey([]byte(password), salt, argonTime, argonMemory, argonThreads, argonKeyLen)
	return hex.EncodeToString(hash)
}

func generateSalt() string {
	salt := make([]byte, argonSaltLen)
	rand.Read(salt)
	return hex.EncodeToString(salt)
}

func verifyPassword(password, saltHex, stored string) bool {
	salt, err := hex.DecodeString(saltHex)
	if err != nil {
		salt = []byte(saltHex)
	}
	hash := argon2.IDKey([]byte(password), salt, argonTime, argonMemory, argonThreads, argonKeyLen)
	return subtle.ConstantTimeCompare([]byte(hex.EncodeToString(hash)), []byte(stored)) == 1
}

func (e *Engine) usersDB() (*badger.DB, error) {
	return e.pool.openUserDB()
}

func (e *Engine) CreateUser(username, password, role string) error {
	if err := validateName(username); err != nil {
		return err
	}
	if len(password) < 6 {
		return fmt.Errorf("password must be at least 6 characters")
	}
	if role == "" {
		role = "readwrite"
	}
	saltHex := generateSalt()
	u := User{
		Username:  username,
		PassHash:  hashPassword(password, saltHex),
		Salt:      saltHex,
		Role:      role,
		CreatedAt: time.Now().Unix(),
	}
	raw, _ := json.Marshal(u)
	db, err := e.usersDB()
	if err != nil {
		return err
	}

	err = txHelper.SafeUpdate(db, func(txn *badger.Txn) error {
		return txn.Set([]byte("u/"+username), raw)
	})

	if err == nil {
		log().Info("User created", zap.String("username", username), zap.String("role", role))
		if e.auditLogger != nil {
			e.auditLogger.Log(AuditLog{
				UserID:   "system",
				Username: "system",
				Action:   "create_user",
				Status:   "success",
				Message:  fmt.Sprintf("user=%s role=%s", username, role),
			})
		}
	}
	return err
}

func (e *Engine) DropUser(username string) error {
	db, err := e.usersDB()
	if err != nil {
		return err
	}

	err = txHelper.SafeUpdate(db, func(txn *badger.Txn) error {
		return txn.Delete([]byte("u/" + username))
	})

	if err == nil {
		log().Info("User dropped", zap.String("username", username))
		if e.auditLogger != nil {
			e.auditLogger.Log(AuditLog{
				UserID:   "system",
				Username: "system",
				Action:   "drop_user",
				Status:   "success",
				Message:  fmt.Sprintf("user=%s", username),
			})
		}
	}
	return err
}

func (e *Engine) ShowUsers() ([]map[string]any, error) {
	db, err := e.usersDB()
	if err != nil {
		return nil, err
	}
	var users []map[string]any

	err = txHelper.SafeView(db, func(txn *badger.Txn) error {
		opts := badger.DefaultIteratorOptions
		it := txn.NewIterator(opts)
		defer it.Close()
		for it.Seek([]byte("u/")); it.ValidForPrefix([]byte("u/")); it.Next() {
			item := it.Item()
			if item == nil {
				continue
			}
			var u User
			item.Value(func(v []byte) error { return json.Unmarshal(v, &u) })
			users = append(users, map[string]any{
				"username":   u.Username,
				"role":       u.Role,
				"created_at": u.CreatedAt,
				"locked":     u.Locked,
			})
		}
		return nil
	})

	if err != nil {
		return nil, err
	}
	return users, nil
}

func (e *Engine) AuthUser(username, password string) (bool, string) {
	db, err := e.usersDB()
	if err != nil {
		metricAuthFailures.Inc()
		return false, ""
	}
	var u User

	err = txHelper.SafeView(db, func(txn *badger.Txn) error {
		item, err := txn.Get([]byte("u/" + username))
		if err != nil {
			return err
		}
		return item.Value(func(v []byte) error { return json.Unmarshal(v, &u) })
	})

	if err != nil {
		metricAuthFailures.Inc()
		return false, ""
	}

	if u.Locked {
		if time.Now().Unix()-u.LockedAt > int64(e.config.LockoutDuration.Seconds()) {
			u.Locked = false
			u.Attempts = 0
			txHelper.SafeUpdate(db, func(txn *badger.Txn) error {
				raw, _ := json.Marshal(u)
				return txn.Set([]byte("u/"+username), raw)
			})
		} else {
			return false, ""
		}
	}

	if !verifyPassword(password, u.Salt, u.PassHash) {
		u.Attempts++
		if u.Attempts >= e.config.MaxLoginAttempts {
			u.Locked = true
			u.LockedAt = time.Now().Unix()
		}
		txHelper.SafeUpdate(db, func(txn *badger.Txn) error {
			raw, _ := json.Marshal(u)
			return txn.Set([]byte("u/"+username), raw)
		})
		metricAuthFailures.Inc()
		log().Warn("Authentication failed", zap.String("username", username))
		return false, ""
	}

	if u.Attempts > 0 {
		u.Attempts = 0
		txHelper.SafeUpdate(db, func(txn *badger.Txn) error {
			raw, _ := json.Marshal(u)
			return txn.Set([]byte("u/"+username), raw)
		})
	}

	log().Debug("Authentication successful", zap.String("username", username))
	return true, u.Role
}
