// Code generated by splitting main.go. Part of package main.
package novodb

import (
	"fmt"
	"io"
	"net/url"
	"strings"
	"time"
)

func (e *Engine) vmIndex(dbName, block string, doc *Document) {
	if e.vmURL == "" {
		return
	}
	var sb strings.Builder
	sb.WriteString(fmt.Sprintf(`db="%s",block="%s",id="%s",shard="%s",node="%s"`,
		labelEsc(dbName), labelEsc(block), doc.ID, labelEsc(doc.ShardID), labelEsc(e.nodeID)))
	for k, v := range doc.Data {
		switch v.(type) {
		case string, float64, int, int64, bool:
			sb.WriteString(fmt.Sprintf(`,%s="%s"`, labelEsc(k), labelEsc(fmt.Sprint(v))))
		}
	}
	line := fmt.Sprintf("%s_doc{%s} 1 %d\n", labelEsc(block), sb.String(), time.Now().UnixMilli())

	resp, err := e.vmClient.Post(
		e.vmURL+"/api/v1/import/prometheus",
		"text/plain",
		strings.NewReader(line),
	)
	if err == nil {
		resp.Body.Close()
	}
}

func (e *Engine) VMQuery(q string) (string, error) {
	if e.vmURL == "" {
		return "", fmt.Errorf("VictoriaMetrics not configured")
	}
	resp, err := e.vmClient.Get(e.vmURL + "/api/v1/query?query=" + url.QueryEscape(q))
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()
	b, _ := io.ReadAll(resp.Body)
	return string(b), nil
}
