// Code generated by splitting main.go. Part of package main.
package novodb

import (
	"encoding/json"
	"fmt"
	"go.uber.org/zap"
	"hash/crc32"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"sync"
	"time"
)

type WALEntry struct {
	ID         uint64
	Timestamp  int64
	Op         string
	DB         string
	Block      string
	Data       []byte
	Checksum   uint32
	Compressed bool
}

type WAL struct {
	mu          sync.Mutex
	dir         string
	segments    []string
	currentSeg  *os.File
	currentID   uint64
	maxSize     int64
	maxSegs     int
	encoder     *json.Encoder
	lastClean   time.Time
	clean       bool
	streaming   bool
	stopChan    chan struct{}
	writeChan   chan WALEntry
	wg          sync.WaitGroup
	flushTicker *time.Ticker
	bufferPool  *BufferPool
}

func NewWAL(dir string, maxSegs int, streaming bool) (*WAL, error) {
	if maxSegs <= 0 {
		maxSegs = maxWALSegments
	}
	wal := &WAL{
		dir:         dir,
		maxSize:     walSegmentSize,
		maxSegs:     maxSegs,
		lastClean:   time.Now(),
		clean:       true,
		streaming:   streaming,
		stopChan:    make(chan struct{}),
		writeChan:   make(chan WALEntry, 10000),
		flushTicker: time.NewTicker(5 * time.Second),
		bufferPool:  NewBufferPool(128 << 20),
	}

	if err := os.MkdirAll(dir, 0750); err != nil {
		return nil, err
	}

	if err := wal.recover(); err != nil {
		return nil, err
	}

	wal.wg.Add(1)
	go wal.writeLoop()

	return wal, nil
}

func (w *WAL) writeLoop() {
	defer w.wg.Done()
	var batch []WALEntry

	for {
		select {
		case entry, ok := <-w.writeChan:
			if !ok {
				w.flushBatch(batch)
				return
			}
			batch = append(batch, entry)
			if len(batch) >= 100 {
				w.flushBatch(batch)
				batch = nil
			}
		case <-w.flushTicker.C:
			if len(batch) > 0 {
				w.flushBatch(batch)
				batch = nil
			}
		case <-w.stopChan:
			w.flushBatch(batch)
			return
		}
	}
}

func (w *WAL) flushBatch(batch []WALEntry) {
	if len(batch) == 0 {
		return
	}

	w.mu.Lock()
	defer w.mu.Unlock()

	if w.encoder == nil {
		w.encoder = json.NewEncoder(w.currentSeg)
	}

	buf := w.bufferPool.Get()
	defer w.bufferPool.Put(buf)

	for _, entry := range batch {
		if err := w.encoder.Encode(entry); err != nil {
			log().Error("Failed to write WAL entry", zap.Error(err))
			continue
		}
	}

	stat, err := w.currentSeg.Stat()
	if err != nil {
		log().Error("Failed to stat WAL segment", zap.Error(err))
		return
	}
	if stat.Size() >= w.maxSize {
		if err := w.rotate(); err != nil {
			log().Error("Failed to rotate WAL segment", zap.Error(err))
		}
	}
}

func (w *WAL) recover() error {
	files, err := filepath.Glob(filepath.Join(w.dir, "wal-*.log"))
	if err != nil {
		return err
	}
	sort.Strings(files)

	if len(files) == 0 {
		return w.newSegment()
	}

	w.segments = files
	lastSeg := files[len(files)-1]
	f, err := os.OpenFile(lastSeg, os.O_RDWR|os.O_APPEND, 0640)
	if err != nil {
		return err
	}
	w.currentSeg = f

	base := filepath.Base(lastSeg)
	idStr := strings.TrimPrefix(strings.TrimSuffix(base, ".log"), "wal-")
	w.currentID, _ = strconv.ParseUint(idStr, 10, 64)

	stat, _ := f.Stat()
	if stat.Size() >= w.maxSize {
		return w.rotate()
	}

	w.encoder = json.NewEncoder(f)

	w.checkCleanliness()

	return nil
}

func (w *WAL) checkCleanliness() {
	markerFile := filepath.Join(w.dir, ".clean")
	if _, err := os.Stat(markerFile); err == nil {
		w.clean = true
		log().Info("WAL clean shutdown detected, skipping recovery")
	} else {
		w.clean = false
		log().Info("WAL unclean shutdown detected, will recover on next startup")
	}
}

func (w *WAL) newSegment() error {
	w.currentID++
	fname := filepath.Join(w.dir, fmt.Sprintf("wal-%d.log", w.currentID))
	f, err := os.Create(fname)
	if err != nil {
		return err
	}
	w.currentSeg = f
	w.segments = append(w.segments, fname)
	w.encoder = json.NewEncoder(f)
	return nil
}

func (w *WAL) rotate() error {
	if err := w.currentSeg.Close(); err != nil {
		return err
	}
	if err := w.newSegment(); err != nil {
		return err
	}
	for len(w.segments) > w.maxSegs {
		oldest := w.segments[0]
		os.Remove(oldest)
		w.segments = w.segments[1:]
	}
	return nil
}

func (w *WAL) Write(op string, db, block string, data []byte) error {
	compressed := false
	entryData := data

	if len(data) > 102400 {
		if compressedData, ok, err := compressData(data, CompressionZstd); err == nil && ok {
			entryData = compressedData
			compressed = true
		}
	}

	entry := WALEntry{
		ID:         w.currentID,
		Timestamp:  time.Now().UnixNano(),
		Op:         op,
		DB:         db,
		Block:      block,
		Data:       entryData,
		Checksum:   crc32.ChecksumIEEE(entryData),
		Compressed: compressed,
	}

	if w.streaming {
		select {
		case w.writeChan <- entry:
		case <-w.stopChan:
			return fmt.Errorf("WAL closed")
		}
	} else {
		w.mu.Lock()
		defer w.mu.Unlock()
		if w.encoder == nil {
			w.encoder = json.NewEncoder(w.currentSeg)
		}
		if err := w.encoder.Encode(entry); err != nil {
			return err
		}
		stat, err := w.currentSeg.Stat()
		if err != nil {
			return err
		}
		if stat.Size() >= w.maxSize {
			if err := w.rotate(); err != nil {
				return err
			}
		}
	}

	metricWALWrites.Inc()
	return nil
}

func (w *WAL) ReadAll() ([]WALEntry, error) {
	w.mu.Lock()
	defer w.mu.Unlock()

	var entries []WALEntry

	for _, segFile := range w.segments {
		f, err := os.Open(segFile)
		if err != nil {
			continue
		}
		dec := json.NewDecoder(f)
		for {
			var entry WALEntry
			if err := dec.Decode(&entry); err == io.EOF {
				break
			} else if err != nil {
				continue
			}
			entries = append(entries, entry)
		}
		f.Close()
	}

	return entries, nil
}

func (w *WAL) Close() error {
	close(w.stopChan)
	w.flushTicker.Stop()
	w.wg.Wait()

	w.mu.Lock()
	defer w.mu.Unlock()

	markerFile := filepath.Join(w.dir, ".clean")
	if err := os.WriteFile(markerFile, []byte("clean"), 0644); err != nil {
		log().Warn("Failed to write WAL clean marker", zap.Error(err))
	}

	if w.currentSeg != nil {
		return w.currentSeg.Close()
	}
	return nil
}

func (w *WAL) RecoverApply(engine *Engine) (int64, error) {
	if w.clean {
		log().Info("WAL clean shutdown, skipping recovery")
		return 0, nil
	}

	entries, err := w.ReadAll()
	if err != nil {
		return 0, err
	}

	if len(entries) == 0 {
		return 0, nil
	}

	log().Info("Starting WAL recovery",
		zap.Int("entries", len(entries)))

	applied := int64(0)
	batchSize := 5000

	for i := 0; i < len(entries); i += batchSize {
		end := i + batchSize
		if end > len(entries) {
			end = len(entries)
		}
		batch := entries[i:end]

		for _, entry := range batch {
			if crc32.ChecksumIEEE(entry.Data) != entry.Checksum {
				log().Warn("WAL entry checksum mismatch, skipping",
					zap.Uint64("id", entry.ID))
				continue
			}

			entryData := entry.Data
			if entry.Compressed {
				if decompressed, err := decompressData(entry.Data); err == nil {
					entryData = decompressed
				}
			}

			switch entry.Op {
			case "insert":
				var doc Document
				if err := json.Unmarshal(entryData, &doc); err != nil {
					continue
				}
				if _, err := engine.insertWithIDLocal(entry.DB, entry.Block, doc.ID, doc.Data, doc.ShardID); err != nil {
					log().Warn("WAL insert recovery failed", zap.Error(err))
					continue
				}
				applied++
			case "update":
				var op UpdateOp
				if err := json.Unmarshal(entryData, &op); err != nil {
					continue
				}
				if _, err := engine.updateLocal(entry.DB, entry.Block, nil, op, ""); err != nil {
					log().Warn("WAL update recovery failed", zap.Error(err))
					continue
				}
				applied++
			case "delete":
				var filters []Filter
				if err := json.Unmarshal(entryData, &filters); err != nil {
					continue
				}
				if _, err := engine.deleteLocal(entry.DB, entry.Block, filters, ""); err != nil {
					log().Warn("WAL delete recovery failed", zap.Error(err))
					continue
				}
				applied++
			}
		}

		if i > 0 && i%10000 == 0 {
			log().Info("WAL recovery progress",
				zap.Int("processed", i),
				zap.Int("total", len(entries)),
				zap.Int64("applied", applied))
		}
	}

	if applied > 0 {
		w.clean = true
		markerFile := filepath.Join(w.dir, ".clean")
		os.WriteFile(markerFile, []byte("clean"), 0644)
	}

	log().Info("WAL recovery completed",
		zap.Int64("applied", applied),
		zap.Int("entries", len(entries)))
	return applied, nil
}

func (w *WAL) Truncate() error {
	w.mu.Lock()
	defer w.mu.Unlock()

	if len(w.segments) > 1 {
		for i := 0; i < len(w.segments)-1; i++ {
			os.Remove(w.segments[i])
		}
		w.segments = w.segments[len(w.segments)-1:]
	}

	markerFile := filepath.Join(w.dir, ".clean")
	return os.WriteFile(markerFile, []byte("clean"), 0644)
}

func (w *WAL) Stats() map[string]any {
	w.mu.Lock()
	defer w.mu.Unlock()

	var totalSize int64
	for _, seg := range w.segments {
		if info, err := os.Stat(seg); err == nil {
			totalSize += info.Size()
		}
	}

	return map[string]any{
		"segments":    len(w.segments),
		"total_size":  fmtBytes(totalSize),
		"max_segs":    w.maxSegs,
		"max_size":    fmtBytes(w.maxSize),
		"clean":       w.clean,
		"streaming":   w.streaming,
		"current_id":  w.currentID,
		"buffer_pool": w.bufferPool.Stats(),
	}
}

func (w *WAL) Sync() error {
	w.mu.Lock()
	defer w.mu.Unlock()

	if w.currentSeg != nil {
		if err := w.currentSeg.Sync(); err != nil {
			return err
		}
	}
	return nil
}
