// Code generated by splitting main.go. Part of package main.
package novodb

import (
	"context"
	"go.uber.org/zap"
	"runtime"
	"runtime/debug"
	"sync"
	"sync/atomic"
)

type job struct {
	fn   func()
	ctx  context.Context
	name string
}

type workerPool struct {
	jobs   chan job
	wg     sync.WaitGroup
	mu     sync.Mutex
	done   bool
	active atomic.Int64
	queued atomic.Int64
}

func newWorkerPool(n int) *workerPool {
	if n <= 0 {
		n = runtime.GOMAXPROCS(0) * 64
	}
	p := &workerPool{
		jobs: make(chan job, n*256),
	}
	for i := 0; i < n; i++ {
		p.wg.Add(1)
		go p.worker()
	}
	return p
}

func (p *workerPool) Submit(ctx context.Context, name string, fn func()) {
	p.mu.Lock()
	if p.done {
		p.mu.Unlock()
		return
	}
	p.mu.Unlock()

	p.queued.Add(1)

	select {
	case p.jobs <- job{
		fn:   fn,
		ctx:  ctx,
		name: name,
	}:
		p.queued.Add(-1)

	case <-ctx.Done():
		p.queued.Add(-1)
		log().Warn("Job submission cancelled",
			zap.String("job", name),
			zap.Error(ctx.Err()),
		)
	}
}

func (p *workerPool) worker() {
	defer p.wg.Done()
	defer func() {
		if r := recover(); r != nil {
			log().Error("Worker panic recovered",
				zap.Any("panic", r),
				zap.String("stack", string(debug.Stack())),
			)
		}
	}()
	for job := range p.jobs {
		p.active.Add(1)
		func() {
			defer func() {
				if r := recover(); r != nil {
					log().Error("Job panic recovered",
						zap.Any("panic", r),
						zap.String("job", job.name),
						zap.String("stack", string(debug.Stack())),
					)
				}
				p.active.Add(-1)
			}()
			select {
			case <-job.ctx.Done():
				log().Warn("Job cancelled", zap.String("job", job.name))
				return
			default:
				job.fn()
			}
		}()
	}
}

func (p *workerPool) Close() {
	p.mu.Lock()
	if !p.done {
		p.done = true
		close(p.jobs)
	}
	p.mu.Unlock()
	p.wg.Wait()
}
